### ISSUE TITLE
 BITMEX: Failed to parse symbol information

### ISSUE THREAD

**Issue by maddrid** [bmoscon/cryptofeed#1035]
**Describe the bug**
master@PC MINGW64 /i/k/cryptofeed/examples
$ python demo_questdb.py
2024-05-15 13:22:49,608 : ERROR : BITMEX: Failed to parse symbol information: 'expiry'
Traceback (most recent call last):
  File "C:\Users\master\AppData\Roaming\Python\Python39\site-packages\cryptofeed\exchange.py", line 105, in symbol_mapping
    syms, info = cls._parse_symbol_data(data if len(data) > 1 else data[0])
  File "C:\Users\master\AppData\Roaming\Python\Python39\site-packages\cryptofeed\exchanges\bitmex.py", line 61, in _parse_symbol_data
    s = Symbol(base, quote, type=stype, expiry_date=entry['expiry'])
KeyError: 'expiry'
Traceback (most recent call last):
  File "I:\k\cryptofeed\examples\demo_questdb.py", line 29, in <module>
    main()
  File "I:\k\cryptofeed\examples\demo_questdb.py", line 20, in main
    f.add_feed(Bitmex(channels=[FUNDING, L2_BOOK], symbols=['BTC-USD-PERP'], callbacks={FUNDING: FundingQuest(host=QUEST_HOST, port=QUEST_PORT), L2_BOOK: BookQuest(host=QUEST_HOST, port=QUEST_PORT)}))
  File "C:\Users\master\AppData\Roaming\Python\Python39\site-packages\cryptofeed\feed.py", line 63, in __init__
    super().__init__(**kwargs)
  File "C:\Users\master\AppData\Roaming\Python\Python39\site-packages\cryptofeed\exchange.py", line 49, in __init__
    self.symbol_mapping()
  File "C:\Users\master\AppData\Roaming\Python\Python39\site-packages\cryptofeed\exchange.py", line 105, in symbol_mapping
    syms, info = cls._parse_symbol_data(data if len(data) > 1 else data[0])
  File "C:\Users\master\AppData\Roaming\Python\Python39\site-packages\cryptofeed\exchanges\bitmex.py", line 61, in _parse_symbol_data
    s = Symbol(base, quote, type=stype, expiry_date=entry['expiry'])
KeyError: 'expiry'

**To Reproduce**
run demo_questdb.py

**Operating System:**
wsl2 ,  windows  10

**Cryptofeed Version**
pip install cryptofeed

**Comment by bmoscon** [comment]
should be fixed now
