### ISSUE TITLE
Deribit TypeError during ohlcv feed

### ISSUE THREAD

**Issue by evanatyourservice** [bmoscon/cryptofeed#110]
While running:
```
async def ohlcv(data=None):
    print(data)

def main():
    f = FeedHandler()
    f.add_feed(Deribit(pairs=['BTC-PERPETUAL'], channels=[TRADES], callbacks={TRADES: OHLCV(Callback(ohlcv), window=10)}))

    f.run()
```

I get:
```
2019-07-02 21:52:04,892 : ERROR : DERIBIT: error handling message
2019-07-02 21:52:04,994 : ERROR : DERIBIT: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/cryptofeed/feedhandler.py", line 171, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/usr/local/lib/python3.6/dist-packages/cryptofeed/feedhandler.py", line 189, in _handler
    await handler(message)
  File "/usr/local/lib/python3.6/dist-packages/cryptofeed/deribit/deribit.py", line 193, in message_handler
    await self._trade(msg_dict)
  File "/usr/local/lib/python3.6/dist-packages/cryptofeed/deribit/deribit.py", line 82, in _trade
    timestamp=timestamp_normalize(self.id, trade['timestamp'])
  File "/usr/local/lib/python3.6/dist-packages/cryptofeed/backends/aggregate.py", line 67, in __call__
    self._agg(pair, amount, price)
  File "/usr/local/lib/python3.6/dist-packages/cryptofeed/backends/aggregate.py", line 51, in _agg
    self.data[pair]['volume'] += amount
TypeError: unsupported operand type(s) for +=: 'decimal.Decimal' and 'float'
```
This could very well be a problem on Deribit's side, I've had a lot of trouble with their API in the past in various ways.

**Comment by bmoscon** [comment]
fixed in master. The code to handle deribit's exchange interface was not converting values to decimal.Decimal properly.
