### ISSUE TITLE
Bitstamp L2/L3 problem

### ISSUE THREAD

**Issue by nateGeorge** [bmoscon/cryptofeed#127]
When trying to use cryptostore to store Bitstamp L2 or L3 data for BTC-USD using Redis and Arctic, the following error appears:

```python
2019-07-30 20:11:28,655 : ERROR : BITSTAMP: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptofeed-1.0.0-py3.6.egg/cryptofeed/feedhandler.py", line 174, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptofeed-1.0.0-py3.6.egg/cryptofeed/feedhandler.py", line 193, in _handler
    await handler(message, self.last_msg[feed_id])
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptofeed-1.0.0-py3.6.egg/cryptofeed/bitstamp/bitstamp.py", line 111, in message_handler
    await self._l2_book(msg)
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptofeed-1.0.0-py3.6.egg/cryptofeed/bitstamp/bitstamp.py", line 44, in _l2_book
    await self.book_callback(pair=pair, book_type=L2_BOOK, forced=False, delta=False, timestamp=timestamp)
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptofeed-1.0.0-py3.6.egg/cryptofeed/feed.py", line 61, in book_callback
    await self.callback(BOOK_DELTA, feed=self.id, pair=pair, delta=delta, timestamp=timestamp)
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptofeed-1.0.0-py3.6.egg/cryptofeed/feed.py", line 72, in callback
    await cb(**kwargs)
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptofeed-1.0.0-py3.6.egg/cryptofeed/backends/redis.py", line 165, in __call__
    book_delta_convert(delta, data, convert=self.numeric_type)
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptofeed-1.0.0-py3.6.egg/cryptofeed/backends/_util.py", line 12, in book_delta_convert
    for entry in delta[side]:
TypeError: 'bool' object is not subscriptable
```

It looks like L3 data should be available for bitstamp from the API page: https://www.bitstamp.net/api/
Other L2/L3 data like Coinbase seems to be working fine.

I started digging through the code, but get lost in feed.py with all the async code.  Any insights as to what's going on?

**Comment by nateGeorge** [comment]
I'm guess it's related to this? :  https://github.com/bmoscon/cryptostore/issues/25

Should be fixed when per-exchange delta config is available within cryptostore, right?

**Comment by bmoscon** [comment]
yes, its on master and has been fixed
