### ISSUE TITLE
Huobi L2 issue

### ISSUE THREAD

**Issue by nateGeorge** [bmoscon/cryptofeed#129]
Issue with BTC-USDT L2 on Huobi (using Redis and Arctic with cryptostore):

```python
2019-07-30 20:45:19,700 : ERROR : HUOBI_US: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptofeed-1.0.0-py3.6.egg/cryptofeed/feedhandler.py", line 174, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptofeed-1.0.0-py3.6.egg/cryptofeed/feedhandler.py", line 193, in _handler
    await handler(message, self.last_msg[feed_id])
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptofeed-1.0.0-py3.6.egg/cryptofeed/huobi/huobi.py", line 84, in message_handler
    await self._book(msg)
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptofeed-1.0.0-py3.6.egg/cryptofeed/huobi/huobi.py", line 47, in _book
    await self.book_callback(pair, L2_BOOK, False, False, timestamp_normalize(self.id, msg['ts']))
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptofeed-1.0.0-py3.6.egg/cryptofeed/feed.py", line 61, in book_callback
    await self.callback(BOOK_DELTA, feed=self.id, pair=pair, delta=delta, timestamp=timestamp)
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptofeed-1.0.0-py3.6.egg/cryptofeed/feed.py", line 72, in callback
    await cb(**kwargs)
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptofeed-1.0.0-py3.6.egg/cryptofeed/backends/redis.py", line 165, in __call__
    book_delta_convert(delta, data, convert=self.numeric_type)
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptofeed-1.0.0-py3.6.egg/cryptofeed/backends/_util.py", line 12, in book_delta_convert
    for entry in delta[side]:
TypeError: 'bool' object is not subscriptable
```

**Comment by nateGeorge** [comment]
Also related: Huobi US:

```python
2019-07-30 20:50:08,766 : ERROR : HUOBI_US: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptofeed-1.0.0-py3.6.egg/cryptofeed/feedhandler.py", line 174, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptofeed-1.0.0-py3.6.egg/cryptofeed/feedhandler.py", line 193, in _handler
    await handler(message, self.last_msg[feed_id])
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptofeed-1.0.0-py3.6.egg/cryptofeed/huobi/huobi.py", line 84, in message_handler
    await self._book(msg)
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptofeed-1.0.0-py3.6.egg/cryptofeed/huobi/huobi.py", line 47, in _book
    await self.book_callback(pair, L2_BOOK, False, False, timestamp_normalize(self.id, msg['ts']))
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptofeed-1.0.0-py3.6.egg/cryptofeed/feed.py", line 61, in book_callback
    await self.callback(BOOK_DELTA, feed=self.id, pair=pair, delta=delta, timestamp=timestamp)
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptofeed-1.0.0-py3.6.egg/cryptofeed/feed.py", line 72, in callback
    await cb(**kwargs)
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptofeed-1.0.0-py3.6.egg/cryptofeed/backends/redis.py", line 165, in __call__
    book_delta_convert(delta, data, convert=self.numeric_type)
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptofeed-1.0.0-py3.6.egg/cryptofeed/backends/_util.py", line 12, in book_delta_convert
    for entry in delta[side]:
TypeError: 'bool' object is not subscriptable
```

**Comment by nateGeorge** [comment]
Looks like it's related to this:  https://github.com/bmoscon/cryptostore/issues/25

Should be fixed when per-exchange delta config is available within cryptostore, right?

**Comment by xiandong79** [comment]
I have the same error message with Huobi L2.

**Comment by bmoscon** [comment]
this has been fixed on master (cryptostore). those exchnages dont support book deltas. I'll improve the config validation on the cryptofeed side as well so you'll know when you register for unsupported trading pairs or unsupported options (like book deltas).
