### ISSUE TITLE
Coinbene trades issues

### ISSUE THREAD

**Issue by nateGeorge** [bmoscon/cryptofeed#131]
Seems like getting Coinbene trades is having some issues.  Here are a few errors I've gotten trying to collect BTC-USDT and ETH-USDT data:

```python
2019-08-01 21:41:18,588 : INFO : trades-COINBENE-BTC-USDT: Read 1091543 messages from Redis
Task exception was never retrieved
future: <Task finished coro=<Aggregator.loop() done, defined at /home/nate/anaconda3/lib/python3.6/site-packages/cryptostore/aggregator/aggregator.py:38> exception=ConnectionError('Error 104 while writing to socket. Connection reset by peer.',)>
Traceback (most recent call last):
  File "/home/nate/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 649, in send_packed_command
    self._sock.sendall(item)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptostore/aggregator/aggregator.py", line 66, in loop
    cache.delete(exchange, dtype, pair)
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptostore/aggregator/redis.py", line 66, in delete
    self.conn.xdel(key, *self.ids[key])
  File "/home/nate/anaconda3/lib/python3.6/site-packages/redis/client.py", line 2124, in xdel
    return self.execute_command('XDEL', name, *ids)
  File "/home/nate/anaconda3/lib/python3.6/site-packages/redis/client.py", line 838, in execute_command
    conn.send_command(*args)
  File "/home/nate/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 670, in send_command
    check_health=kwargs.get('check_health', True))
  File "/home/nate/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 662, in send_packed_command
    (errno, errmsg))
redis.exceptions.ConnectionError: Error 104 while writing to socket. Connection reset by peer.
2019-08-01 21:44:06,613 : ERROR : COINBENE: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptofeed/feedhandler.py", line 145, in _rest_connect
    await feed.message_handler()
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptofeed/coinbene/coinbene.py", line 136, in message_handler
    await handle(session, pair, chan)
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptofeed/coinbene/coinbene.py", line 124, in handle
    await self._trades(session, pair)
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptofeed/coinbene/coinbene.py", line 55, in _trades
    data = await response.json()
  File "/home/nate/anaconda3/lib/python3.6/site-packages/aiohttp-4.0.0a0-py3.6-linux-x86_64.egg/aiohttp/client_reqrep.py", line 1032, in json
    return loads(self._body.decode(encoding))  # type: ignore
  File "/home/nate/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/nate/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/nate/anaconda3/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 110982 (char 110981)

```

```python
2019-08-01 22:07:17,269 : ERROR : COINBENE: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptofeed/feedhandler.py", line 145, in _rest_connect
    await feed.message_handler()
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptofeed/coinbene/coinbene.py", line 136, in message_handler
    await handle(session, pair, chan)
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptofeed/coinbene/coinbene.py", line 124, in handle
    await self._trades(session, pair)
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptofeed/coinbene/coinbene.py", line 55, in _trades
    data = await response.json()
  File "/home/nate/anaconda3/lib/python3.6/site-packages/aiohttp-4.0.0a0-py3.6-linux-x86_64.egg/aiohttp/client_reqrep.py", line 1032, in json
    return loads(self._body.decode(encoding))  # type: ignore
  File "/home/nate/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/nate/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/nate/anaconda3/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 256475 (char 256474)
```

**Comment by bmoscon** [comment]
just retested coinbene, I dont get these errors. was there an intermittent issue with the exchange when you tested this?

**Comment by bmoscon** [comment]
@nateGeorge let me know if you can reproduce this, otherwise I'll close it since its working fine for me.

**Comment by nateGeorge** [comment]
Yes, just retested and seems to be working.  Not sure what was wrong before.
