### ISSUE TITLE
Feature request: Order book deltas for Huobi and Huobi US

### ISSUE THREAD

**Issue by nateGeorge** [bmoscon/cryptofeed#135]
It would be nice to have order book deltas for Huobi for more efficient storage of data.  Most other exchanges seem to work with book deltas.  Trying to use a book delta with Huobi and Huobi US currently gives the following error (using it through cryptostore):

```python
2019-08-07 16:53:02,707 : ERROR : HUOBI: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptofeed/feedhandler.py", line 174, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptofeed/feedhandler.py", line 193, in _handler
    await handler(message, self.last_msg[feed_id])
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptofeed/huobi/huobi.py", line 84, in message_handler
    await self._book(msg)
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptofeed/huobi/huobi.py", line 47, in _book
    await self.book_callback(pair, L2_BOOK, False, False, timestamp_normalize(self.id, msg['ts']))
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptofeed/feed.py", line 61, in book_callback
    await self.callback(BOOK_DELTA, feed=self.id, pair=pair, delta=delta, timestamp=timestamp)
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptofeed/feed.py", line 72, in callback
    await cb(**kwargs)
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptofeed/backends/redis.py", line 165, in __call__
    book_delta_convert(delta, data, convert=self.numeric_type)
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptofeed/backends/_util.py", line 12, in book_delta_convert
    for entry in delta[side]:
TypeError: 'bool' object is not subscriptable
```

**Comment by xiandong79** [comment]
Also, currently Binance uses 'depth20' with a fixed depth ==20 instead of 'full book with book delta'.

I know that the full book of Binance is not consistent and stable.

**Comment by nateGeorge** [comment]
Good call. Going to take a look at all the book depths to make sure they are maxed, since they can be cut off in cryptostore config if desired.

**Comment by nateGeorge** [comment]
Started a discussion for Binance here: https://github.com/bmoscon/cryptofeed/issues/137

**Comment by bmoscon** [comment]
this is fixed now. with the max_depth= param you can set max depths and get deltas (if not supported by exchange already)
