### ISSUE TITLE
Multithreading data digest

### ISSUE THREAD

**Issue by rombin** [bmoscon/cryptofeed#15]
I might get this wrong, so apologies if I do. During a book retrieval callback you might want to save the data into DB. The speed of the write routine and update arrival frequency become important. If writing is too slow or arrival rate to high, the writing routine becomes a bottleneck.

No messages are lost (great!), due to `asyncio.ensure_future()` (correct??). But due to slow data digestion a queue starts forming (correct??). If you are dealing with multiple currencies, you might never be able to catch up with the queue. So maybe and idea is to abandon the queue, take a new snapshot and start again. You miss a few updates but perhaps that's ok for a small trader. Re-starting the whole process is not ideal though.

I guess one way to deal with this is to write producer/consumer where the consumer (writer) runs on a separate thread. In this way, the main thread (with the book update) runs happily and (in general) no queues are formed because the writing is on an independent thread and so it's not blocking the main thread. This assumes that you are saving snapshots of the order book though.

**Comment by bmoscon** [comment]
you should use async database connectors - eg. motor for Mongo, asyncpg for postgres, etc. This will drastically reduce the waiting for the DB operations. If you still have a lot of latency you might consider running sets of exchanges in different processes.

**Comment by bmoscon** [comment]
@rombin take a look at `examples/demo_arctic.py`. Its a vert short/small example, but I'm able to write `BTC-USD` + `ETH-USD` from 4 exchanges to an arctic db on a dual core, 2GHz machine (very low power and not very powerful) without losing any data, or experiencing very much latency.

**Comment by rombin** [comment]
this looks good, thank you

**Comment by DennyZen** [comment]
@bmoscon let me ask one more question about multithreading..

**Comment by DennyZen** [comment]
@bmoscon let me ask one more question about multithreading..
I am using cryptofeed in trading robot. count orderbook volumes  in needed way every 0.2 second.
BitMex is a huge market.  It can be hundreds updates in a second in overload periods .. 
Can it be that cryptofeed can't handle to process updates during that periods and they disappear?
I saw Some projects they put all updates in a queue and than another thread get it from there and process..

**Comment by bmoscon** [comment]
if you only need order books every .2 seconds, you can use the Throttle class in backends to wrap the book callback, it will throttle the data and deliver updates on that interval. 

Bitmex is pretty large but I haven't had issues with a data overload - it all depends on how fast to release the callback. You can also tweak the message queue size that websockets uses as well if you're losing data

**Comment by DennyZen** [comment]
thanks, i will try

**Comment by TnzGit** [comment]
> if you only need order books every .2 seconds, you can use the Throttle class in backends to wrap the book callback, it will throttle the data and deliver updates on that interval.
> 
> Bitmex is pretty large but I haven't had issues with a data overload - it all depends on how fast to release the callback. You can also tweak the message queue size that websockets uses as well if you're losing data

Hi bmoscon, I'm trying to do this exact thing with code as below:

`f.add_feed(FTX(channels=[L2_BOOK], symbols=['BTC-USD-PERP'], callbacks={L2_BOOK: Throttle(BookMongo(snapshots_only=True), window=60)}))`

However I'm getting this error message:

> Traceback (most recent call last):
  File "/home/dataloader-ubuntu/Documents/dataloader-combined-orderbook-snapshot/venv/lib/python3.10/site-packages/cryptofeed/connection_handler.py", line 69, in _create_connection
    await self._handler(connection, self.handler)
  File "/home/dataloader-ubuntu/Documents/dataloader-combined-orderbook-snapshot/venv/lib/python3.10/site-packages/cryptofeed/connection_handler.py", line 119, in _handler
    await handler(message, connection, self.conn.last_message)
  File "/home/dataloader-ubuntu/Documents/dataloader-combined-orderbook-snapshot/venv/lib/python3.10/site-packages/cryptofeed/exchanges/ftx.py", line 422, in message_handler
    await self._book(msg, timestamp)
  File "/home/dataloader-ubuntu/Documents/dataloader-combined-orderbook-snapshot/venv/lib/python3.10/site-packages/cryptofeed/exchanges/ftx.py", line 299, in _book
    await self.book_callback(L2_BOOK, self._l2_book[pair], timestamp, timestamp=float(msg['data']['time']), raw=msg, checksum=check)
  File "/home/dataloader-ubuntu/Documents/dataloader-combined-orderbook-snapshot/venv/lib/python3.10/site-packages/cryptofeed/feed.py", line 243, in book_callback
    await self.callback(book_type, book, receipt_timestamp)
  File "/home/dataloader-ubuntu/Documents/dataloader-combined-orderbook-snapshot/venv/lib/python3.10/site-packages/cryptofeed/feed.py", line 254, in callback
    await cb(obj, receipt_timestamp)
  File "/home/dataloader-ubuntu/Documents/dataloader-combined-orderbook-snapshot/venv/lib/python3.10/site-packages/cryptofeed/backends/aggregate.py", line 33, in __call__
    await self.handler(data, receipt_timestamp)
  File "/home/dataloader-ubuntu/Documents/dataloader-combined-orderbook-snapshot/venv/lib/python3.10/site-packages/cryptofeed/backends/backend.py", line 111, in __call__
    await self._write_snapshot(book, receipt_timestamp)
  File "/home/dataloader-ubuntu/Documents/dataloader-combined-orderbook-snapshot/venv/lib/python3.10/site-packages/cryptofeed/backends/backend.py", line 107, in _write_snapshot
    await self.write(data)
  File "/home/dataloader-ubuntu/Documents/dataloader-combined-orderbook-snapshot/venv/lib/python3.10/site-packages/cryptofeed/backends/backend.py", line 51, in write
    if self.multiprocess:
AttributeError: 'BookMongo' object has no attribute 'multiprocess'

I attempted to modify the `MongoCallback` class and added multiprocess attribute but then I get a new error of 

> AttributeError: 'BookMongo' object has no attribute 'queue'

It feels like this has gone beyond my capabilities so I came here to ask for help. Not sure if this is a bug or just me being dumb. Any help appreciated and thank you for all this fantastic work!

ubuntu 22.04, python 3.10.4, cryptofeed 2.2.3

**Comment by ivs** [comment]
Hi @TnzGit! I've ran into the same issue, check PR above
