### ISSUE TITLE
BITSTAMP - SSL error - ClientResponseError: 404, message='Not Found'

### ISSUE THREAD

**Issue by xiandong79** [bmoscon/cryptofeed#152]
```
    BITSTAMP:
        l2_book:
            symbols: [BTC-USD, ETH-USD, XRP-USD, LTC-USD, BCH-USD, ETH-BTC, LTC-BTC, XRP-BTC, BCH-BTC]
            book_depth: 100
        trades: [BTC-USD, ETH-USD, XRP-USD, LTC-USD, BCH-USD, ETH-BTC, LTC-BTC, XRP-BTC, BCH-BTC]
```

```
SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7fccd5219390>
transport: <_SelectorSocketTransport fd=22 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7fccd5219588>
transport: <_SelectorSocketTransport fd=25 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
2019-09-03 14:14:48,892 : ERROR : BITSTAMP: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/home/dong/.local/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 178, in _connect
    await feed.subscribe(websocket)
  File "/home/dong/.local/lib/python3.7/site-packages/cryptofeed/exchange/bitstamp.py", line 175, in subscribe
    await self._snapshot(snaps)
  File "/home/dong/.local/lib/python3.7/site-packages/cryptofeed/exchange/bitstamp.py", line 147, in _snapshot
    results = await asyncio.gather(*[fetch(session, url) for url in urls])
  File "/home/dong/.local/lib/python3.7/site-packages/cryptofeed/exchange/bitstamp.py", line 143, in fetch
    response.raise_for_status()
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/client_reqrep.py", line 942, in raise_for_status
    headers=self.headers)
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found'
```

with the latest code of the cryptostore and cryptofeed

This error happens after I **git pull the latest code** and **relaunch the cryptostore** program

**Comment by xiandong79** [comment]
https://github.com/aio-libs/aiohttp/issues/3535

it seems that it is a Python problem.

**Comment by bmoscon** [comment]
The bug report seems to indicate you should upgrade to 3.7.4, but not sure if that will actually fix it or not

**Comment by zhenpingfeng** [comment]
Not working with 3.7.4 still got 404
`
f = FeedHandler()
f.add_feed(Bitstamp(channels=[L2_BOOK], pairs=[
'BTC-USD', 'ETH-USD'], callbacks={L2_BOOK: BookRabbit(depth=1, port=5672)}))
f.run()
`
`2019-09-09 19:10:10,160 : ERROR : BITSTAMP: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/cryptofeed-1.0.1-py3.7.egg/cryptofeed/feedhandler.py", line 178, in _connect
    await feed.subscribe(websocket)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/cryptofeed-1.0.1-py3.7.egg/cryptofeed/exchange/bitstamp.py", line 175, in subscribe
    await self._snapshot(snaps)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/cryptofeed-1.0.1-py3.7.egg/cryptofeed/exchange/bitstamp.py", line 147, in _snapshot
    results = await asyncio.gather(*[fetch(session, url) for url in urls])
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/cryptofeed-1.0.1-py3.7.egg/cryptofeed/exchange/bitstamp.py", line 143, in fetch
    response.raise_for_status()
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/aiohttp-4.0.0a0-py3.7-linux-x86_64.egg/aiohttp/client_reqrep.py", line 942, in raise_for_status
    headers=self.headers)
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found'`

**Comment by zhenpingfeng** [comment]
When I sub with 1 pair `['BTC-USD']`, the connection is fine. But when I sub with multi-pair that like `pair=['BTC-USD', 'ETH-USD']`, I got `404, message='Not Found'`.

**Comment by bmoscon** [comment]
nothing i can do about this - it works for me, its likely an issue with your certs, isp, etc. Cryptofeed doesnt do any SSL handling directly, its all done via the 3rd party libraries it uses

**Comment by zhenpingfeng** [comment]
The old version before 8c6aa44 commit works fine for me. probably has some bug in the 8c6aa44 commit.

**Comment by zhenpingfeng** [comment]
https://github.com/bmoscon/cryptofeed/blob/8c6aa44605e1ba989b7f1357d346abcae4923ab2/cryptofeed/exchange/bitstamp.py#L139

**Comment by zhenpingfeng** [comment]
https://github.com/bmoscon/cryptofeed/blob/8c6aa44605e1ba989b7f1357d346abcae4923ab2/cryptofeed/exchange/bitstamp.py#L139 
The URL 'https://www.bitstamp.net/api/order_book/{sym}' should be 'https://www.bitstamp.net/api/v2/order_book/{sym}' for the alts pair, the URL 
https://www.bitstamp.net/api/v2/order_book/ltcusd work as expected. I will create a pull request to fix this.

**Comment by zhenpingfeng** [comment]
https://github.com/bmoscon/cryptofeed/pull/155/commits/1f9940b7fcdfeb77fae04f4cb9d020e280eca21c Its been fixed.

**Comment by bmoscon** [comment]
merged
