### ISSUE TITLE
Handle ConnectionClosed exceptions

### ISSUE THREAD

**Issue by bmoscon** [bmoscon/cryptofeed#16]
Websocket connections can be closed for a variety of reasons. These should be handled and the connection re-established if possible. Some tracebacks from my server:

```
Error in data transfer
Traceback (most recent call last):
  File "/home/bryant/anaconda3/envs/cryptofeed/lib/python3.6/site-packages/websockets-4.0.1-py3.6-linux-x86_64.egg/websockets/protocol.py", line 496, in transfer_data
    msg = yield from self.read_message()
  File "/home/bryant/anaconda3/envs/cryptofeed/lib/python3.6/site-packages/websockets-4.0.1-py3.6-linux-x86_64.egg/websockets/protocol.py", line 526, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "/home/bryant/anaconda3/envs/cryptofeed/lib/python3.6/site-packages/websockets-4.0.1-py3.6-linux-x86_64.egg/websockets/protocol.py", line 591, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "/home/bryant/anaconda3/envs/cryptofeed/lib/python3.6/site-packages/websockets-4.0.1-py3.6-linux-x86_64.egg/websockets/protocol.py", line 632, in read_frame
    extensions=self.extensions,
  File "/home/bryant/anaconda3/envs/cryptofeed/lib/python3.6/site-packages/websockets-4.0.1-py3.6-linux-x86_64.egg/websockets/framing.py", line 100, in read
    data = yield from reader(2)
  File "/home/bryant/anaconda3/envs/cryptofeed/lib/python3.6/asyncio/streams.py", line 663, in readexactly
    raise self._exception
  File "/home/bryant/anaconda3/envs/cryptofeed/lib/python3.6/asyncio/selector_events.py", line 723, in _read_ready
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer
Error in data transfer
Traceback (most recent call last):
  File "/home/bryant/anaconda3/envs/cryptofeed/lib/python3.6/site-packages/websockets-4.0.1-py3.6-linux-x86_64.egg/websockets/protocol.py", line 496, in transfer_data
    msg = yield from self.read_message()
  File "/home/bryant/anaconda3/envs/cryptofeed/lib/python3.6/site-packages/websockets-4.0.1-py3.6-linux-x86_64.egg/websockets/protocol.py", line 526, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "/home/bryant/anaconda3/envs/cryptofeed/lib/python3.6/site-packages/websockets-4.0.1-py3.6-linux-x86_64.egg/websockets/protocol.py", line 591, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "/home/bryant/anaconda3/envs/cryptofeed/lib/python3.6/site-packages/websockets-4.0.1-py3.6-linux-x86_64.egg/websockets/protocol.py", line 632, in read_frame
    extensions=self.extensions,
  File "/home/bryant/anaconda3/envs/cryptofeed/lib/python3.6/site-packages/websockets-4.0.1-py3.6-linux-x86_64.egg/websockets/framing.py", line 100, in read
    data = yield from reader(2)
  File "/home/bryant/anaconda3/envs/cryptofeed/lib/python3.6/asyncio/streams.py", line 663, in readexactly
    raise self._exception
  File "/home/bryant/anaconda3/envs/cryptofeed/lib/python3.6/asyncio/selector_events.py", line 723, in _read_ready
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer
Task exception was never retrieved
future: <Task finished coro=<FeedHandler._connect() done, defined at /home/bryant/workspace/cryptofeed/cryptofeed/feedhandler.py:41> exception=ConnectionClosed('WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason',)>
Traceback (most recent call last):
  File "/home/bryant/workspace/cryptofeed/cryptofeed/feedhandler.py", line 44, in _connect
    await self._handler(websocket, feed.message_handler)
  File "/home/bryant/workspace/cryptofeed/cryptofeed/feedhandler.py", line 47, in _handler
    async for message in websocket:
  File "/home/bryant/anaconda3/envs/cryptofeed/lib/python3.6/site-packages/websockets-4.0.1-py3.6-linux-x86_64.egg/websockets/py36/protocol.py", line 15, in __aiter__
    yield await self.recv()
  File "/home/bryant/anaconda3/envs/cryptofeed/lib/python3.6/site-packages/websockets-4.0.1-py3.6-linux-x86_64.egg/websockets/protocol.py", line 323, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason
Task exception was never retrieved
future: <Task finished coro=<FeedHandler._connect() done, defined at /home/bryant/workspace/cryptofeed/cryptofeed/feedhandler.py:41> exception=ConnectionClosed('WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason',)>
Traceback (most recent call last):
  File "/home/bryant/workspace/cryptofeed/cryptofeed/feedhandler.py", line 44, in _connect
    await self._handler(websocket, feed.message_handler)
  File "/home/bryant/workspace/cryptofeed/cryptofeed/feedhandler.py", line 47, in _handler
    async for message in websocket:
  File "/home/bryant/anaconda3/envs/cryptofeed/lib/python3.6/site-packages/websockets-4.0.1-py3.6-linux-x86_64.egg/websockets/py36/protocol.py", line 15, in __aiter__
    yield await self.recv()
  File "/home/bryant/anaconda3/envs/cryptofeed/lib/python3.6/site-packages/websockets-4.0.1-py3.6-linux-x86_64.egg/websockets/protocol.py", line 323, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason
Task exception was never retrieved
future: <Task finished coro=<FeedHandler._connect() done, defined at /home/bryant/workspace/cryptofeed/cryptofeed/feedhandler.py:41> exception=ConnectionClosed('WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason',)>
Traceback (most recent call last):
  File "/home/bryant/workspace/cryptofeed/cryptofeed/feedhandler.py", line 44, in _connect
    await self._handler(websocket, feed.message_handler)
  File "/home/bryant/workspace/cryptofeed/cryptofeed/feedhandler.py", line 47, in _handler
    async for message in websocket:
  File "/home/bryant/anaconda3/envs/cryptofeed/lib/python3.6/site-packages/websockets-4.0.1-py3.6-linux-x86_64.egg/websockets/py36/protocol.py", line 15, in __aiter__
    yield await self.recv()
  File "/home/bryant/anaconda3/envs/cryptofeed/lib/python3.6/site-packages/websockets-4.0.1-py3.6-linux-x86_64.egg/websockets/protocol.py", line 323, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason
```

```
Task exception was never retrieved
future: <Task finished coro=<FeedHandler._connect() done, defined at /home/bryant/workspace/cryptofeed/cryptofeed/feedhandler.py:41> exception=ConnectionClosed('WebSocket connection is closed: code = 1001 (going away), reason = CloudFlare WebSocket proxy restarting',)>
Traceback (most recent call last):
  File "/home/bryant/workspace/cryptofeed/cryptofeed/feedhandler.py", line 44, in _connect
    await self._handler(websocket, feed.message_handler)
  File "/home/bryant/workspace/cryptofeed/cryptofeed/feedhandler.py", line 47, in _handler
    async for message in websocket:
  File "/home/bryant/anaconda3/envs/cryptofeed/lib/python3.6/site-packages/websockets-4.0.1-py3.6-linux-x86_64.egg/websockets/py36/protocol.py", line 15, in __aiter__
    yield await self.recv()
  File "/home/bryant/anaconda3/envs/cryptofeed/lib/python3.6/site-packages/websockets-4.0.1-py3.6-linux-x86_64.egg/websockets/protocol.py", line 323, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1001 (going away), reason = CloudFlare WebSocket proxy restarting
```

**Comment by eliquinox** [comment]
Hi Bryant,

Have you managed to fix the ConncetionClosed exception at all?
I have ran into this issue myself many times with a number of exchanges and as such do not know a working solution.

**Comment by bmoscon** [comment]
i merged in a partial solution - when the exceptions are received, it will attempt to reconnect. The other issue the rest of my changes address (unmerged) are when the connection goes dead but there is no disconnect. They will kill the connection and reconnect.
