### ISSUE TITLE
ImportError: cannot import name 'FeedHandler' from 'cryptofeed' 

### ISSUE THREAD

**Issue by lkthomas** [bmoscon/cryptofeed#181]
`from cryptofeed import FeedHandler`
`ticker_cb = {TICKER: TickerCallback(ticker)}`
`trade_cb = {TRADES: TradeCallback(trade)}`
`gemini_cb = {TRADES: TradeCallback(trade), L2_BOOK: BookCallback(book)}`
`FeedHandler().add_feed(Bitfinex(pairs=['BTC-USD'], channels=[TICKER], callbacks=ticker_cb))`
`FeedHandler().run()`

Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 31, in <module>
    start(fakepyfile,mainpyfile)
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 30, in start
    exec(open(mainpyfile).read(),  __main__.__dict__)
  File "<string>", line 1, in <module>
  File "/sdcard/Documents/Bitfinex tick data/cryptofeed.py", line 1, in <module>
    from cryptofeed import FeedHandler
ImportError: cannot import name 'FeedHandler' from 'cryptofeed' (/sdcard/Documents/Bitfinex tick data/cryptofeed.py)

**Comment by lkthomas** [comment]
My mistake, name the file conflict with the module, sorry.
