### ISSUE TITLE
TRADES and L2_BOOK not writing to InfluxDB for Bittrex

### ISSUE THREAD

**Issue by arrrbeee** [bmoscon/cryptofeed#183]
I'm trying to re-use the callback for InfluxDB from `examples/demo_influxdb.py` for Bittrex orderbook and trade data like so:

```python
from cryptofeed.backends.influxdb import TradeInflux, BookInflux, BookDeltaInflux, TickerInflux
from cryptofeed import FeedHandler
from cryptofeed.exchanges import Bittrex

from cryptofeed.defines import TRADES, L2_BOOK, BOOK_DELTA, TICKER

bittrex_pairs = ['BTC-USD', 'ETH-USD']


def main():
    f = FeedHandler()
    f.add_feed(Bittrex(channels=[TRADES], pairs=bittrex_pairs, callbacks={TRADES: TradeInflux('http://localhost:8086', 'crypto')}))
    f.add_feed(Bittrex(channels=[L2_BOOK], pairs=bittrex_pairs, callbacks={L2_BOOK: BookInflux('http://localhost:8086', 'crypto', numeric_type=float), BOOK_DELTA: BookDeltaInflux('http://localhost:8086', 'crypto', numeric_type=float)}))
    f.add_feed(Bittrex(channels=[TICKER], pairs=bittrex_pairs, callbacks={TICKER: TickerInflux('http://localhost:8086', 'crypto', numeric_type=float)}))
    f.run()


if __name__ == '__main__':
    main()
```

However, when I run the above, it seems to only grab the `ticker-BITTREX` measurement in Influx; it's missing the `trades-BITTREX` and `book-BITTREX` measurements (when I just query `show measurements;` at the Influx console)

What am I doing wrong here?

**Comment by bmoscon** [comment]
There is nothing obviously wrong with your example. I can try and reproduce it. If you don't write to influx, but instead log the updates to the console, do you get any book updates?

**Comment by arrrbeee** [comment]
@bmoscon I think it has something to do with passing a list as a param.

See the below minimally-viable example:

```python
from cryptofeed.callback import TickerCallback, TradeCallback, BookCallback
from cryptofeed import FeedHandler
from cryptofeed.exchanges import Bittrex
from cryptofeed.defines import L2_BOOK, BID, ASK, TRADES, TICKER

bittrex_pairs = ['BTC-USD', 'ETH-USD', 'ETH-BTC']


async def ticker(feed, pair, bid, ask, timestamp):
    print(f'Timestamp: {timestamp} Feed: {feed} Pair: {pair} Bid: {bid} Ask: {ask}')


async def trade(feed, pair, order_id, timestamp, side, amount, price):
    print(f"Timestamp: {timestamp} Feed: {feed} Pair: {pair} ID: {order_id} Side: {side} Amount: {amount} Price: {price}")


async def book(feed, pair, book, timestamp):
    print(f'Timestamp: {timestamp} Feed: {feed} Pair: {pair} Book Bid Size is {len(book[BID])} Ask Size is {len(book[ASK])}')


def main():
    f = FeedHandler()
    # f.add_feed(Bittrex(config={TRADES: ['BTC-USD'], TICKER: ['ETH-USD'], L2_BOOK: ['BTC-USDT']}, callbacks={L2_BOOK: BookCallback(book), TICKER: TickerCallback(ticker), TRADES: TradeCallback(trade)}))  # works
    # f.add_feed(Bittrex(config={TRADES: ['BTC-USD']}, callbacks={TRADES: TradeCallback(trade)})) # works
    # f.add_feed(Bittrex(config={L2_BOOK: ['ETH-BTC']}, callbacks={L2_BOOK: BookCallback(book)})) # works
    f.add_feed(Bittrex(config={L2_BOOK: bittrex_pairs}, callbacks={L2_BOOK: BookCallback(book)})) # this doesn't work
    f.run()


if __name__ == '__main__':
    main()
```

The line that doesn't run is this one: `f.add_feed(Bittrex(config={L2_BOOK: bittrex_pairs}, callbacks={L2_BOOK: BookCallback(book)}))`, but if you set `L2_BOOK: ['ETH-USD']` (basically any 1-element list), everything works as it should.

Is this a bug or by-design? :)

**Comment by bmoscon** [comment]
I should work with a list of pairs, let me take a look

**Comment by bmoscon** [comment]
I tested your first example (with the list of pairs) and it works for me - I got the following output on Linux with Python3.7

```
Timestamp: 1576352814.2824872 Feed: BITTREX Pair: ETH-BTC Book Bid Size is 500 Ask Size is 500
Timestamp: 1576352814.3603346 Feed: BITTREX Pair: BTC-USD Book Bid Size is 500 Ask Size is 500
Timestamp: 1576352814.3717425 Feed: BITTREX Pair: ETH-USD Book Bid Size is 261 Ask Size is 500
Timestamp: 1576352814.3806503 Feed: BITTREX Pair: ETH-USD Book Bid Size is 261 Ask Size is 500
Timestamp: 1576352814.3809884 Feed: BITTREX Pair: ETH-BTC Book Bid Size is 500 Ask Size is 500
Timestamp: 1576352814.5868714 Feed: BITTREX Pair: ETH-BTC Book Bid Size is 500 Ask Size is 500
Timestamp: 1576352814.9374766 Feed: BITTREX Pair: ETH-BTC Book Bid Size is 500 Ask Size is 500
Timestamp: 1576352814.9381957 Feed: BITTREX Pair: BTC-USD Book Bid Size is 500 Ask Size is 500
Timestamp: 1576352815.0410032 Feed: BITTREX Pair: BTC-USD Book Bid Size is 500 Ask Size is 500
Timestamp: 1576352815.0484657 Feed: BITTREX Pair: ETH-BTC Book Bid Size is 500 Ask Size is 500
Timestamp: 1576352815.3050256 Feed: BITTREX Pair: ETH-BTC Book Bid Size is 500 Ask Size is 500
Timestamp: 1576352815.3303907 Feed: BITTREX Pair: BTC-USD Book Bid Size is 500 Ask Size is 500
Timestamp: 1576352815.7084706 Feed: BITTREX Pair: ETH-BTC Book Bid Size is 500 Ask Size is 500
Timestamp: 1576352815.7084706 Feed: BITTREX Pair: BTC-USD Book Bid Size is 500 Ask Size is 500
Timestamp: 1576352815.8830373 Feed: BITTREX Pair: ETH-BTC Book Bid Size is 500 Ask Size is 500
Timestamp: 1576352815.8830373 Feed: BITTREX Pair: BTC-USD Book Bid Size is 500 Ask Size is 500
Timestamp: 1576352815.8879077 Feed: BITTREX Pair: ETH-USD Book Bid Size is 261 Ask Size is 500
Timestamp: 1576352816.129737 Feed: BITTREX Pair: ETH-BTC Book Bid Size is 500 Ask Size is 500
Timestamp: 1576352816.129737 Feed: BITTREX Pair: ETH-USD Book Bid Size is 259 Ask Size is 500
Timestamp: 1576352816.1506765 Feed: BITTREX Pair: BTC-USD Book Bid Size is 500 Ask Size is 500
Timestamp: 1576352816.3722057 Feed: BITTREX Pair: ETH-BTC Book Bid Size is 500 Ask Size is 500
Timestamp: 1576352816.3726978 Feed: BITTREX Pair: ETH-USD Book Bid Size is 260 Ask Size is 500
Timestamp: 1576352816.7813332 Feed: BITTREX Pair: ETH-BTC Book Bid Size is 500 Ask Size is 500
Timestamp: 1576352816.806778 Feed: BITTREX Pair: ETH-USD Book Bid Size is 260 Ask Size is 500
```
etc

**Comment by bmoscon** [comment]
Can you confirm you're using the latest version (i.e. running whats in master, not in pypi)?

**Comment by arrrbeee** [comment]
Updated to latest `master`, then ran `python setup.py install` and now I get the following error (in Windows):

```
2019-12-30 13:47:18,944 : ERROR : Unhandled exception
Traceback (most recent call last):
  File "C:\Users\xxx\Anaconda3\lib\site-packages\cryptofeed\feedhandler.py", line 124, in run
    loop.run_forever()
  File "C:\Users\xxx\Anaconda3\lib\asyncio\base_events.py", line 526, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
``` 

Is there something wrong w/ my `asyncio`? Similar error: https://stackoverflow.com/questions/46827007/runtimeerror-this-event-loop-is-already-running-in-python

**Comment by bmoscon** [comment]
@arrrbeee technically windows isnt supported. So could be a windows thing, or could be a python version thing (python 3.7+ only) or could be an error with the way you're using the library, can't tell without more information .

**Comment by bmoscon** [comment]
@arrrbeee also when i tested bittrex myself it worked as expected, so please re-open if you have the same issue with the latest code from master on github
