### ISSUE TITLE
Non-periodic connection error of orderbook deltas with Binance due to websocket error

### ISSUE THREAD

**Issue by heartcored98** [bmoscon/cryptofeed#196]
I am logging the Binance L2 order book delta data into the influxDB with `ETH-USDT` and `BTC-USDT` pairs. 

However, I observed that data incoming is unstable and caused missing data time interval. 

The screenshot is the capture of the InfluxDB data explorer(x-axis is time and y-axis is amount of the delta). Purple dots are for BTC-USDT and Cyan dots are for ETH-USDT. 

As we can see, data incoming only last for 2~10 mins and continued after several minutes or hours.

<img width="1538" alt="스크린샷 2020-01-09 오전 1 21 52" src="https://user-images.githubusercontent.com/33013451/71995907-ab558c80-327e-11ea-83ef-69a8b5fdf534.png">

Error logs show that websocket is closed with no reason like below.  

Do you have any idea for storing order book data continuously?  

Thank you for your time

```
Traceback (most recent call last):
  File "../cryptofeed/feedhandler.py", line 197, in _connect
    await self._handler(websocket, feed.message_handler, feed.uuid)
  File "../cryptofeed/feedhandler.py", line 220, in _handler
    async for message in websocket:
  File "/opt/conda/envs/coindb/lib/python3.7/site-packages/websockets/protocol.py", line 439, in __aiter__
    yield await self.recv()
  File "/opt/conda/envs/coindb/lib/python3.7/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/opt/conda/envs/coindb/lib/python3.7/site-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
2020-01-08 16:29:04,283 : ERROR : POST to https://us-west-2-1.aws.cloud2.influxdata.com/api/v2/write?org=myorg&bucket=coindb&precision=ns failed: 400 - {"code":"invalid","message":"writing requires points"}
Future exception was never retrieved
future: <Future finished exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), noreason')>
Traceback (most recent call last):
  File "/opt/conda/envs/coindb/lib/python3.7/site-packages/websockets/protocol.py", line 838, in transfer_data
    await asyncio.shield(self._put_message_waiter)
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
Future exception was never retrieved
future: <Future finished exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), noreason')>
Traceback (most recent call last):
  File "/opt/conda/envs/coindb/lib/python3.7/site-packages/websockets/protocol.py", line 838, in transfer_data
    await asyncio.shield(self._put_message_waiter)
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
Future exception was never retrieved
future: <Future finished exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), noreason')>
Traceback (most recent call last):
  File "/opt/conda/envs/coindb/lib/python3.7/site-packages/websockets/protocol.py", line 838, in transfer_data
    await asyncio.shield(self._put_message_waiter)
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
Future exception was never retrieved
future: <Future finished exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), noreason')>
Traceback (most recent call last):
  File "/opt/conda/envs/coindb/lib/python3.7/site-packages/websockets/protocol.py", line 838, in transfer_data
    await asyncio.shield(self._put_message_waiter)
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
Future exception was never retrieved
future: <Future finished exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), noreason')>
Traceback (most recent call last):
  File "/opt/conda/envs/coindb/lib/python3.7/site-packages/websockets/protocol.py", line 838, in transfer_data
    await asyncio.shield(self._put_message_waiter)
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
Future exception was never retrieved
future: <Future finished exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), noreason')>
Traceback (most recent call last):
  File "/opt/conda/envs/coindb/lib/python3.7/site-packages/websockets/protocol.py", line 838, in transfer_data
    await asyncio.shield(self._put_message_waiter)
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
Future exception was never retrieved
future: <Future finished exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), noreason')>
Traceback (most recent call last):
  File "/opt/conda/envs/coindb/lib/python3.7/site-packages/websockets/protocol.py", line 838, in transfer_data
    await asyncio.shield(self._put_message_waiter)
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
Future exception was never retrieved
future: <Future finished exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), noreason')>
Traceback (most recent call last):
  File "/opt/conda/envs/coindb/lib/python3.7/site-packages/websockets/protocol.py", line 838, in transfer_data
    await asyncio.shield(self._put_message_waiter)
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
Future exception was never retrieved
future: <Future finished exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), noreason')>
Traceback (most recent call last):
  File "/opt/conda/envs/coindb/lib/python3.7/site-packages/websockets/protocol.py", line 838, in transfer_data
    await asyncio.shield(self._put_message_waiter)
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
Future exception was never retrieved
future: <Future finished exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), noreason')>
Traceback (most recent call last):
  File "/opt/conda/envs/coindb/lib/python3.7/site-packages/websockets/protocol.py", line 838, in transfer_data
    await asyncio.shield(self._put_message_waiter)
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
Future exception was never retrieved
future: <Future finished exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), noreason')>
Traceback (most recent call last):
  File "/opt/conda/envs/coindb/lib/python3.7/site-packages/websockets/protocol.py", line 838, in transfer_data
    await asyncio.shield(self._put_message_waiter)
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
Future exception was never retrieved
future: <Future finished exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), noreason')>
Traceback (most recent call last):
  File "/opt/conda/envs/coindb/lib/python3.7/site-packages/websockets/protocol.py", line 838, in transfer_data
    await asyncio.shield(self._put_message_waiter)
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
Future exception was never retrieved
future: <Future finished exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), noreason')>
Traceback (most recent call last):
  File "/opt/conda/envs/coindb/lib/python3.7/site-packages/websockets/protocol.py", line 838, in transfer_data
    await asyncio.shield(self._put_message_waiter)
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
Future exception was never retrieved
future: <Future finished exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), noreason')>
Traceback (most recent call last):
  File "/opt/conda/envs/coindb/lib/python3.7/site-packages/websockets/protocol.py", line 838, in transfer_data
    await asyncio.shield(self._put_message_waiter)
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
Future exception was never retrieved
future: <Future finished exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), noreason')>
Traceback (most recent call last):
  File "/opt/conda/envs/coindb/lib/python3.7/site-packages/websockets/protocol.py", line 838, in transfer_data
    await asyncio.shield(self._put_message_waiter)
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
Future exception was never retrieved
future: <Future finished exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), noreason')>
Traceback (most recent call last):
  File "/opt/conda/envs/coindb/lib/python3.7/site-packages/websockets/protocol.py", line 838, in transfer_data
    await asyncio.shield(self._put_message_waiter)
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
Future exception was never retrieved
future: <Future finished exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), noreason')>
Traceback (most recent call last):
  File "/opt/conda/envs/coindb/lib/python3.7/site-packages/websockets/protocol.py", line 838, in transfer_data
    await asyncio.shield(self._put_message_waiter)
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
Future exception was never retrieved
future: <Future finished exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), noreason')>
Traceback (most recent call last):
  File "/opt/conda/envs/coindb/lib/python3.7/site-packages/websockets/protocol.py", line 838, in transfer_data
    await asyncio.shield(self._put_message_waiter)
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
Future exception was never retrieved
future: <Future finished exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), noreason')>
Traceback (most recent call last):
  File "/opt/conda/envs/coindb/lib/python3.7/site-packages/websockets/protocol.py", line 838, in transfer_data
    await asyncio.shield(self._put_message_waiter)
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
Future exception was never retrieved
future: <Future finished exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), noreason')>
Traceback (most recent call last):
  File "/opt/conda/envs/coindb/lib/python3.7/site-packages/websockets/protocol.py", line 838, in transfer_data
    await asyncio.shield(self._put_message_waiter)
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
2020-01-08 16:29:34,292 : ERROR : BITFINEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "../cryptofeed/feedhandler.py", line 197, in _connect
    await self._handler(websocket, feed.message_handler, feed.uuid)
  File "../cryptofeed/feedhandler.py", line 222, in _handler
    await handler(message, self.last_msg[feed_id])
  File "../cryptofeed/exchange/bitfinex.py", line 273, in message_handler
    await self.channel_map[chan_id]['handler'](msg, timestamp)
  File "../cryptofeed/exchange/bitfinex.py", line 180, in _book
    await self.book_callback(self.l2_book[pair], L2_BOOK, pair, forced, delta, timestamp)
  File "../cryptofeed/feed.py", line 86, in book_callback
    await self.callback(BOOK_DELTA, feed=self.id, pair=pair, delta=delta, timestamp=timestamp)
  File "../cryptofeed/feed.py", line 104, in callback
    await cb(**kwargs)
  File "../cryptofeed/backends/backend.py", line 25, in __call__
    await self.write(feed, pair, timestamp, data)
  File "../cryptofeed/backends/influxdb.py", line 141, in write
    await self._write_rows(start, data, timestamp)
  File "../cryptofeed/backends/influxdb.py", line 129, in _write_rows
    await self.http_write('POST', '\n'.join(msg), self.headers)
  File "../cryptofeed/backends/http.py", line 33, in http_write
    resp.raise_for_status()
  File "/opt/conda/envs/coindb/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 946, in raise_for_status
    headers=self.headers)
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://us-west-2-1.aws.cloud2.influxdata.com/api/v2/write?org=whwodud9@gmail.com&bucket=coindb&precision=ns')
2020-01-08 16:30:50,805 : ERROR : POST to https://us-west-2-1.aws.cloud2.influxdata.com/api/v2/write?org=myorg&bucket=coindb&precision=ns failed: 400 - {"code":"invalid","message":"writing requires points"}
Future exception was never retrieved
future: <Future finished exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), noreason')>
Traceback (most recent call last):
  File "/opt/conda/envs/coindb/lib/python3.7/site-packages/websockets/protocol.py", line 838, in transfer_data
    await asyncio.shield(self._put_message_waiter)
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
Future exception was never retrieved
future: <Future finished exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), noreason')>
Traceback (most recent call last):
  File "/opt/conda/envs/coindb/lib/python3.7/site-packages/websockets/protocol.py", line 838, in transfer_data
    await asyncio.shield(self._put_message_waiter)
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
Future exception was never retrieved
future: <Future finished exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), noreason')>
Traceback (most recent call last):
  File "/opt/conda/envs/coindb/lib/python3.7/site-packages/websockets/protocol.py", line 838, in transfer_data
    await asyncio.shield(self._put_message_waiter)
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
Future exception was never retrieved
future: <Future finished exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), noreason')>
Traceback (most recent call last):
  File "/opt/conda/envs/coindb/lib/python3.7/site-packages/websockets/protocol.py", line 838, in transfer_data
    await asyncio.shield(self._put_message_waiter)
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
2020-01-08 16:31:20,843 : ERROR : BINANCE: encountered an exception, reconnecting
Traceback (most recent call last):
  File "../cryptofeed/feedhandler.py", line 197, in _connect
    await self._handler(websocket, feed.message_handler, feed.uuid)
  File "../cryptofeed/feedhandler.py", line 222, in _handler
    await handler(message, self.last_msg[feed_id])
  File "../cryptofeed/exchange/binance.py", line 201, in message_handler
    await self._book(msg, pair, timestamp)
  File "../cryptofeed/exchange/binance.py", line 188, in _book
    await self.book_callback(self.l2_book[pair], L2_BOOK, pair, forced, delta, timestamp_normalize(self.id, timestamp))
  File "../cryptofeed/feed.py", line 86, in book_callback
    await self.callback(BOOK_DELTA, feed=self.id, pair=pair, delta=delta, timestamp=timestamp)
  File "../cryptofeed/feed.py", line 104, in callback
    await cb(**kwargs)
  File "../cryptofeed/backends/backend.py", line 25, in __call__
    await self.write(feed, pair, timestamp, data)
  File "../cryptofeed/backends/influxdb.py", line 141, in write
    await self._write_rows(start, data, timestamp)
  File "../cryptofeed/backends/influxdb.py", line 129, in _write_rows
    await self.http_write('POST', '\n'.join(msg), self.headers)
  File "../cryptofeed/backends/http.py", line 33, in http_write
    resp.raise_for_status()
  File "/opt/conda/envs/coindb/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 946, in raise_for_status
    headers=self.headers)
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://us-west-2-1.aws.cloud2.influxdata.com/api/v2/write?org=myorg&bucket=coindb&precision=ns')
```   

And below is modified version of the `demo_influxdb.py`. I masked my influxdb address.  

```
'''
Copyright (C) 2018-2019  Bryant Moscon - bmoscon@gmail.com

Please see the LICENSE file for the terms and conditions
associated with this software.
'''

from cryptofeed.backends.influxdb import TradeInflux, FundingInflux, BookInflux, BookDeltaInflux, TickerInflux
from cryptofeed import FeedHandler
from cryptofeed.exchanges import Bitmex, Coinbase, Bitfinex, Binance

from cryptofeed.defines import TRADES, FUNDING, L2_BOOK, BOOK_DELTA, TICKER



def main():

    # For InfluxDB 2.0, provide additional org, bucket(instead of db), token and precision(optional) 
    # [Note] In order to use visualization and aggregation, numeric_type with float is strongly recommended. 
    
    ADDR = 'https://us-west-2-1.aws.cloud2.influxdata.com'
    ORG='my-org'
    BUCKET = 'coindb'
    TOKEN = 'my-token'
    
    f = FeedHandler()
    funding_influx = FundingInflux(ADDR, org=ORG, bucket=BUCKET, token=TOKEN, numeric_type=float, precision='ns') 
    trade_influx = TradeInflux(ADDR, org=ORG, bucket=BUCKET, token=TOKEN, numeric_type=float, precision='ns') 
    book_influx = BookInflux(ADDR, org=ORG, bucket=BUCKET, token=TOKEN, numeric_type=float, precision='ns') 
    bookdelta_influx_eth = BookDeltaInflux(ADDR, org=ORG, bucket=BUCKET, token=TOKEN, numeric_type=float, precision='ns') 
    bookdelta_influx_btc = BookDeltaInflux(ADDR, org=ORG, bucket=BUCKET, token=TOKEN, numeric_type=float, precision='ns') 

    ticker_influx = TickerInflux(ADDR, org=ORG, bucket=BUCKET, token=TOKEN, numeric_type=float, precision='ns')
    
    
    
    f.add_feed(Binance(channels=[TRADES], pairs=['BTC-USDT', 'ETH-USDT'], callbacks={TRADES: trade_influx}))
    f.add_feed(Binance(channels=[L2_BOOK], pairs=['BTC-USDT'], callbacks={BOOK_DELTA: bookdelta_influx_btc}))
    f.add_feed(Binance(channels=[L2_BOOK], pairs=['ETH-USDT'], callbacks={BOOK_DELTA: bookdelta_influx_eth}))
    
    f.add_feed(Binance(channels=[TICKER], pairs=['BTC-USDT', 'ETH-USDT'], callbacks={TICKER: ticker_influx}))
    

    f.run()


if __name__ == '__main__':
    main()
```

**Comment by bmoscon** [comment]
it looks like the first exception was:

aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://us-west-2-1.aws.cloud2.influxdata.com/api/v2/write?org=myorg&bucket=coindb&precision=ns')

which caused all the reconnects.

**Comment by bmoscon** [comment]
@heartcored98 unless you have something else to add here I don't think this is a bug/issue with cryptofeed. If its gets a 400 back when the write is attempted, thats going to cause issues.

**Comment by heartcored98** [comment]
I think the 400 error is caused by high-rate orderbook delta write request with binance because I used demo code which does not adopt any batch writing. I think I should use cryptostore. 

Anyway, I also agree that this is not the cryptofeed issue!
