### ISSUE TITLE
OKEX FUTURES ticker channel KeyError: 'open_interest'

### ISSUE THREAD

**Issue by zhenpingfeng** [bmoscon/cryptofeed#198]
cryptofeed version: master branch
when i run demo_okex_futures.py, will got
```Timestamp: 1580643241.021 Feed: OKEX Pair: XRP-USD-200207 Bid: 0.253 Ask: 0.2532
2020-02-02 19:34:57,734 : ERROR : OKEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/zp/miniconda3/envs/zp/lib/python3.7/site-packages/cryptofeed-1.3.0-py3.7.egg/cryptofeed/feedhandler.py", line 197, in _connect
    await self._handler(websocket, feed.message_handler, feed.uuid)
  File "/Users/zp/miniconda3/envs/zp/lib/python3.7/site-packages/cryptofeed-1.3.0-py3.7.egg/cryptofeed/feedhandler.py", line 222, in _handler
    await handler(message, self.last_msg[feed_id])
  File "/Users/zp/miniconda3/envs/zp/lib/python3.7/site-packages/cryptofeed-1.3.0-py3.7.egg/cryptofeed/exchange/okcoin.py", line 136, in message_handler
    await self._ticker(msg)
  File "/Users/zp/miniconda3/envs/zp/lib/python3.7/site-packages/cryptofeed-1.3.0-py3.7.egg/cryptofeed/exchange/okcoin.py", line 69, in _ticker
    await self.callback(OPEN_INTEREST, feed=self.id, pair=pair, open_interest=oi, timestamp=timestamp)
  File "/Users/zp/miniconda3/envs/zp/lib/python3.7/site-packages/cryptofeed-1.3.0-py3.7.egg/cryptofeed/feed.py", line 103, in callback
    for cb in self.callbacks[data_type]:
KeyError: 'open_interest'
Timestamp: 1580643241.021 Feed: OKEX Pair: XRP-USD-200207 Bid: 0.253 Ask: 0.2532
2020-02-02 19:35:11,074 : ERROR : OKEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/zp/miniconda3/envs/zp/lib/python3.7/site-packages/cryptofeed-1.3.0-py3.7.egg/cryptofeed/feedhandler.py", line 197, in _connect
    await self._handler(websocket, feed.message_handler, feed.uuid)
  File "/Users/zp/miniconda3/envs/zp/lib/python3.7/site-packages/cryptofeed-1.3.0-py3.7.egg/cryptofeed/feedhandler.py", line 222, in _handler
    await handler(message, self.last_msg[feed_id])
  File "/Users/zp/miniconda3/envs/zp/lib/python3.7/site-packages/cryptofeed-1.3.0-py3.7.egg/cryptofeed/exchange/okcoin.py", line 136, in message_handler
    await self._ticker(msg)
  File "/Users/zp/miniconda3/envs/zp/lib/python3.7/site-packages/cryptofeed-1.3.0-py3.7.egg/cryptofeed/exchange/okcoin.py", line 69, in _ticker
    await self.callback(OPEN_INTEREST, feed=self.id, pair=pair, open_interest=oi, timestamp=timestamp)
  File "/Users/zp/miniconda3/envs/zp/lib/python3.7/site-packages/cryptofeed-1.3.0-py3.7.egg/cryptofeed/feed.py", line 103, in callback
    for cb in self.callbacks[data_type]:
KeyError: 'open_interest'
Timestamp: 1580643305.067 Feed: OKEX Pair: XRP-USD-200207 Bid: 0.2528 Ask: 0.253```

**Comment by zhenpingfeng** [comment]
https://github.com/bmoscon/cryptofeed/blob/a4ab7c6f7ec06ffea59f56ab1c8beff52a95eb4a/cryptofeed/exchange/okcoin.py#L64-L69

https://github.com/bmoscon/cryptofeed/blob/a4ab7c6f7ec06ffea59f56ab1c8beff52a95eb4a/cryptofeed/feed.py#L48-L54

It looks like the feed doesn't have the open_interest key.

**Comment by bmoscon** [comment]
yep. I have a fix for it already, but its part of a larger refactor. Should have it pushed later today

**Comment by bmoscon** [comment]
fixed
