### ISSUE TITLE
Json parse issue with Coinbene

### ISSUE THREAD

**Issue by joelrich** [bmoscon/cryptofeed#201]
Latest code from Github

Error:
```
2020-02-06 14:21:49,348 : ERROR : COINBENE: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/home/joel/Code/cryptostore/venv/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 169, in _rest_connect
    await feed.message_handler()
  File "/home/joel/Code/cryptostore/venv/lib/python3.7/site-packages/cryptofeed/exchange/coinbene.py", line 129, in message_handler
    await handle(session, pair, chan)
  File "/home/joel/Code/cryptostore/venv/lib/python3.7/site-packages/cryptofeed/exchange/coinbene.py", line 121, in handle
    await self._book(session, pair)
  File "/home/joel/Code/cryptostore/venv/lib/python3.7/site-packages/cryptofeed/exchange/coinbene.py", line 97, in _book
    data = await response.json()
  File "/home/joel/Code/cryptostore/venv/lib/python3.7/site-packages/aiohttp-4.0.0a1-py3.7-linux-x86_64.egg/aiohttp/client_reqrep.py", line 979, in json
    return loads(self._body.decode(encoding))  # type: ignore
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 15 (char 14)
```

With the following cryptostore config:
```
  COINBENE:
    l2_book:
      book_delta: true
      max_depth: 250
      symbols: &id011
      - ETH-USDT
      - BTC-USDT
    retries: 3
    ticker: *id011
    trades: *id011
```

The problematic string being:
`b'{"code":"429,"msg":"Please use V2,V1 is not maintained and will be offline soon. "}'`

Which is at least a little bit sad... (notice the " in front of 429)

**Comment by vdbelt** [comment]
Taking a quick glance at the V2 API, it seems to be of poor quality (only 50 most recent trades, no trade ids, 1s time granularity etc). At least for trades, it will make it difficult to not miss anything and to filter out duplicates.

Looking at the [books](https://www.coinbene.com/spot/exchange/BTC_USDT), it seems most volume is fake (printing mid book trades, equal volume levels, transaction mining and illiquid books). FTX [research report](https://ftx.com/volume-report-paper.pdf) indicates the same.

Wondering if it would be better to remove Coinbene from the list of supported exchanges.

Curious about your use case!

**Comment by joelrich** [comment]
I have just tested all exchanges. I don't use Coinbene, so I don't mind if it's getting removed.

**Comment by bmoscon** [comment]
@vdbelt I'm fine removing it, the data isnt that good, the main reason its there is to illustrate how a REST only exchange can be supported. I'll probably remove it from the list (i.e. readme) but leave the code in case someone wants to use it as an example
