### ISSUE TITLE
Key error with Bitmex L2 book data

### ISSUE THREAD

**Issue by twmeggs** [bmoscon/cryptofeed#202]
On latest code as delivered by `pip install --upgrade cryptofeed`

```
2020-02-06 06:29:15,653 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\crypto\lib\site-packages\cryptofeed\feedhandler.py", line 197, in _connect
    await self._handler(websocket, feed.message_handler, feed.uuid)
  File "C:\ProgramData\Anaconda3\envs\crypto\lib\site-packages\cryptofeed\feedhandler.py", line 222, in _handler
    await handler(message, self.last_msg[feed_id])
  File "C:\ProgramData\Anaconda3\envs\crypto\lib\site-packages\cryptofeed\exchange\bitmex.py", line 224, in message_handler
    await self._book(msg, timestamp)
  File "C:\ProgramData\Anaconda3\envs\crypto\lib\site-packages\cryptofeed\exchange\bitmex.py", line 151, in _book
    await self.book_callback(self.l2_book[pair], L2_BOOK, pair, forced, delta, timestamp)
  File "C:\ProgramData\Anaconda3\envs\crypto\lib\site-packages\cryptofeed\feed.py", line 82, in book_callback
    delta, book = await self.apply_depth(book, True, pair)
  File "C:\ProgramData\Anaconda3\envs\crypto\lib\site-packages\cryptofeed\feed.py", line 114, in apply_depth
    delta = book_delta(self.previous_book[pair], ret)
  File "C:\ProgramData\Anaconda3\envs\crypto\lib\site-packages\cryptofeed\util\book.py", line 36, in book_delta
    fkeys = set(list(former[side].keys()))
KeyError: 'bid'
```
Initially ran under cryptostore, which reconnected the number of times that I had specified and then ceased trying, which is the expected behaviour.  When running directly in cryptofeed, the above error is returned.

On cryptostore under:
```
BITMEX:
    retries: 5
    trades: [XBTUSD, XBTH20, XBTM20]
    l2_book:
        symbols: [XBTUSD, XBTH20, XBTM20]
        max_depth: 20
        book_delta: true
```

**Comment by vdbelt** [comment]
I think this was already fixed by @bmoscon in https://github.com/bmoscon/cryptofeed/commit/4c48ba43e905f4b6382990664f574c6d435635e5.

You could run the latest master version to verify, or wait for the next release.

**Comment by twmeggs** [comment]
Thanks @vdbelt 

@bmoscon apologies if a dupe.  I did search for issues (open and closed) that related to Bitmex and errors like this, but I missed `4c48ba4`.

**Comment by bmoscon** [comment]
yes, this has been fixed, but not release to pypi yet. Please use the version in github until release
