### ISSUE TITLE
bid/ask can be None => TypeError: conversion from NoneType to Decimal is not supported

### ISSUE THREAD

**Issue by joelrich** [bmoscon/cryptofeed#203]
Code:
```
        await self.callback(TICKER, feed=self.id,
                            pair=pair_exchange_to_std(msg['market']),
                            bid=Decimal(msg['data']['bid']),
                            ask=Decimal(msg['data']['ask']),
                            timestamp=float(msg['data']['time']))
```
Error:
```
2020-02-06 20:07:43,351 : ERROR : FTX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/home/joel/Code/cryptostore/venv/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 198, in _connect
    await self._handler(websocket, feed.message_handler, feed.uuid)
  File "/home/joel/Code/cryptostore/venv/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 223, in _handler
    await handler(message, self.last_msg[feed_id])
  File "/home/joel/Code/cryptostore/venv/lib/python3.7/site-packages/cryptofeed/exchange/ftx.py", line 125, in message_handler
    await self._ticker(msg)
  File "/home/joel/Code/cryptostore/venv/lib/python3.7/site-packages/cryptofeed/exchange/ftx.py", line 70, in _ticker
    bid=Decimal(msg['data']['bid']),
TypeError: conversion from NoneType to Decimal is not supported
```
This fails when bid/ask is None, which can be the case when an order book side is empty.
In this case, the message was (notice `'data': {'bid': None`):
```
{'channel': 'ticker', 'market': 'BSVDOOM/USD', 'type': 'update', 'data': {'bid': None, 'ask': Decimal('5E-8'), 'bidSize': None, 'askSize': Decimal('100000000.0'), 'last': Decimal('1E-8'), 'time': Decimal('1581016052.9065478')}}
```
I haven't tested it yet, but the same will likely also happen with Deribit options.

**Comment by joelrich** [comment]
Thanks. You were right regarding Deribit: `'best_bid_price': Decimal('0.0'), 'best_bid_amount': Decimal('0.0')`
