### ISSUE TITLE
Huobi & Huobi DM order book error if max_depth not specified 

### ISSUE THREAD

**Issue by joelrich** [bmoscon/cryptofeed#206]
Error:
```
2020-02-08 12:49:13,189 : ERROR : HUOBI: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/home/joel/Code/cryptostore/venv/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 198, in _connect
    await self._handler(websocket, feed.message_handler, feed.uuid)
  File "/home/joel/Code/cryptostore/venv/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 223, in _handler
    await handler(message, self.last_msg[feed_id])
  File "/home/joel/Code/cryptostore/venv/lib/python3.7/site-packages/cryptofeed/exchange/huobi.py", line 86, in message_handler
    await self._book(msg)
  File "/home/joel/Code/cryptostore/venv/lib/python3.7/site-packages/cryptofeed/exchange/huobi.py", line 49, in _book
    await self.book_callback(self.l2_book[pair], L2_BOOK, pair, forced, False, timestamp_normalize(self.id, msg['ts']))
  File "/home/joel/Code/cryptostore/venv/lib/python3.7/site-packages/cryptofeed/feed.py", line 86, in book_callback
    await self.callback(BOOK_DELTA, feed=self.id, pair=pair, delta=delta, timestamp=timestamp)
  File "/home/joel/Code/cryptostore/venv/lib/python3.7/site-packages/cryptofeed/feed.py", line 104, in callback
    await cb(**kwargs)
  File "/home/joel/Code/cryptostore/venv/lib/python3.7/site-packages/cryptofeed/backends/backend.py", line 24, in __call__
    book_delta_convert(delta, data, convert=self.numeric_type)
  File "/home/joel/Code/cryptostore/venv/lib/python3.7/site-packages/cryptofeed/backends/_util.py", line 12, in book_delta_convert
    for entry in delta[side]:
TypeError: 'bool' object is not subscriptable
```
Example configuration:
```
exchanges:
  HUOBI_DM:
    retries: 3
    trades: &id016
    - BTC_CW
    - BTC_NW
    - BTC_CQ
    - ETC_CW
    - ETC_NW
    - ETC_CQ
    - ETH_CW
    - ETH_NW
    - ETH_CQ
    - EOS_CW
    - EOS_NW
    - EOS_CQ
    - LTC_CW
    - LTC_NW
    l2_book:
      symbols: *id016
      book_delta: true
      book_interval: 864000
```
Works just fine when max_depth is added.

**Comment by bmoscon** [comment]
fixed. Huobi is the only exchange supported that doesn't do deltas, so have to manually calculate them

**Comment by joelrich** [comment]
I get now the following error:
```
2020-02-11 15:23:49,027 : ERROR : HUOBI: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/home/joel/Code/cryptostore/venv/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 198, in _connect
    await self._handler(websocket, feed.message_handler, feed.uuid)
  File "/home/joel/Code/cryptostore/venv/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 223, in _handler
    await handler(message, self.last_msg[feed_id])
  File "/home/joel/Code/cryptostore/venv/lib/python3.7/site-packages/cryptofeed/exchange/huobi.py", line 86, in message_handler
    await self._book(msg)
  File "/home/joel/Code/cryptostore/venv/lib/python3.7/site-packages/cryptofeed/exchange/huobi.py", line 49, in _book
    await self.book_callback(self.l2_book[pair], L2_BOOK, pair, forced, False, timestamp_normalize(self.id, msg['ts']))
  File "/home/joel/Code/cryptostore/venv/lib/python3.7/site-packages/cryptofeed/feed.py", line 90, in book_callback
    delta = book_delta(self.previous_book[pair], book, book_type=book_type)
  File "/home/joel/Code/cryptostore/venv/lib/python3.7/site-packages/cryptofeed/util/book.py", line 36, in book_delta
    fkeys = set(list(former[side].keys()))
KeyError: 'bid'
```
Which disappears when setting max_depth.

**Comment by bmoscon** [comment]
Are you using the latest version on github?

**Comment by joelrich** [comment]
Thank you!
