### ISSUE TITLE
Optional bid/ask (FTX) price leads to issue in backend

### ISSUE THREAD

**Issue by joelrich** [bmoscon/cryptofeed#207]
The fix https://github.com/bmoscon/cryptofeed/issues/203 for FTX leads to issues in the backend:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/cryptofeed/feedhandler.py", line 198, in _connect
    await self._handler(websocket, feed.message_handler, feed.uuid)
  File "/usr/local/lib/python3.6/dist-packages/cryptofeed/feedhandler.py", line 223, in _handler
    await handler(message, self.last_msg[feed_id])
  File "/usr/local/lib/python3.6/dist-packages/cryptofeed/exchange/ftx.py", line 124, in message_handler
    await self._ticker(msg)
  File "/usr/local/lib/python3.6/dist-packages/cryptofeed/exchange/ftx.py", line 71, in _ticker
    timestamp=float(msg['data']['time']))
  File "/usr/local/lib/python3.6/dist-packages/cryptofeed/feed.py", line 104, in callback
    await cb(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cryptofeed/backends/backend.py", line 53, in __call__
    data = {'feed': feed, 'pair': pair, 'bid': self.numeric_type(bid), 'ask': self.numeric_type(ask), 'timestamp': timestamp}
TypeError: float() argument must be a string or a number, not 'NoneType'
```

**Comment by bmoscon** [comment]
fixed
