### ISSUE TITLE
OKEX reconnect when order book entry to be deleted is misssing

### ISSUE THREAD

**Issue by joelrich** [bmoscon/cryptofeed#211]
I have seen this quite often and am wondering if it wouldn't be better to just stay connected in this case?

```
2020-02-16 10:03:21,625 : ERROR : OKEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/cryptofeed-BTkveWxE/lib/python3.8/site-packages/cryptofeed/feedhandler.py", line 198, in _connect
    await self._handler(websocket, feed.message_handler, feed.uuid)
  File "/root/.local/share/virtualenvs/cryptofeed-BTkveWxE/lib/python3.8/site-packages/cryptofeed/feedhandler.py", line 223, in _handler
    await handler(message, self.last_msg[feed_id])
  File "/root/.local/share/virtualenvs/cryptofeed-BTkveWxE/lib/python3.8/site-packages/cryptofeed/exchange/okcoin.py", line 140, in message_ha    await self._book(msg)
  File "/root/.local/share/virtualenvs/cryptofeed-BTkveWxE/lib/python3.8/site-packages/cryptofeed/exchange/okcoin.py", line 116, in _book
    del self.l2_book[pair][s][price]
  File "/root/.local/share/virtualenvs/cryptofeed-BTkveWxE/lib/python3.8/site-packages/sortedcontainers/sorteddict.py", line 259, in __delitem    self._dict_delitem(key)
KeyError: Decimal('69.53')
```

**Comment by bmoscon** [comment]
I'll change the feed to tick-by-tick instead of the depth it currently it. TBT is real time changes where as the normal depth feed is batched changes. Let's see if this helps the issue

**Comment by bmoscon** [comment]
I've pushed a change to handle the tick by tick data feed, let me know if this works better for you @joelrich

**Comment by joelrich** [comment]
I think OKEx is good now. However, I have noticed that other exchanges have the same problem, which makes me wonder if it would make sense to not throw an error if an entry to delete is missing. What do you think?

**Comment by bmoscon** [comment]
which exchanges @joelrich  ? Some specifically say in the docs to ignore deletes for nonexistent orders, so for those I definitely do.

**Comment by joelrich** [comment]
Bitfinex is by far the worst. Sometimes, it happens also for Kraken and Kraken Futures. Very rarely for Bitmex, FTX or Deribit (for these I could imagine that some messages went missing).

**Comment by bmoscon** [comment]
I updated the bitfinex code. Kraken already has (and has always had a guard) to check for this, so not sure what you're seeing. Would need to see a traceback. I believe this is fixed, so feel free to re-open or open new ticket if it persists. A traceback is definitely helpful as well.
