### ISSUE TITLE
Poloniex pair_mapping KeyError

### ISSUE THREAD

**Issue by joelrich** [bmoscon/cryptofeed#224]
I am seeing lots of errors like the following recently:

```
2020-03-25 11:01:00,287 : ERROR : POLONIEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/cryptofeed-BTkveWxE/lib/python3.8/site-packages/cryptofeed/feedhandler.py", line 202, in _connect
    await self._handler(websocket, feed.message_handler, feed.uuid)
  File "/root/.local/share/virtualenvs/cryptofeed-BTkveWxE/lib/python3.8/site-packages/cryptofeed/feedhandler.py", line 231, in _handler
    await handler(message, self.last_msg[feed_id])
  File "/root/.local/share/virtualenvs/cryptofeed-BTkveWxE/lib/python3.8/site-packages/cryptofeed/exchange/poloniex.py", line 169, in message_handler
    await self._ticker(msg[2], timestamp)
  File "/root/.local/share/virtualenvs/cryptofeed-BTkveWxE/lib/python3.8/site-packages/cryptofeed/exchange/poloniex.py", line 78, in _ticker
    pair = pair_exchange_to_std(self.pair_mapping[pair_id])
KeyError: 277
```
Always with 277 or 278. Do you have an idea what the problem could be?
Right now, it looks like the problem went away after restarting.

**Comment by bmoscon** [comment]
Those two trading pairs were newly listed on poloniex on march 24th:

https://m.poloniex.com/notices

So it started sending data that you couldnt process. I fixed this
