### ISSUE TITLE
bitmex reconnect errors

### ISSUE THREAD

**Issue by bmoscon** [bmoscon/cryptofeed#23]
```2018-05-14 10:13:03,065 : WARNING : Feed BITMEX encountered connection issue WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason - reconnecting...
2018-05-17 08:11:58,571 : WARNING : Feed BITMEX encountered connection issue WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason - reconnecting...
2018-05-17 16:55:50,276 : WARNING : Feed BITMEX encountered connection issue WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason - reconnecting...
2018-05-17 16:55:55,165 : ERROR : Task exception was never retrieved
future: <Task finished coro=<FeedHandler._connect() done, defined at /home/bryant/workspace/cryptofeed/cryptofeed/feedhandler.py:57> exception=KeyError(8799142950,)>
Traceback (most recent call last):
  File "/home/bryant/workspace/cryptofeed/cryptofeed/feedhandler.py", line 64, in _connect
    await self._handler(websocket, feed.message_handler)
  File "/home/bryant/workspace/cryptofeed/cryptofeed/feedhandler.py", line 74, in _handler
    await handler(message)
  File "/home/bryant/workspace/cryptofeed/cryptofeed/bitmex/bitmex.py", line 116, in message_handler
    await self._book(msg)
  File "/home/bryant/workspace/cryptofeed/cryptofeed/bitmex/bitmex.py", line 84, in _book
    price, _ = self.order_id[pair][data['id']]
KeyError: 8799142950
2018-05-17 16:55:55,169 : ERROR : Task exception was never retrieved
future: <Task finished coro=<FeedHandler._connect() done, defined at /home/bryant/workspace/cryptofeed/cryptofeed/feedhandler.py:57> exception=InvalidStatusCode('Status code not 101: 503',)>
Traceback (most recent call last):
  File "/home/bryant/workspace/cryptofeed/cryptofeed/feedhandler.py", line 62, in _connect
    async with websockets.connect(feed.address) as websocket:
  File "/home/bryant/anaconda3/envs/cryptofeed/lib/python3.6/site-packages/websockets-4.0.1-py3.6-linux-x86_64.egg/websockets/client.py", line 386, in __aenter__
    return (yield from self)
  File "/home/bryant/anaconda3/envs/cryptofeed/lib/python3.6/site-packages/websockets-4.0.1-py3.6-linux-x86_64.egg/websockets/client.py", line 400, in __await__
    extra_headers=protocol.extra_headers,
  File "/home/bryant/anaconda3/envs/cryptofeed/lib/python3.6/site-packages/websockets-4.0.1-py3.6-linux-x86_64.egg/websockets/client.py", line 263, in handshake
    raise InvalidStatusCode(status_code)
websockets.exceptions.InvalidStatusCode: Status code not 101: 503
```

**Comment by bmoscon** [comment]
fixed
