### ISSUE TITLE
KeyError: 'trades_swap' & KeyError: 'ticker_swap'

### ISSUE THREAD

**Issue by joelrich** [bmoscon/cryptofeed#238]
On the latest code. This did work before:

```
2020-04-16 11:14:25,258 : ERROR : OKEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/home/joel/.local/share/virtualenvs/cryptofeed2csv-gSWG8EAq/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 208, in _connect
    await self._handler(websocket, feed.message_handler, feed.uuid)
  File "/home/joel/.local/share/virtualenvs/cryptofeed2csv-gSWG8EAq/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 237, in _handler
    await handler(message, self.last_msg[feed_id])
  File "/home/joel/.local/share/virtualenvs/cryptofeed2csv-gSWG8EAq/lib/python3.7/site-packages/cryptofeed/exchange/okcoin.py", line 164, in message_handler
    await self._trade(msg, timestamp)
  File "/home/joel/.local/share/virtualenvs/cryptofeed2csv-gSWG8EAq/lib/python3.7/site-packages/cryptofeed/exchange/okcoin.py", line 101, in _trade
    receipt_timestamp=timestamp
  File "/home/joel/.local/share/virtualenvs/cryptofeed2csv-gSWG8EAq/lib/python3.7/site-packages/cryptofeed/feed.py", line 126, in callback
    for cb in self.callbacks[data_type]:
KeyError: 'trades_swap'
2020-04-16 11:14:27,695 : ERROR : OKEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/home/joel/.local/share/virtualenvs/cryptofeed2csv-gSWG8EAq/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 208, in _connect
    await self._handler(websocket, feed.message_handler, feed.uuid)
  File "/home/joel/.local/share/virtualenvs/cryptofeed2csv-gSWG8EAq/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 237, in _handler
    await handler(message, self.last_msg[feed_id])
  File "/home/joel/.local/share/virtualenvs/cryptofeed2csv-gSWG8EAq/lib/python3.7/site-packages/cryptofeed/exchange/okcoin.py", line 162, in message_handler
    await self._ticker(msg, timestamp)
  File "/home/joel/.local/share/virtualenvs/cryptofeed2csv-gSWG8EAq/lib/python3.7/site-packages/cryptofeed/exchange/okcoin.py", line 69, in _ticker
    receipt_timestamp=timestamp)
  File "/home/joel/.local/share/virtualenvs/cryptofeed2csv-gSWG8EAq/lib/python3.7/site-packages/cryptofeed/feed.py", line 126, in callback
    for cb in self.callbacks[data_type]:
KeyError: 'ticker_swap'
```

Code:
```python
                    fh = FeedHandler(retries=retries)
                    fh.add_feed(exchange, max_depth=max_depth, book_interval=book_interval, config=channel_pairs, callbacks=callbacks)
                    fh.run(start_loop=False)
```
With:
```
channel_pairs = {'trades_swap': ['BTC-USD-SWAP'], 'ticker_swap': ['BTC-USD-SWAP'], 'l2_book_swap': ['BTC-USD-SWAP'], 'funding': ['BTC-USD-SWAP'], 'open_interest': ['BTC-USD-SWAP']}
```

**Comment by joelrich** [comment]
@xiandong79 is this related to your change?

**Comment by xiandong79** [comment]
``` fh.add_feed(OKEx(pairs=['EOS-USD-SWAP'], channels=[TRADES_SWAP, L2_BOOK_SWAP, OPEN_INTEREST, FUNDING], callbacks={FUNDING: funding, OPEN_INTEREST: open_interest, TRADES: TradeCallback(trade), L2_BOOK: BookCallback(book)}))
```
should change to

```
fh.add_feed(OKEx(pairs=['EOS-USD-SWAP'], channels=[TRADES_SWAP, L2_BOOK_SWAP, OPEN_INTEREST, FUNDING], callbacks={FUNDING: funding, OPEN_INTEREST: open_interest, TRADES_SWAP: TradeCallback(trade), L2_BOOK_SWAP: BookCallback(book)}))
```

Will test it tonight.

**Comment by xiandong79** [comment]
For  OPEN_INTEREST, more dig is needed.

**Comment by xiandong79** [comment]
@joelrich for your error, I think you could change the key name in your `callbacks` variable.

**Comment by joelrich** [comment]
@xiandong79 In my opinion, the best solution would be to get rid of `*_SWAP` and `*_FUTURES` entirely since they are only used for OKEX even tough other exchanges (like for example FTX) also support all instrument types (spot, futures, swaps and even options). Then the symbol/pair itself would determine the type of the instrument. As far as I understand, the feed (TRADE, L2_BOOK, ...) is directly mapped to the exchange-specific channel, which is an issue in case for OKEX, since there you need different channels depending on the instrument type - which lead probably to `*_SWAP` and `*_FUTURES`  in the first place. Seems a leaky abstraction to me.

@bmoscon What is your take on this?

**Comment by xiandong79** [comment]
**`get rid of *_SWAP and *_FUTURES entirely` would be cool, and the system would be easier to use.**

However, 

in `/cryptofeed/standards.py` file, the channel has already be designed like below. 
so, L2_BOOK, L2_BOOK_SWAP, L2_BOOK_FUTURES are the different channels.

othervise,  a new design is needed, and it is hard to find a better design, IMO.

```
_feed_to_exchange_map = {
    L2_BOOK: {
         BITTREX: 'SubscribeToExchangeDeltas',
        BITCOINCOM: 'subscribeOrderbook',
        BITMAX: L2_BOOK,
        UPBIT: L2_BOOK
    },
    L3_BOOK: {
    },
   L2_BOOK_SWAP: {
        OKEX: 'swap/depth_l2_tbt'
    },
    TRADES_FUTURES: {
        OKEX: 'futures/trade'
    },
    L2_BOOK_FUTURES: {
        OKEX: 'futures/depth_l2_tbt'
    },
```

**Comment by joelrich** [comment]
@xiandong79, a relatively simple solution would be to support a different channel per instrument type (if needed):

```
L2_BOOK: {
        BITTREX: 'SubscribeToExchangeDeltas',
        ...
        OKEX: {
        	SPOT: ...,
        	FUTURE: 'futures/depth_l2_tbt',
        	SWAP: 'swap/depth_l2_tbt',
        	OPTION: ...,
        }
}
```

In combination with an exchange-specific `getInstrumentType(symbol)`-function. This function could either be implemented with pattern matching or by fetching information from the exchange (usually there is an exchange info or contract info API).

**Comment by bmoscon** [comment]
I'm trying to work out a good solution for removing the _swap and _futures channel types. Nothing has really clicked for me yet. I agree what is there currently is ugly, but no point in replacing ugly with ugly.

**Comment by xiandong79** [comment]
100% agree with @bmoscon

**Comment by joelrich** [comment]
@bmoscon What do you think about my proposal above? Unless you want to get rid of `_feed_to_exchange_map` entirely, I don't think there is a better solution. The `getInstrumentType` would only have to be implemented for exchanges like OKEX which have a dict instead of a single channel (as in my example).

**Comment by bmoscon** [comment]
@joelrich how do you know which key to access in the sub-dict? for most exchanges, you just look up the channel, eg L2_BOOK, and then the exchange, to get the mapping for the subscription. How do you know which one to use here, is it based on the symbol?

**Comment by joelrich** [comment]
Yes, I would do this based on the symbol. Example for OKEx:

```
BTC-USDT
BTC-USD-200626
BTC-USD-SWAP
BTC-USD-200501-7500-C
```

Which leads to the following regexes:

```
SPOT: [\w]+-[\w]+
FUTURE: [\w]+-[\d]{6}
SPOT: [\w]+-[\w]+-SWAP
OPTION: [\w]+-[\w]+-[\d]{6}-[\d]+-[CP]
```

To make sure that the regexes are correct, you can just fetch all instruments from the different instrument APIs (e.g. https://www.okex.com/api/futures/v3/instruments) and make sure that the only the correct pattern matches.

The alternative would be to fetch the instrument APIs for all supported instruments when the feed is started and check in which instrument API a certain symbol appears. I prefer the regex approach (less overhead).
