### ISSUE TITLE
KeyError: 'channel_timeouts'

### ISSUE THREAD

**Issue by yohplala** [bmoscon/cryptofeed#255]
Hi,
I installed Cryptostore along with Redis.

I used following configuration file:

```yaml
# Cache
cache: redis
redis:
    ip: '127.0.0.1'
    port: 6379
    socket: null
    del_after_read: true
    retention_time: null
    start_flush: true

# Data sources and data types
exchanges:
    BINANCE:
        channel_timeouts:
            l2_book: 30
            trades: 120
        retries: 10
        l2_book:
            symbols: [BTC-USDT, ETH-USDT, XRP-USDT]
            book_delta: true
            book_interval: 1440
        trades: [BTC-USDT, ETH-USDT, XRP-USDT]

# Storage
storage: [parquet]
parquet:
    file_format: [exchange, data_type, pair, timestamp]
    path: /home/me/Documents/code/cryptostore/data

storage_interval: 300

# Cryptostore Plugin Interface
plugins:
    backfill:
        module: [cryptostore.plugin.backfill, Backfill]
        config: config.yaml

backfill:
    BINANCE:
        BTC-USDT:
            start: '2017-01-01'
        ETH-USDT:
            start: '2017-01-01'
        XRP-USDT:
            start: '2017-01-01'
```

I get no data and following error message. Any idea what could be wrong?

```
020-06-25 22:31:39,044 : INFO : Starting cryptostore
2020-06-25 22:31:39,044 : INFO : Cryptostore running on PID 30738
2020-06-25 22:31:39,045 : INFO : Backfill running on PID 30749
2020-06-25 22:31:39,046 : INFO : Spawner started
2020-06-25 22:31:39,047 : INFO : Spawner running on PID 30751
2020-06-25 22:31:39,048 : INFO : Aggregator started
2020-06-25 22:31:39,049 : INFO : Aggregator running on PID 30752
2020-06-25 22:31:39,050 : INFO : Cryptostore started
2020-06-25 22:31:39,066 : INFO : start: ['BINANCE'] stop: []
2020-06-25 22:31:39,067 : INFO : message: {"op": "start", "exchange": "BINANCE", "collector": {"channel_timeouts": {"l2_book": 30, "trades": 120}, "retries": 10, "l2_book": {"symbols": ["BTC-USDT", "ETH-USDT", "XRP-USDT"], "book_delta": true, "book_interval": 1440}, "trades": ["BTC-USDT", "ETH-USDT", "XRP-USDT"]}, "config": {"cache": "redis", "kafka": {"ip": "127.0.0.1", "port": 9092, "start_flush": true}, "redis": {"ip": "127.0.0.1", "port": 6379, "socket": null, "del_after_read": true, "retention_time": null, "start_flush": true}, "storage": ["parquet"], "parquet": {"file_format": ["exchange", "data_type", "pair", "timestamp"], "path": "/home/pierre/Documents/code/cryptostore/data"}, "storage_interval": 300, "plugins": {"backfill": {"module": ["cryptostore.plugin.backfill", "Backfill"], "config": "config.yaml"}}, "backfill": {"BINANCE": {"BTC-USDT": {"start": "2017-01-01"}, "ETH-USDT": {"start": "2017-01-01"}, "XRP-USDT": {"start": "2017-01-01"}}}}}
2020-06-25 22:31:39,068 : INFO : Starting {'op': 'start', 'exchange': 'BINANCE', 'collector': {'channel_timeouts': {'l2_book': 30, 'trades': 120}, 'retries': 10, 'l2_book': {'symbols': ['BTC-USDT', 'ETH-USDT', 'XRP-USDT'], 'book_delta': True, 'book_interval': 1440}, 'trades': ['BTC-USDT', 'ETH-USDT', 'XRP-USDT']}, 'config': {'cache': 'redis', 'kafka': {'ip': '127.0.0.1', 'port': 9092, 'start_flush': True}, 'redis': {'ip': '127.0.0.1', 'port': 6379, 'socket': None, 'del_after_read': True, 'retention_time': None, 'start_flush': True}, 'storage': ['parquet'], 'parquet': {'file_format': ['exchange', 'data_type', 'pair', 'timestamp'], 'path': '/home/pierre/Documents/code/cryptostore/data'}, 'storage_interval': 300, 'plugins': {'backfill': {'module': ['cryptostore.plugin.backfill', 'Backfill'], 'config': 'config.yaml'}}, 'backfill': {'BINANCE': {'BTC-USDT': {'start': '2017-01-01'}, 'ETH-USDT': {'start': '2017-01-01'}, 'XRP-USDT': {'start': '2017-01-01'}}}}}
2020-06-25 22:31:39,071 : INFO : Collector for BINANCE running on PID 30754
2020-06-25 22:31:39,073 : INFO : Flushing cache
2020-06-25 22:31:39,109 : INFO : Reading BINANCE-channel_timeouts-l2_book
2020-06-25 22:31:39,110 : INFO : No data for BINANCE-channel_timeouts-l2_book
2020-06-25 22:31:39,110 : INFO : Reading BINANCE-channel_timeouts-trades
2020-06-25 22:31:39,110 : INFO : No data for BINANCE-channel_timeouts-trades
2020-06-25 22:31:39,110 : INFO : Reading BINANCE-l2_book-BTC-USDT
2020-06-25 22:31:39,110 : INFO : No data for BINANCE-l2_book-BTC-USDT
2020-06-25 22:31:39,110 : INFO : Reading BINANCE-l2_book-ETH-USDT
2020-06-25 22:31:39,111 : INFO : No data for BINANCE-l2_book-ETH-USDT
2020-06-25 22:31:39,111 : INFO : Reading BINANCE-l2_book-XRP-USDT
2020-06-25 22:31:39,111 : INFO : No data for BINANCE-l2_book-XRP-USDT
2020-06-25 22:31:39,111 : INFO : Reading BINANCE-trades-BTC-USDT
2020-06-25 22:31:39,112 : INFO : No data for BINANCE-trades-BTC-USDT
2020-06-25 22:31:39,112 : INFO : Reading BINANCE-trades-ETH-USDT
2020-06-25 22:31:39,112 : INFO : No data for BINANCE-trades-ETH-USDT
2020-06-25 22:31:39,112 : INFO : Reading BINANCE-trades-XRP-USDT
2020-06-25 22:31:39,112 : INFO : No data for BINANCE-trades-XRP-USDT
Process Collector-1:1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.7/dist-packages/cryptostore/collector.py", line 109, in run
    fh.add_feed(self.exchange, max_depth=depth, book_interval=window, config={callback_type: self.exchange_config[callback_type]}, callbacks=cb)
  File "/usr/local/lib/python3.7/dist-packages/cryptofeed/feedhandler.py", line 108, in add_feed
    self.feeds.append(_EXCHANGES[feed](**kwargs))
  File "/usr/local/lib/python3.7/dist-packages/cryptofeed/exchange/binance.py", line 27, in __init__
    super().__init__(None, pairs=pairs, channels=channels, callbacks=callbacks, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/cryptofeed/feed.py", line 42, in __init__
    chan = feed_to_exchange(self.id, channel)
  File "/usr/local/lib/python3.7/dist-packages/cryptofeed/standards.py", line 290, in feed_to_exchange
    ret = _feed_to_exchange_map[feed][exchange]
KeyError: 'channel_timeouts'
```

**Comment by bmoscon** [comment]
what version of cryptostore?

**Comment by yohplala** [comment]
Thanks for your reactivity Bryan.
I saw that there is no command to show cryptostore version.
I typed then pip3 install --upgrade cryptostore, and here is the output:
```
Requirement already up-to-date: cryptostore in /usr/local/lib/python3.7/dist-packages (0.2.1)
```

**Comment by bmoscon** [comment]
Can you update to the latest source in github and try again? It works for me with the code in github

**Comment by yohplala** [comment]
Hello Bryan,

First sorry for issuing the issue in the wrong repo. I was speaking about Cryptostore. Sorry for that.

Second, yes, you are right, this did the trick. I updated from git with following command:

`pip3 install git+git://github.com/bmoscon/cryptostore --upgrade`

And no more error related to this trouble!
Thanks a lot!
