### ISSUE TITLE
Demos & examples fail with import errors

### ISSUE THREAD

**Issue by UnitNote** [bmoscon/cryptofeed#370]
**Describe the bug**
Various import errors trying to run the demos / examples after the standard install

**To Reproduce**
```
$ python3 -m pip install --user --upgrade cryptofeed  
Requirement already satisfied: cryptofeed in /home/user/.local/lib/python3.6/sit
e-packages (1.4.1)
[... install lines omitted ...]

$ python3 examples/demo.py
Traceback (most recent call last):
  File "examples/demo.py", line 11, in <module>
    from cryptofeed.callback import BookCallback, FundingCallback, TickerCallback, TradeCallback, FuturesIndexCallback, OpenInterestCallback
ImportError: cannot import name 'FuturesIndexCallback'

$ python3
Python 3.6.9 (default, Oct  8 2020, 12:12:24)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cryptofeed.feedhandler import FeedHandler
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/cryptofeed/cryptofeed/__init__.py", line 7, in <module>
    from cryptofeed.feedhandler import FeedHandler
  File "/home/user/cryptofeed/cryptofeed/feedhandler.py", line 27, in <module>
    from cryptofeed.exchanges import *
  File "/home/user/cryptofeed/cryptofeed/exchanges.py", line 7, in <module>
    from cryptofeed.exchange.binance import Binance
  File "/home/user/cryptofeed/cryptofeed/exchange/binance.py", line 19, in <module>
    from cryptofeed.feed import Feed
  File "/home/user/cryptofeed/cryptofeed/feed.py", line 11, in <module>
    from cryptofeed.connection import AsyncConnection
  File "/home/user/cryptofeed/cryptofeed/connection.py", line 8, in <module>
    from contextlib import asynccontextmanager
ImportError: cannot import name 'asynccontextmanager'
```

**Expected behavior**
Expect demos & examples to work immediately when install procedure is followed as given

**Operating System:**
 - Ubuntu 18

**Cryptofeed Version**
1.4.1

**Comment by bmoscon** [comment]
cryptofeed requires 3.7+, you are using 3.6
