### ISSUE TITLE
Pipenv installation broken

### ISSUE THREAD

**Issue by UnitNote** [bmoscon/cryptofeed#371]
**Describe the bug**
When installing via `git clone` and `pipenv`, the user must also run `python3 -m pip install .`, running `python3 -m pipenv install` is not enough (with Python 3.7.5), but the INSTALL.md documention does not mention this.

The error appears to be that the pipenv install does not result in uvloop (or cryptofeed itself ) being installed.

**To Reproduce**
```
user@Ubuntu18:~/cryptofeed$ git log | head -n 1
commit 6eafd56b98a6a895d7485d46841e908992082e92

user@Ubuntu18:~/cryptofeed$ python3.7 -m pipenv install
Creating a virtualenv for this project...
Pipfile: /home/user/cryptofeed/Pipfile
Using /usr/bin/python3.7 (3.7.5) to create virtualenv...
⠇ Creating virtual environment...created virtual environment CPython3.7.5.final.0-64 in 433ms
  creator CPython3Posix(dest=/home/user/.local/share/virtualenvs/cryptofeed-XkEPfgbK, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/user/.local/share/virtualenv)
    added seed packages: pip==20.3.1, setuptools==51.0.0, wheel==0.36.1
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

✔ Successfully created virtual environment! 
Virtualenv location: /home/user/.local/share/virtualenvs/cryptofeed-XkEPfgbK
Installing dependencies from Pipfile.lock (ba6a78)...
Ignoring idna-ssl: markers 'python_version < "3.7"' don't match your environment
Ignoring typing: markers 'python_version < "3.7"' don't match your environment
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 64/64 — 00:00:54
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.

user@Ubuntu18:~/cryptofeed$ pipenv shell
Launching subshell in virtual environment...
user@Ubuntu18:~/cryptofeed$  . /home/user/.local/share/virtualenvs/cryptofeed-XkEPfgbK/bin/activate

(cryptofeed) user@Ubuntu18:~/cryptofeed$ python examples/demo.py 
Traceback (most recent call last):
  File "examples/demo.py", line 9, in <module>
    from cryptofeed.pairs import binance_pairs
ModuleNotFoundError: No module named 'cryptofeed'

(cryptofeed) user@Ubuntu18:~/cryptofeed$ python -m pip install .
[... log entries omitted ...]
Installing collected packages: uvloop, cryptofeed
Successfully installed cryptofeed-1.7.0 uvloop-0.14.0

(cryptofeed) user@Ubuntu18:~/cryptofeed$ python examples/demo.py                                                                              
Timestamp: 1.609108 Feed: BLOCKCHAIN Pair: BTC-USD Book Bid Size is 189 Ask Size is 113
Timestamp: 1.609108 Feed: BLOCKCHAIN Pair: ETH-USD Book Bid Size is 58 Ask Size is 28   
```

**Operating System:**
 - Ubuntu 18
 
**Cryptofeed Version**

**Comment by bmoscon** [comment]
fixed. i dont use pipenv, so it may or may not always be up to date.

**Comment by bmoscon** [comment]
@olibre if you think you can fix the pipenv, go for it, otherwise I'll just remove it, I'm not a pipenv user, and I'm not really willing to support it. I can't get it to work on my mac laptop either - i just get a ton of strange errors from it trying to build numpy

**Comment by bmoscon** [comment]
to be clear the issue is not that uvloop is not in the pipfile, the code will work without that dependency - after all windows doesnt support it at all

**Comment by olibre** [comment]
Hi @bmoscon I am having a look on this issue...

**Comment by bmoscon** [comment]
i can post my tracebacks if necessary

**Comment by olibre** [comment]
Hi @UnitNote 
In lieu of `python examples/demo.py` try to use:
```
PYTHONPATH=. python examples/demo.py
```

or:

```
export PYTHONPATH=/path/where/setup.py/of/cryptofeed/is/located 

python examples/demo.py
```

If you want to avoid having to set `PYTHONPATH`, you can use this command line:

```
rm Pipefile Pipefile.lock
python3 -m pip install -e cryptofeed
```

That creates a `Pipfile` similar to:
```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
cryptofeed = {editable = true, path = "."}
```

I am updating the INSTALL.md ...

@bmoscon I am wondering about your NumPy build errors when using Pipenv on macOS. 
1. How do you install the NumPy? (or Pandas) Do you use Pip?
2. What happen when you try `python3 -m pip install --user --upgrade numpy`?  
   (or `pandas` in lieu of `numpy`)

**Comment by olibre** [comment]
Hi @UnitNote 
Please let me know if the refreshed INSTALL.md fixes your issue:
https://github.com/olibre/cryptofeed/blob/update-install-and-setup.py/INSTALL.md
Merry xmas

**Comment by UnitNote** [comment]
On Sun, Dec 27, 2020 at 04:28:07PM -0800, Bryant Moscon wrote:
>@olibre if you think you can fix the pipenv, go for it, otherwise I'll just remove it, I'm not a pipenv user, and I'm not really willing to support it. I can't get it to work on my mac laptop either - i just get a ton of strange errors from it trying to build numpy

There needs to be *some* kind of documented way to build from a `git 
clone`, that's fairly basic... if the only documented way to use 
`cryptofeed` is with `pip install` then that makes it very hard to test 
recent changes to the codebase.

**Comment by UnitNote** [comment]
> Hi @UnitNote
> Please let me know if the refreshed INSTALL.md fixes your issue:
> https://github.com/olibre/cryptofeed/blob/update-install-and-setup.py/INSTALL.md
> Merry xmas

I tried and got a pipenv.patched.notpip._internal.exceptions.HashMismatch error during the install stage, but I assume that's a local issue and the extra PYTHONPATH variable is enough to resolve the issue under normal circumstances.

**Comment by UnitNote** [comment]
> Hi @UnitNote
> Please let me know if the refreshed INSTALL.md fixes your issue:
> https://github.com/olibre/cryptofeed/blob/update-install-and-setup.py/INSTALL.md
> Merry xmas

I tried and got a pipenv.patched.notpip._internal.exceptions.HashMismatch error during the install stage, but I assume that's a local issue and the extra PYTHONPATH variable is enough to resolve the issue under normal circumstances.

**Comment by bmoscon** [comment]
@UnitNote there are multiple ways to install python packages from source. two others are `python setup.py install` and `pip install -e .`

**Comment by bmoscon** [comment]
@olibre i use conda to create virtualenvs and i use pip or setuptools to install all dependencies. 

I've tried removing pandas from the pipfile, adding numpy to it, no avail. Still fails:

```
$ pipenv install
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Building requirements...
Resolving dependencies...
✔ Success!
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✘ Locking Failed!
ERROR:pip.subprocessor:Command errored out with exit status 1:
 command: /Users/bryant/.local/share/virtualenvs/cryptofeed-hUuwhlOc/bin/python /usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/patched/notpip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/_r/28vq05fx4mqf0fr5fcd0tg_40000gn/T/tmpak_vuxos
     cwd: /private/var/folders/_r/28vq05fx4mqf0fr5fcd0tg_40000gn/T/pip-resolver-2texe5tt/numpy
Complete output (209 lines):
Running from numpy source directory.
setup.py:480: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
  run_build = parse_setuppy_commands()
Cythonizing sources
Processing numpy/random/_bounded_integers.pxd.in
Processing numpy/random/_philox.pyx
Processing numpy/random/_bounded_integers.pyx.in
Processing numpy/random/_sfc64.pyx
Processing numpy/random/_mt19937.pyx
Processing numpy/random/bit_generator.pyx
Processing numpy/random/mtrand.pyx
Processing numpy/random/_generator.pyx
Processing numpy/random/_pcg64.pyx
Processing numpy/random/_common.pyx
blas_opt_info:
blas_mkl_info:
customize UnixCCompiler
  libraries mkl_rt not found in ['/Users/bryant/.local/share/virtualenvs/cryptofeed-hUuwhlOc/lib', '/usr/local/lib', '/usr/lib']
  NOT AVAILABLE

blis_info:
  libraries blis not found in ['/Users/bryant/.local/share/virtualenvs/cryptofeed-hUuwhlOc/lib', '/usr/local/lib', '/usr/lib']
  NOT AVAILABLE

openblas_info:
  libraries openblas not found in ['/Users/bryant/.local/share/virtualenvs/cryptofeed-hUuwhlOc/lib', '/usr/local/lib', '/usr/lib']
  NOT AVAILABLE

atlas_3_10_blas_threads_info:
Setting PTATLAS=ATLAS
  libraries tatlas not found in ['/Users/bryant/.local/share/virtualenvs/cryptofeed-hUuwhlOc/lib', '/usr/local/lib', '/usr/lib']
  NOT AVAILABLE

atlas_3_10_blas_info:
  libraries satlas not found in ['/Users/bryant/.local/share/virtualenvs/cryptofeed-hUuwhlOc/lib', '/usr/local/lib', '/usr/lib']
  NOT AVAILABLE

atlas_blas_threads_info:
Setting PTATLAS=ATLAS
  libraries ptf77blas,ptcblas,atlas not found in ['/Users/bryant/.local/share/virtualenvs/cryptofeed-hUuwhlOc/lib', '/usr/local/lib', '/usr/lib']
  NOT AVAILABLE

atlas_blas_info:
  libraries f77blas,cblas,atlas not found in ['/Users/bryant/.local/share/virtualenvs/cryptofeed-hUuwhlOc/lib', '/usr/local/lib', '/usr/lib']
  NOT AVAILABLE

accelerate_info:
  libraries accelerate not found in ['/Users/bryant/.local/share/virtualenvs/cryptofeed-hUuwhlOc/lib', '/usr/local/lib', '/usr/lib']
Library accelerate was not found. Ignoring
  libraries veclib not found in ['/Users/bryant/.local/share/virtualenvs/cryptofeed-hUuwhlOc/lib', '/usr/local/lib', '/usr/lib']
Library veclib was not found. Ignoring
  FOUND:
    extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
    define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]

  FOUND:
    extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
    define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]

non-existing path in 'numpy/distutils': 'site.cfg'
lapack_opt_info:
lapack_mkl_info:
  libraries mkl_rt not found in ['/Users/bryant/.local/share/virtualenvs/cryptofeed-hUuwhlOc/lib', '/usr/local/lib', '/usr/lib']
  NOT AVAILABLE

openblas_lapack_info:
  libraries openblas not found in ['/Users/bryant/.local/share/virtualenvs/cryptofeed-hUuwhlOc/lib', '/usr/local/lib', '/usr/lib']
  NOT AVAILABLE

openblas_clapack_info:
  libraries openblas,lapack not found in ['/Users/bryant/.local/share/virtualenvs/cryptofeed-hUuwhlOc/lib', '/usr/local/lib', '/usr/lib']
  NOT AVAILABLE

flame_info:
  libraries flame not found in ['/Users/bryant/.local/share/virtualenvs/cryptofeed-hUuwhlOc/lib', '/usr/local/lib', '/usr/lib']
  NOT AVAILABLE

atlas_3_10_threads_info:
Setting PTATLAS=ATLAS
  libraries lapack_atlas not found in /Users/bryant/.local/share/virtualenvs/cryptofeed-hUuwhlOc/lib
  libraries tatlas,tatlas not found in /Users/bryant/.local/share/virtualenvs/cryptofeed-hUuwhlOc/lib
  libraries lapack_atlas not found in /usr/local/lib
  libraries tatlas,tatlas not found in /usr/local/lib
  libraries lapack_atlas not found in /usr/lib
  libraries tatlas,tatlas not found in /usr/lib
<class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
  NOT AVAILABLE

atlas_3_10_info:
  libraries lapack_atlas not found in /Users/bryant/.local/share/virtualenvs/cryptofeed-hUuwhlOc/lib
  libraries satlas,satlas not found in /Users/bryant/.local/share/virtualenvs/cryptofeed-hUuwhlOc/lib
  libraries lapack_atlas not found in /usr/local/lib
  libraries satlas,satlas not found in /usr/local/lib
  libraries lapack_atlas not found in /usr/lib
  libraries satlas,satlas not found in /usr/lib
<class 'numpy.distutils.system_info.atlas_3_10_info'>
  NOT AVAILABLE

atlas_threads_info:
Setting PTATLAS=ATLAS
  libraries lapack_atlas not found in /Users/bryant/.local/share/virtualenvs/cryptofeed-hUuwhlOc/lib
  libraries ptf77blas,ptcblas,atlas not found in /Users/bryant/.local/share/virtualenvs/cryptofeed-hUuwhlOc/lib
  libraries lapack_atlas not found in /usr/local/lib
  libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
  libraries lapack_atlas not found in /usr/lib
  libraries ptf77blas,ptcblas,atlas not found in /usr/lib
<class 'numpy.distutils.system_info.atlas_threads_info'>
  NOT AVAILABLE

atlas_info:
  libraries lapack_atlas not found in /Users/bryant/.local/share/virtualenvs/cryptofeed-hUuwhlOc/lib
  libraries f77blas,cblas,atlas not found in /Users/bryant/.local/share/virtualenvs/cryptofeed-hUuwhlOc/lib
  libraries lapack_atlas not found in /usr/local/lib
  libraries f77blas,cblas,atlas not found in /usr/local/lib
  libraries lapack_atlas not found in /usr/lib
  libraries f77blas,cblas,atlas not found in /usr/lib
<class 'numpy.distutils.system_info.atlas_info'>
  NOT AVAILABLE

  FOUND:
    extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
    define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]

/usr/local/Cellar/python@3.9/3.9.1_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
  warnings.warn(msg)
running dist_info
running build_src
build_src
building py_modules sources
creating build
creating build/src.macosx-11-x86_64-3.9
creating build/src.macosx-11-x86_64-3.9/numpy
creating build/src.macosx-11-x86_64-3.9/numpy/distutils
building library "npymath" sources
Traceback (most recent call last):
  File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/patched/notpip/_vendor/pep517/_in_process.py", line 257, in <module>
    main()
  File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/patched/notpip/_vendor/pep517/_in_process.py", line 240, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/patched/notpip/_vendor/pep517/_in_process.py", line 110, in prepare_metadata_for_build_wheel
    return hook(metadata_directory, config_settings)
  File "/private/var/folders/_r/28vq05fx4mqf0fr5fcd0tg_40000gn/T/pip-build-env-fnb47mtb/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 157, in prepare_metadata_for_build_wheel
    self.run_setup()
  File "/private/var/folders/_r/28vq05fx4mqf0fr5fcd0tg_40000gn/T/pip-build-env-fnb47mtb/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 248, in run_setup
    super(_BuildMetaLegacyBackend,
  File "/private/var/folders/_r/28vq05fx4mqf0fr5fcd0tg_40000gn/T/pip-build-env-fnb47mtb/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 142, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 508, in <module>
    setup_package()
  File "setup.py", line 500, in setup_package
    setup(**metadata)
  File "/private/var/folders/_r/28vq05fx4mqf0fr5fcd0tg_40000gn/T/pip-resolver-2texe5tt/numpy/numpy/distutils/core.py", line 169, in setup
    return old_setup(**new_attr)
  File "/private/var/folders/_r/28vq05fx4mqf0fr5fcd0tg_40000gn/T/pip-build-env-fnb47mtb/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/Cellar/python@3.9/3.9.1_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python@3.9/3.9.1_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python@3.9/3.9.1_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/private/var/folders/_r/28vq05fx4mqf0fr5fcd0tg_40000gn/T/pip-build-env-fnb47mtb/overlay/lib/python3.9/site-packages/setuptools/command/dist_info.py", line 31, in run
    egg_info.run()
  File "/private/var/folders/_r/28vq05fx4mqf0fr5fcd0tg_40000gn/T/pip-resolver-2texe5tt/numpy/numpy/distutils/command/egg_info.py", line 24, in run
    self.run_command("build_src")
  File "/usr/local/Cellar/python@3.9/3.9.1_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/Cellar/python@3.9/3.9.1_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/private/var/folders/_r/28vq05fx4mqf0fr5fcd0tg_40000gn/T/pip-resolver-2texe5tt/numpy/numpy/distutils/command/build_src.py", line 144, in run
    self.build_sources()
  File "/private/var/folders/_r/28vq05fx4mqf0fr5fcd0tg_40000gn/T/pip-resolver-2texe5tt/numpy/numpy/distutils/command/build_src.py", line 155, in build_sources
    self.build_library_sources(*libname_info)
  File "/private/var/folders/_r/28vq05fx4mqf0fr5fcd0tg_40000gn/T/pip-resolver-2texe5tt/numpy/numpy/distutils/command/build_src.py", line 288, in build_library_sources
    sources = self.generate_sources(sources, (lib_name, build_info))
  File "/private/var/folders/_r/28vq05fx4mqf0fr5fcd0tg_40000gn/T/pip-resolver-2texe5tt/numpy/numpy/distutils/command/build_src.py", line 378, in generate_sources
    source = func(extension, build_dir)
  File "numpy/core/setup.py", line 658, in get_mathlib_info
    st = config_cmd.try_link('int main(void) { return 0;}')
  File "/usr/local/Cellar/python@3.9/3.9.1_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/config.py", line 241, in try_link
    self._check_compiler()
  File "/private/var/folders/_r/28vq05fx4mqf0fr5fcd0tg_40000gn/T/pip-resolver-2texe5tt/numpy/numpy/distutils/command/config.py", line 80, in _check_compiler
    self.fcompiler = new_fcompiler(compiler=self.fcompiler,
  File "/private/var/folders/_r/28vq05fx4mqf0fr5fcd0tg_40000gn/T/pip-resolver-2texe5tt/numpy/numpy/distutils/fcompiler/__init__.py", line 880, in new_fcompiler
    compiler = get_default_fcompiler(plat, requiref90=requiref90,
  File "/private/var/folders/_r/28vq05fx4mqf0fr5fcd0tg_40000gn/T/pip-resolver-2texe5tt/numpy/numpy/distutils/fcompiler/__init__.py", line 851, in get_default_fcompiler
    compiler_type =  _find_existing_fcompiler(matching_compiler_types,
  File "/private/var/folders/_r/28vq05fx4mqf0fr5fcd0tg_40000gn/T/pip-resolver-2texe5tt/numpy/numpy/distutils/fcompiler/__init__.py", line 802, in _find_existing_fcompiler
    c.customize(dist)
  File "/private/var/folders/_r/28vq05fx4mqf0fr5fcd0tg_40000gn/T/pip-resolver-2texe5tt/numpy/numpy/distutils/fcompiler/__init__.py", line 526, in customize
    linker_so_flags = self.flag_vars.linker_so
  File "/private/var/folders/_r/28vq05fx4mqf0fr5fcd0tg_40000gn/T/pip-resolver-2texe5tt/numpy/numpy/distutils/fcompiler/environment.py", line 37, in __getattr__
    return self._get_var(name, conf_desc)
  File "/private/var/folders/_r/28vq05fx4mqf0fr5fcd0tg_40000gn/T/pip-resolver-2texe5tt/numpy/numpy/distutils/fcompiler/environment.py", line 53, in _get_var
    var = self._hook_handler(name, hook)
  File "/private/var/folders/_r/28vq05fx4mqf0fr5fcd0tg_40000gn/T/pip-resolver-2texe5tt/numpy/numpy/distutils/fcompiler/__init__.py", line 705, in _environment_hook
    return hook()
  File "/private/var/folders/_r/28vq05fx4mqf0fr5fcd0tg_40000gn/T/pip-resolver-2texe5tt/numpy/numpy/distutils/fcompiler/gnu.py", line 346, in get_flags_linker_so
    flags = GnuFCompiler.get_flags_linker_so(self)
  File "/private/var/folders/_r/28vq05fx4mqf0fr5fcd0tg_40000gn/T/pip-resolver-2texe5tt/numpy/numpy/distutils/fcompiler/gnu.py", line 136, in get_flags_linker_so
    os.environ['MACOSX_DEPLOYMENT_TARGET'] = target
  File "/usr/local/Cellar/python@3.9/3.9.1_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 684, in __setitem__
    value = self.encodevalue(value)
  File "/usr/local/Cellar/python@3.9/3.9.1_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 756, in encode
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not int
----------------------------------------
Traceback (most recent call last):
  File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/resolver.py", line 764, in <module>
    main()
  File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/resolver.py", line 758, in main
    _main(parsed.pre, parsed.clear, parsed.verbose, parsed.system, parsed.write,
  File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/resolver.py", line 741, in _main
    resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev)
  File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/resolver.py", line 702, in resolve_packages
    results, resolver = resolve(
  File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/resolver.py", line 684, in resolve
    return resolve_deps(
  File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/utils.py", line 1395, in resolve_deps
    results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
  File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/utils.py", line 1108, in actually_resolve_deps
    resolver.resolve()
  File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/utils.py", line 823, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/patched/piptools/resolver.py", line 180, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/patched/piptools/resolver.py", line 268, in _resolve_one_round
    their_constraints.extend(self._iter_dependencies(best_match))
  File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/patched/piptools/resolver.py", line 383, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 229, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 350, in get_legacy_dependencies
    results, ireq = self.resolve_reqs(
  File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 306, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/patched/notpip/_internal/legacy_resolve.py", line 339, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/patched/notpip/_internal/legacy_resolve.py", line 287, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 508, in prepare_linked_requirement
    abstract_dist = _get_prepared_distribution(
  File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 95, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/patched/notpip/_internal/distributions/sdist.py", line 40, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/patched/notpip/_internal/req/req_install.py", line 564, in prepare_metadata
    self.metadata_directory = self._generate_metadata()
  File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/patched/notpip/_internal/req/req_install.py", line 549, in _generate_metadata
    return generate_metadata(
  File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/patched/notpip/_internal/operations/build/metadata.py", line 36, in generate_metadata
    distinfo_dir = backend.prepare_metadata_for_build_wheel(
  File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/patched/notpip/_vendor/pep517/wrappers.py", line 167, in prepare_metadata_for_build_wheel
    return self._call_hook('prepare_metadata_for_build_wheel', {
  File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/patched/notpip/_vendor/pep517/wrappers.py", line 245, in _call_hook
    self._subprocess_runner(
  File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/patched/notpip/_internal/utils/subprocess.py", line 271, in runner
    call_subprocess(
  File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/patched/notpip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pipenv.patched.notpip._internal.exceptions.InstallationError: Command errored out with exit status 1: /Users/bryant/.local/share/virtualenvs/cryptofeed-hUuwhlOc/bin/python /usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/patched/notpip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/_r/28vq05fx4mqf0fr5fcd0tg_40000gn/T/tmpak_vuxos Check the logs for full command output.
```

if i install with pip, it just downloads and installs the wheel, as expected. With pipenv it tries to build the source. No idea.

**Comment by UnitNote** [comment]
> Hi @UnitNote
> Please let me know if the refreshed INSTALL.md fixes your issue:
> https://github.com/olibre/cryptofeed/blob/update-install-and-setup.py/INSTALL.md
> Merry xmas

Fixed the hash error, but running it fails:
```
$ PYTHONPATH=. python3 -m pipenv run python3 examples/demo.py
Traceback (most recent call last):
  File "examples/demo.py", line 103, in <module>
    main()
  File "examples/demo.py", line 67, in main
    f.add_feed(COINBASE, pairs=['BTC-USD'], channels=[TICKER], callbacks={TICKER: TickerCallback(ticker)})
  File "/home/user/cryptofeed/cryptofeed/feedhandler.py", line 148, in add_feed
    self.feeds.append((_EXCHANGES[feed](**kwargs), timeout))
  File "/home/user/cryptofeed/cryptofeed/exchange/coinbase.py", line 28, in __init__
    super().__init__('wss://ws-feed.pro.coinbase.com', pairs=pairs, channels=channels, callbacks=callbacks, **kwargs)
  File "/home/user/cryptofeed/cryptofeed/feed.py", line 57, in __init__
    load_exchange_pair_mapping(self.id, key_id=key_id)
  File "/home/user/cryptofeed/cryptofeed/standards.py", line 35, in load_exchange_pair_mapping
    mapping = gen_pairs(exchange, key_id=key_id)
  File "/home/user/cryptofeed/cryptofeed/pairs.py", line 35, in gen_pairs
    pairs = _exchange_function_map[exchange](key_id) if key_id else _exchange_function_map[exchange]()
  File "/home/user/cryptofeed/cryptofeed/pairs.py", line 143, in coinbase_pairs
    r = requests.get('https://api.pro.coinbase.com/products').json()
  File "/home/user/.local/share/virtualenvs/cryptofeed-XkEPfgbK/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by bmoscon** [comment]
that appears to be an error decoding the response from the exchange. I just tried the demo locally, and saw no error. could you try again? not sure if coinbase was having maintenance or not.

**Comment by olibre** [comment]
Hi @bmoscon 
I have checked the Pipenv output and I do not understand why it does not downloads the package in the same way as Pip!
Anyway, I have seen you are using Python-3.9 => you may add Python-3.9 in the supported versions in `setup.py`.

Hi @UnitNote 
As @bmoscon has noticed, your Pipenv/Cryptofeed is OK. The Cryptofeed stopped because of an invalid JSON response from Coinbase. If this issue occurs again, please verify the endpoint using cURL:
```
curl https://api.pro.coinbase.com/products
```

**Comment by bmoscon** [comment]
@olibre 3.9 is in the supported versions already
