### ISSUE TITLE
NBBO demo fails

### ISSUE THREAD

**Issue by UnitNote** [bmoscon/cryptofeed#372]
**To Reproduce**
```
(cryptofeed) user@Ubuntu18:~/cryptofeed$ python
Python 3.7.5 (default, Nov  7 2019, 10:50:52)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cryptofeed.feedhandler import FeedHandler
>>> from cryptofeed.exchanges import Coinbase, Bitfinex, HitBTC
>>>
>>>
>>> def nbbo_ticker(pair, bid, ask, bid_feed, ask_feed):
...     print('Pair: {} Bid: {} Bid Feed: {} Ask: {} Ask Feed: {}'.format(pair,
...                                                                       bid,
...                                                                       bid_feed,
...                                                                       ask,
...                                                                       ask_feed))
...
>>>
>>> fh = FeedHandler()
>>> fh.add_nbbo([Coinbase, Bitfinex, HitBTC], ['BTC-USD'], nbbo_ticker)
>>> fh.run()
2020-12-27 22:26:30,448 : ERROR : HITBTC-3a6c7a: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/home/user/cryptofeed/cryptofeed/feedhandler.py", line 242, in _connect
    await self._handler(connection, handler)
  File "/home/user/cryptofeed/cryptofeed/feedhandler.py", line 271, in _handler
    await handler(message, connection, self.last_msg[connection.uuid])
  File "/home/user/cryptofeed/cryptofeed/exchange/hitbtc.py", line 99, in message_handler
    await self._snapshot(msg['params'], timestamp)
  File "/home/user/cryptofeed/cryptofeed/exchange/hitbtc.py", line 65, in _snapshot
    await self.book_callback(self.l2_book[pair], L2_BOOK, pair, True, None, timestamp, timestamp)
  File "/home/user/cryptofeed/cryptofeed/feed.py", line 190, in book_callback
    await self.callback(L2_BOOK, feed=self.id, pair=pair, book=book, timestamp=timestamp, receipt_timestamp=receipt_timestamp)
  File "/home/user/cryptofeed/cryptofeed/feed.py", line 204, in callback
    await cb(**kwargs)
  File "/home/user/cryptofeed/cryptofeed/nbbo.py", line 51, in __call__
    await loop.run_in_executor(None, self.callback, pair, bid['price'], bid['size'], ask['price'], ask['size'], bid_feed, ask_feed)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
TypeError: nbbo_ticker() takes 5 positional arguments but 7 were given
```

**Comment by bmoscon** [comment]
the code in examples/demo_nbbo.py works. I've updated the readme to mirror that
