### ISSUE TITLE
Binance OI feed crashes and does not recover

### ISSUE THREAD

**Issue by Quenos** [bmoscon/cryptofeed#404]
When a feed crashes it seems as if the exception is not caught and successively the feed stops and is not recovered.
I notice this primarily on the Binance Futures OI feed. That the feed crashes is most likely because of Binance Futures and not cryptofeed perse.

Would be great if this could be somehow fix, or worked around.

I've tried to fix it myself, but am not able to do so. So some help would be great.

`Task exception was never retrieved
future: <Task finished name='Task-6' coro=<Binance._open_interest() done, defined at .../projects/binanceOB/lib/python3.8/site-packages/cryptofeed/exchange/binance.py:234> exception=ClientOSError(104, 'Connection reset by peer')>
Traceback (most recent call last):
  File ".../projects/binanceOB/lib/python3.8/site-packages/cryptofeed/exchange/binance.py", line 248, in _open_interest
    async with session.get(end_point) as response:
  File ".../projects/binanceOB/lib/python3.8/site-packages/aiohttp/client.py", line 1124, in __aenter__
    self._resp = await self._coro
  File ".../projects/binanceOB/lib/python3.8/site-packages/aiohttp/client.py", line 551, in _request
    await resp.start(conn)
  File ".../projects/binanceOB/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 890, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File ".../projects/binanceOB/lib/python3.8/site-packages/aiohttp/streams.py", line 605, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer
Task exception was never retrieved
future: <Task finished name='Task-6' coro=<Binance._open_interest() done, defined at .../projects/binanceOB/lib/python3.8/site-packages/cryptofeed/exchange/binance.py:234> exception=ClientOSError(104, 'Connection reset by peer')>
Traceback (most recent call last):
  File ".../projects/binanceOB/lib/python3.8/site-packages/cryptofeed/exchange/binance.py", line 248, in _open_interest
    async with session.get(end_point) as response:
  File ".../projects/binanceOB/lib/python3.8/site-packages/aiohttp/client.py", line 1124, in __aenter__
    self._resp = await self._coro
  File ".../projects/binanceOB/lib/python3.8/site-packages/aiohttp/client.py", line 551, in _request
    await resp.start(conn)
  File ".../projects/binanceOB/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 890, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File ".../projects/binanceOB/lib/python3.8/site-packages/aiohttp/streams.py", line 605, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
`

**Comment by bmoscon** [comment]
Binance does not support open interest, binance futures does. I'm not sure how you configured it, but when I try to I get the correct error:

cryptofeed.exceptions.UnsupportedDataFeed: open_interest is not currently supported on BINANCE

**Comment by Quenos** [comment]
Sorry for not being clear on this one. But I meant Binance Futures obviously.
So after a while (can take a couple of days) I get this error.

**Comment by bmoscon** [comment]
ok - thanks for clarifying, I'll take a look

**Comment by bmoscon** [comment]
ok, this will be fixed once the binance code is migrated to the new connection abstraction. Currently it just creates a task for the rest endpoints, but nothing is there to restart them.

**Comment by OnlyC** [comment]
I'm getting the same issue.

**Comment by bmoscon** [comment]
fixed
