### ISSUE TITLE
gcppubsub

### ISSUE THREAD

**Issue by bonald** [bmoscon/cryptofeed#433]
Can't get demo_gcppubsub.py working , any idea?

`python3.7 examples/demo_gcppubsub.py
examples/demo_gcppubsub.py:66: RuntimeWarning: coroutine 'SubscriberClient.create_subscription' was never awaited
  client.create_subscription(subscription_path, topic_path)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "examples/demo_gcppubsub.py", line 96, in <module>
    main()
  File "examples/demo_gcppubsub.py", line 92, in main
    start_subscriber(loop, trades.topic)
  File "examples/demo_gcppubsub.py", line 71, in start_subscriber
    keep_alive = client.subscribe(subscription_path, message_callback)
AttributeError: 'SubscriberClient' object has no attribute 'subscribe'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fd6b1437450>`

**Comment by bmoscon** [comment]
ask the person who added it. I can remove it if no one can fix it, its not something i want to support

**Comment by bonald** [comment]
@globophobe could you help me with this?

**Comment by bmoscon** [comment]
my guess is the sdk changed, so the latest version of the library probably has a breaking change

**Comment by globophobe** [comment]
yes, I can fix. gcloud-aio has breaking changes
