### ISSUE TITLE
Small bug and suggested fix in demo_binance_delivery.py

### ISSUE THREAD

**Issue by idclevxx** [bmoscon/cryptofeed#443]
**Describe the bug**
Line 20: max depth can't be 3, should be e.g. 5

**Comment by bmoscon** [comment]
@idclevxx why cant max depth be 3? This code works from latest in master

**Comment by bmoscon** [comment]
@idclevxx im going to close this. The demo file works in master. There was a bug in an older version, but it has been fixed. You can use a max depth of 3. It will use 5 when communicating with the exchange as the depth and truncate down to 3.

**Comment by idclevxx** [comment]
Sorry mate, was AFK for a bit. When I run the demo code without adjustments on max depth 3, I periodically (i.e. sometimes it prints what it should, sometimes not) get the error:

`
2021-04-01 14:28:47,121 : ERROR : BINANCE_DELIVERY-736064: encountered an exception, reconnecting
Traceback (most recent call last):
  File ".venv/lib/python3.8/site-packages/cryptofeed/feedhandler.py", line 322, in _connect
    await self._handler(connection, handler)
  File ".venv/lib/python3.8/site-packages/cryptofeed/feedhandler.py", line 365, in _handler
    await handler(message, connection, self.last_msg[connection.uuid])
  File ".venv/lib/python3.8/site-packages/cryptofeed/exchange/binance_delivery.py", line 75, in message_handler
    await self._book(msg, pair, timestamp)
  File ".venv/lib/python3.8/site-packages/cryptofeed/exchange/binance.py", line 231, in _book
    await self._snapshot(exchange_pair)
  File ".venv/lib/python3.8/site-packages/cryptofeed/exchange/binance.py", line 175, in _snapshot
    response.raise_for_status()
  File ".venv/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1000, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://dapi.binance.com/dapi/v1/depth?symbol=BNBUSD_210924&limit=3')
`

This periodic error does not occur when max depth is set to 5.

**Comment by bmoscon** [comment]
@idclevxx what version are you using?

**Comment by idclevxx** [comment]
> @idclevxx what version are you using?

1.7, but I know see there's a newer version; after upgrade the issue is gone. Perfect!
