### ISSUE TITLE
Redis DataError due to 'order_type' set to None

### ISSUE THREAD

**Issue by agijsberts** [bmoscon/cryptofeed#465]
**Describe the bug**
The `redis.TradeStream` handler raises an error because the `order_type` is set to **None** for the majority of exchanges. An empty `order_type` used to be filtered out in its parent `BackendTradeCallback`, but this filtering was removed recently in https://github.com/bmoscon/cryptofeed/commit/3a5339dad7d44ed16de3ea5f02c924246d3ba276.

**To Reproduce**
The minimal example
```python
from cryptofeed import FeedHandler
from cryptofeed.backends.redis import TradeStream
from cryptofeed.defines import TRADES
from cryptofeed.exchanges import Bitmex

f = FeedHandler()
f.add_feed(Bitmex(channels=[TRADES], symbols=['BTC-USD'], callbacks={TRADES: TradeStream()}))
f.run()
```
results in 
```
future: <Task finished coro=<RedisStreamCallback.writer() done, defined at /home/user/venv/cryptostore/lib/python3.7/site-packages/cryptofeed/backends/redis.py:55> exception=DataError("Invalid input of type: 'NoneType'. Convert to a bytes, string, int or float first.")>
Traceback (most recent call last):
  File "/home/user/venv/cryptostore/lib/python3.7/site-packages/cryptofeed/backends/redis.py", line 67, in writer
    await self.redis.xadd(f"{self.key}-{update['feed']}-{update['symbol']}", update['data'])
  File "/home/user/venv/cryptostore/lib/python3.7/site-packages/aioredis/client.py", line 1036, in execute_command
    await conn.send_command(*args)
  File "/home/user/venv/cryptostore/lib/python3.7/site-packages/aioredis/connection.py", line 835, in send_command
    self.pack_command(*args), check_health=kwargs.get("check_health", True)
  File "/home/user/venv/cryptostore/lib/python3.7/site-packages/aioredis/connection.py", line 879, in pack_command
    for arg in map(self.encoder.encode, args):
  File "/home/user/venv/cryptostore/lib/python3.7/site-packages/aioredis/connection.py", line 123, in encode
    f"Invalid input of type: {typename!r}. "
aioredis.exceptions.DataError: Invalid input of type: 'NoneType'. Convert to a bytes, string, int or float first.
```

**Operating System:**
Linux

**Cryptofeed Version**
Install from source, commit https://github.com/bmoscon/cryptofeed/commit/41b07e76ae773d50eb537cfbaf157b7d7137bcfa

**Comment by bmoscon** [comment]
fixed. Interestingly this doesnt affect the zset callbacks (because they are json dumped)
