### ISSUE TITLE
Running last cryptofeed with last cryptostore causes AttributeError with 'aioredis'

### ISSUE THREAD

**Issue by yohplala** [bmoscon/cryptofeed#485]
**Describe the bug**
Running cryptofeed through cryptostore and redis causes following error:
```python
Process Collector-1:1:
Traceback (most recent call last):
  File "/home/pierre/anaconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/pierre/anaconda3/lib/python3.8/site-packages/cryptostore-0.4.0-py3.8.egg/cryptostore/collector.py", line 80, in run
    cb[TRADES] = [trade_cb(**kwargs)]
  File "/home/pierre/anaconda3/lib/python3.8/site-packages/cryptofeed-1.9.1-py3.8.egg/cryptofeed/backends/redis.py", line 33, in __init__
    self.redis = aioredis.from_url(f"{prefix}{host}:{port}")
AttributeError: module 'aioredis' has no attribute 'from_url'
```

**To Reproduce**
Running last cryptostore version with last cryptofeed version and following config file.

```yaml
cache: redis

redis:
    ip: '127.0.0.1'
    port: 6379
    socket: null
    del_after_read: true
    retention_time: null
    start_flush: true

exchanges:
    BINANCE:
        retries: 4
        trades: [BTC-USDT, ETH-USDT]
        l2_book:
            symbols: [BTC-USDT, ETH-USDT]
            book_delta: true

storage: [parquet]

parquet:
    append_counter: 2
    file_format: [exchange, symbol, data_type, timestamp]
    compression:
        codec: 'BROTLI'
        level: 6
    path: '/home/pierre/Documents/code/data/cs'
    prefix_date: false

storage_interval: 5
storage_retries: 5
storage_retry_wait: 30
```

**Operating System:**
 - Ubuntu 20.04

**Cryptofeed Version**
- Last development versions from Github, installed with `python3 setup.py install develop`

**Comment by bmoscon** [comment]
@yohplala you need to upgrade to the version of aioredis listed in the requirements.
