### ISSUE TITLE
RuntimeError when restarting Bybit connections 

### ISSUE THREAD

**Issue by agijsberts** [bmoscon/cryptofeed#491]
**Describe the bug**
When a Bybit connection is restarted, it causes a `RuntimeError: dictionary changed size during iteration`.

**To Reproduce**
The situation can be reproduced with the following example:
```python
import asyncio

from cryptofeed.callback import BookCallback
from cryptofeed.defines import BID, ASK, L2_BOOK
from cryptofeed.exchanges import Bybit

async def book(feed, symbol, book, timestamp, receipt_timestamp):
    pass

async def restarter(feed, loop):
    while True:
        print('starting feed')
        feed.start(loop)
        await asyncio.sleep(5.)
        print('stopping feed')
        feed.stop()


loop = asyncio.get_event_loop()
feed = Bybit(symbols=['BTC-USDT'], channels=[L2_BOOK], callbacks={L2_BOOK: BookCallback(book)})
loop.create_task(restarter(feed, loop))
loop.run_forever()
```
This will produce the output:
```
starting feed
stopping feed
starting feed
BYBIT.ws.2: encountered an exception, reconnecting in 1.0 seconds
Traceback (most recent call last):
  File "/home/user/venv/cryptostore/lib/python3.7/site-packages/cryptofeed/connection_handler.py", line 60, in _create_connection
    await self.subscribe(connection)
  File "/home/user/venv/cryptostore/lib/python3.7/site-packages/cryptofeed/exchange/bybit.py", line 86, in subscribe
    self.__reset(quote=quote)
  File "/home/user/venv/cryptostore/lib/python3.7/site-packages/cryptofeed/exchange/bybit.py", line 51, in __reset
    for symbol in self.l2_book:
RuntimeError: dictionary changed size during iteration
```
**Cryptofeed Version**
Git head (commit 8c412c7ec9539d3d6b43f1f07cc8c3e431ff204c).

**Fix**
The problem is that the `__reset` method deletes items from the `self.l2_book` dictionary while iterating over its keys:  https://github.com/bmoscon/cryptofeed/blob/5c46a105766fa3d6f9b8daa976577f99679fce46/cryptofeed/exchange/bybit.py#L53 
This should of course be avoided by iterating over a copy of the dictionary instead. If necessary I can prepare a PR, but it may be overkill for just adding `.copy()`.

**Comment by bmoscon** [comment]
fixed
