### ISSUE TITLE
KeyError when using `max_depth` with Kucoin

### ISSUE THREAD

**Issue by agijsberts** [bmoscon/cryptofeed#498]
**Describe the bug**
When setting a `max_depth` on the L2 updates for Kucoin, it repeatedly throws a `KeyError`.

I am not 100% sure, but I believe that the problem is that with the first update it will request a snapshot 
and set `Forced=True`, but if the snapshot's sequence number is higher than the one of the update, then the snapshot is actually never propagated to the `book_callback`.
https://github.com/bmoscon/cryptofeed/blob/c0de32ba97eb8af023a7b6d0f1b86d1074c56963/cryptofeed/exchange/kucoin.py#L175-L183
So the attribute `previous_book` will not be set once the first valid delta update arrives (with higher sequence number), hence the the `KeyError`.

**To Reproduce**
The following minimal example shows the bug:
```python
from cryptofeed import FeedHandler
from cryptofeed.defines import BID, ASK, L2_BOOK, BOOK_DELTA
from cryptofeed.exchanges import KuCoin

async def cb(**kwargs):
    print(kwargs)

f = FeedHandler()
f.add_feed(KuCoin(symbols=['BTC-USDT'], max_depth=10, channels=[L2_BOOK], callbacks={L2_BOOK: cb, BOOK_DELTA: cb}))
f.run()
```
The output:
```
2021-05-22 21:20:13,341 : ERROR : KUCOIN.ws.1: encountered an exception, reconnecting in 1.0 seconds
Traceback (most recent call last):
  File "/home/user/venv/cryptostore/lib/python3.7/site-packages/cryptofeed/connection_handler.py", line 64, in _create_connection
    await self._handler(connection, self.handler)
  File "/home/user/venv/cryptostore/lib/python3.7/site-packages/cryptofeed/connection_handler.py", line 113, in _handler
    await handler(message, connection, self.conn.last_message)
  File "/home/user/venv/cryptostore/lib/python3.7/site-packages/cryptofeed/exchange/kucoin.py", line 218, in message_handler
    await self._l2_book(msg, symbol, timestamp)
  File "/home/user/venv/cryptostore/lib/python3.7/site-packages/cryptofeed/exchange/kucoin.py", line 201, in _l2_book
    await self.book_callback(self.l2_book[symbol], L2_BOOK, symbol, forced, delta, timestamp, timestamp)
  File "/home/user/venv/cryptostore/lib/python3.7/site-packages/cryptofeed/feed.py", line 255, in book_callback
    delta, book = await self.apply_depth(book, True, symbol)
  File "/home/user/venv/cryptostore/lib/python3.7/site-packages/cryptofeed/feed.py", line 310, in apply_depth
    delta = book_delta(self.previous_book[symbol], ret)
  File "/home/user/venv/cryptostore/lib/python3.7/site-packages/cryptofeed/util/book.py", line 36, in book_delta
    fkeys = set(list(former[side].keys()))
KeyError: 'bid'

```

**Expected behavior**
No exception or reconnects, but a stable L2 feed with the imposed maximum depth.

**Operating System:**
Linux

**Cryptofeed Version**
Git head (c0de32ba97eb8af023a7b6d0f1b86d1074c56963).

**Comment by bmoscon** [comment]
if this is the same as #499 than this is fixed. If not, please re-open
