### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by maxholloway** [bmoscon/cryptofeed#506]
I am trying to perform error handling on a feed. When an error occurs in my program, the exception handler does not get invoked. Here's my example code:
```
from cryptofeed import FeedHandler
from cryptofeed.callback import BookCallback
from cryptofeed.defines import L2_BOOK
from cryptofeed.exchanges import Binance

def handle_exception(loop, context):
    print("\n\n\nInside the exception handler.\n\n\n")

def book_cb(feed, symbol, book, timestamp, receipt_timestamp):
    raise Exception("Contrived Exception Message")

if __name__ == "__main__":
    f = FeedHandler()
    # add symbols
    symbols = ["BTC-USDT"]
    
    f.add_feed(
        Binance(
            symbols=symbols, 
            channels=[L2_BOOK], 
            callbacks={L2_BOOK: BookCallback(book_cb)}))
    f.run(exception_handler=handle_exception)
```

I would expect that when an error arises in my program, the `handle_exception` exception handler would be invoked, and thus its message would be logged to the console. Unfortunately, all I see logged to the screen is the Exception message itself.

Error message:
```
2021-05-30 17:06:38,158 : ERROR : BINANCE.ws.1: encountered an exception, reconnecting in 1.0 seconds
Traceback (most recent call last):
  File "/home/ubuntu/dev/crypto-trade/venv/lib/python3.8/site-packages/cryptofeed/connection_handler.py", line 63, in _create_connection
    await self._handler(connection, self.handler)
  File "/home/ubuntu/dev/crypto-trade/venv/lib/python3.8/site-packages/cryptofeed/connection_handler.py", line 112, in _handler
    await handler(message, connection, self.conn.last_message)
  File "/home/ubuntu/dev/crypto-trade/venv/lib/python3.8/site-packages/cryptofeed/exchange/binance.py", line 355, in message_handler
    await self._book(msg, pair, timestamp)
  File "/home/ubuntu/dev/crypto-trade/venv/lib/python3.8/site-packages/cryptofeed/exchange/binance.py", line 276, in _book
    await self.book_callback(self.l2_book[pair], L2_BOOK, pair, forced, delta, timestamp_normalize(self.id, ts), timestamp)
  File "/home/ubuntu/dev/crypto-trade/venv/lib/python3.8/site-packages/cryptofeed/feed.py", line 282, in book_callback
    await self.callback(L2_BOOK, feed=self.id, symbol=symbol, book=book, timestamp=timestamp, receipt_timestamp=receipt_timestamp)
  File "/home/ubuntu/dev/crypto-trade/venv/lib/python3.8/site-packages/cryptofeed/feed.py", line 296, in callback
    await cb(**kwargs)
  File "/home/ubuntu/dev/crypto-trade/venv/lib/python3.8/site-packages/cryptofeed/callback.py", line 57, in __call__
    await super().__call__(feed, symbol, book, timestamp, receipt_timestamp)
  File "/home/ubuntu/dev/crypto-trade/venv/lib/python3.8/site-packages/cryptofeed/callback.py", line 24, in __call__
    await loop.run_in_executor(None, self.callback, *args, **kwargs)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "exception-issue.py", line 20, in book_cb
    raise Exception("Contrived Exception Message")
Exception: Contrived Exception Message
```

**Questions**
1.  Is it expected behavior for my exception handler to not be invoked?
2. How can I add an exception handler that triggers on all exceptions?

**Comment by bmoscon** [comment]
If you want to handle a top level exception (anything that happens before the connection handler is running) what you have will work. If you want to handle internal exceptions within the connections, you need to specify the exceptions you want to handle in the Feed object. This code worked for me:

```python
from cryptofeed import FeedHandler
from cryptofeed.callback import BookCallback
from cryptofeed.defines import L2_BOOK
from cryptofeed.exchanges import Binance

def handle_exception(loop, context):
    print("\n\n\nInside the exception handler.\n\n\n")

async def book_cb(feed, symbol, book, timestamp, receipt_timestamp):
    raise ValueError("Contrived Exception Message")

if __name__ == "__main__":
    f = FeedHandler()
    # add symbols
    symbols = ["BTC-USDT"]
    
    f.add_feed(
        Binance(exceptions=[ValueError],
            symbols=symbols, 
            channels=[L2_BOOK], 
            callbacks={L2_BOOK: BookCallback(book_cb)}))
    f.run(exception_handler=handle_exception)
```

As you can see I changed the exception to ValueError and then I specified that type to the exceptions kwarg in the Binance object

**Comment by bmoscon** [comment]
going to close this, but feel free to ask any more questions on this and I'll see them and respond. Or join the slack and ask there.
