### ISSUE TITLE
Kucoin order books can't be accessed (v2 deprecated) 

### ISSUE THREAD

**Issue by tudorelu** [bmoscon/cryptofeed#509]
**Describe the bug**
Unable to pull kucoin order books due to deprecation of v2 API.

**To Reproduce**
```py
from functools import partial
from time import time as timer

# crypto data & exchanges
from cryptofeed import FeedHandler
from cryptofeed.defines import KUCOIN, L2_BOOK
from cryptofeed.exchanges import KuCoin

async def on_orderbook_update(*args, **kwargs):
    # pprint(kwargs)
    feed = kwargs['feed']
    symbol = kwargs['symbol']
    timestamp = kwargs['timestamp']
    receipt_timestamp = kwargs['receipt_timestamp']
    now = timer()
    print('{} {}, timestamp_age: {} receipt_age: {}'.format(feed, symbol, now-timestamp, now-receipt_timestamp))


def main():
    config = {'log': {'filename': 'logs/kucoin_error.log', 'level': 'DEBUG'}}
    f = FeedHandler(config=config)
    callbacks = {
        L2_BOOK: partial(on_orderbook_update, L2_BOOK),
    }
    symbols = ['BTC-USDT']
    f.add_feed(KUCOIN, symbols=symbols, channels=[L2_BOOK], callbacks=callbacks)
    f.run()


if __name__ == '__main__':
    main()
```

Relevant Traceback
```sh
2021-06-07 09:34:29,439 : DEBUG : KUCOIN.http.0: create HTTP session
2021-06-07 09:34:29,439 : DEBUG : KUCOIN.http.0: requesting data from https://api.kucoin.com/api/v2/market/orderbook/level2?symbol=BTC-USDT
2021-06-07 09:34:30,119 : INFO : KUCOIN.ws.1: closed connection 'WebSocketClientProtocol'
2021-06-07 09:34:30,120 : ERROR : KUCOIN.ws.1: encountered an exception, reconnecting in 1.0 seconds
Traceback (most recent call last):
  File "/Users/tudor/Developer/Trading Bot/cex-arbitrageur/venv/lib/python3.9/site-packages/cryptofeed/connection_handler.py", line 63, in _create_connection
    await self._handler(connection, self.handler)
  File "/Users/tudor/Developer/Trading Bot/cex-arbitrageur/venv/lib/python3.9/site-packages/cryptofeed/connection_handler.py", line 112, in _handler
    await handler(message, connection, self.conn.last_message)
  File "/Users/tudor/Developer/Trading Bot/cex-arbitrageur/venv/lib/python3.9/site-packages/cryptofeed/exchange/kucoin.py", line 218, in message_handler
    await self._l2_book(msg, symbol, timestamp)
  File "/Users/tudor/Developer/Trading Bot/cex-arbitrageur/venv/lib/python3.9/site-packages/cryptofeed/exchange/kucoin.py", line 178, in _l2_book
    await self._snapshot(symbol)
  File "/Users/tudor/Developer/Trading Bot/cex-arbitrageur/venv/lib/python3.9/site-packages/cryptofeed/exchange/kucoin.py", line 146, in _snapshot
    data = await self.http_conn.read(url)
  File "/Users/tudor/Developer/Trading Bot/cex-arbitrageur/venv/lib/python3.9/site-packages/cryptofeed/connection.py", line 129, in read
    response.raise_for_status()
  File "/Users/tudor/Developer/Trading Bot/cex-arbitrageur/venv/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1000, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('https://api.kucoin.com/api/v2/market/orderbook/level2?symbol=BTC-USDT')
```

**Expected behavior**
Getting the Order Books

**Screenshots**
KuCoin recently deprecated v2 of their API for order books.

<img width="843" alt="Screen Shot 2021-06-07 at 9 43 41 am" src="https://user-images.githubusercontent.com/10128444/120943887-f9710700-c774-11eb-9a15-10c2c9b5acad.png">

**Operating System:**
 macOS

**Cryptofeed Version**
1.9.0 from pip

I intend to try fix this today (hoping it's as simple as I think it is)

**Comment by tudorelu** [comment]
Turns out the new KuCoin API requires API keys for the order books. I'd like to implement this, is there any other exchange implemented here from where I could get some inspiration?

**Comment by bmoscon** [comment]
@tudorelu every exchange is different. Gemini and Okcoin/Okex have authentication support. You can take a look at those
