### ISSUE TITLE
Authentication KuCoin not working?

### ISSUE THREAD

**Issue by michielmvs** [bmoscon/cryptofeed#521]
**TypeError: 'AttrDict' object is not callable**
When using the example nbbo_update function it doesn't seem to work for KuCoin.

**To Reproduce**
```
from cryptofeed import FeedHandler
from cryptofeed.exchanges import KuCoin

def nbbo_update(symbol, bid, bid_size, ask, ask_size, bid_feed, ask_feed):
    print(f'Pair: {symbol} Bid Price: {bid:.2f} Bid Size: {bid_size:.6f} Bid Feed: {bid_feed} Ask Price: {ask:.2f} Ask Size: {ask_size:.6f} Ask Feed: {ask_feed}')

def main():
    f = FeedHandler()
    f.add_nbbo([KuCoin], ['BTC-USDT'], nbbo_update)
    f.run()

main()
```

When I run above code in I get the following error:
```
2021-06-16 10:05:21,931 : ERROR : KUCOIN.ws.1: encountered an exception, reconnecting in 1.0 seconds
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cryptofeed/connection_handler.py", line 64, in _create_connection
    await self._handler(connection, self.handler)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cryptofeed/connection_handler.py", line 113, in _handler
    await handler(message, connection, self.conn.last_message)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cryptofeed/exchange/kucoin.py", line 225, in message_handler
    await self._l2_book(msg, symbol, timestamp)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cryptofeed/exchange/kucoin.py", line 185, in _l2_book
    await self._snapshot(symbol)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cryptofeed/exchange/kucoin.py", line 149, in _snapshot
    headers = generate_token(self.key_id, self.key_secret, self.key_passphrase, str_to_sign)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cryptofeed/auth/kucoin.py", line 19, in generate_token
    signature = base64.b64encode(hmac.new(key_secret.encode('utf-8'), str_to_sign.encode('utf-8'), hashlib.sha256).digest())
TypeError: 'AttrDict' object is not callable
```

**Expected behavior**
When running the same code but for a different exchange it does work. This is an example of the response: 
```
Pair: BTC-USD Bid Price: 40220.49 Bid Size: 0.031592 Bid Feed: GEMINI Ask Price: 40233.85 Ask Size: 0.840000 Ask Feed: GEMINI
Pair: BTC-USD Bid Price: 40220.49 Bid Size: 0.031592 Bid Feed: GEMINI Ask Price: 40231.12 Ask Size: 0.000200 Ask Feed: GEMINI
Pair: BTC-USD Bid Price: 40236.19 Bid Size: 0.017865 Bid Feed: COINBASE Ask Price: 40231.12 Ask Size: 0.000200 Ask Feed: GEMINI
```

**Operating System:**
 - macOS

**Cryptofeed Version**
I'm using python 3.9 and cryptofeed 1.9.2 (pip3 install git+git://github.com/bmoscon/cryptofeed.git)

**Comment by bmoscon** [comment]
you need to populate your config with your account information. look at this example:

https://github.com/bmoscon/cryptofeed/blob/master/examples/demo_kucoin_authenticated.py

**Comment by michielmvs** [comment]
I've created the config.yaml file and when using the the demo code you are linking to it al works, I'm receiving the book data from KUCOIN.

I've added the config.yaml line to the nbbo script but then I get the same error as before.

```
from cryptofeed import FeedHandler
from cryptofeed.exchanges import KuCoin


def nbbo_update(symbol, bid, bid_size, ask, ask_size, bid_feed, ask_feed):
    print(f'Pair: {symbol} Bid Price: {bid:.2f} Bid Size: {bid_size:.6f} Bid Feed: {bid_feed} Ask Price: {ask:.2f} Ask Size: {ask_size:.6f} Ask Feed: {ask_feed}')


def main():
    f = FeedHandler(config="config.yaml")
    f.add_nbbo([KuCoin], ['BTC-USDT'], nbbo_update)
    f.run()

main()
```

I don't understand why it is working for the [demo_kucoin_authenticated.py](https://github.com/bmoscon/cryptofeed/blob/master/examples/demo_kucoin_authenticated.py) demo but when I added it to the nbbo demo I get the same error. What am I doing wrong?
