### ISSUE TITLE
Fail to reset the Poloniex order book after disconnection

### ISSUE THREAD

**Issue by gavincyi** [bmoscon/cryptofeed#53]
It happened in two consecutive days that after running Poloniex feed for more than 5 hours, no longer it can parse the upcoming messages and keep returning error as follows.

```
2019-01-11 11:33:14,312 : ERROR : POLONIEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/root/workspace/cryptofeed/cryptofeed/feedhandler.py", line 156, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/root/workspace/cryptofeed/cryptofeed/feedhandler.py", line 174, in _handler
    await handler(message)
  File "/root/workspace/cryptofeed/cryptofeed/poloniex/poloniex.py", line 146, in message_handler
    LOG.warning("%s: missing sequence number. Received %d, expected %d", self.id, seq_no, self.seq_no+1)
TypeError: unsupported operand type(s) for +: 'dict' and 'int'

```

The issue is due to incorrect warning message formatted and it caused failure to reset the book.

**Comment by bmoscon** [comment]
fixed
