### ISSUE TITLE
Cannot save TRADES to Arctic DB

### ISSUE THREAD

**Issue by sauravskumar** [bmoscon/cryptofeed#535]
I am trying to save TRADES to Arctic db using cryptofeed but i am facing the issue below.
(I can save TICKER without any issues but TRADES seems to throw the error.)

Can someone please help ?

```
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\cryptofeed\connection_handler.py", line 64, in _create_connection
    await self._handler(connection, self.handler)
  File "C:\Anaconda3\lib\site-packages\cryptofeed\connection_handler.py", line 113, in _handler
    await handler(message, connection, self.conn.last_message)
  File "C:\Anaconda3\lib\site-packages\cryptofeed\exchange\bitfinex.py", line 293, in message_handler
    await chan_handler(msg, timestamp)
  File "C:\Anaconda3\lib\site-packages\cryptofeed\exchange\bitfinex.py", line 137, in _trades
    await _trade_update(trade, timestamp)
  File "C:\Anaconda3\lib\site-packages\cryptofeed\exchange\bitfinex.py", line 132, in _trade_update
    receipt_timestamp=timestamp)
  File "C:\Anaconda3\lib\site-packages\cryptofeed\feed.py", line 304, in callback
    await cb(**kwargs)
  File "C:\Anaconda3\lib\site-packages\cryptofeed\backends\backend.py", line 67, in __call__
    await self.write(feed, symbol, timestamp, receipt_timestamp, data)
  File "C:\Anaconda3\lib\site-packages\cryptofeed\backends\arctic.py", line 48, in write
    self.lib.append(self.key, df, upsert=True)
  File "C:\Anaconda3\lib\site-packages\arctic\decorators.py", line 50, in f_retry
    return f(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\arctic\store\version_store.py", line 605, in append
    raise Exception("Append not implemented for handler %s" % handler)
Exception: Append not implemented for handler <arctic.store._pickle_store.PickleStore object at 0x00000251D8422EC8>
```

Code i'm using to save TRADES
```
f.add_feed(Bitfinex(channels=[TRADES], symbols=['BTC-USD'], callbacks={TRADES: TradeArctic('cryptofeed-test')}))
```

![image](https://user-images.githubusercontent.com/5647704/123213376-8f31c380-d4e3-11eb-966c-d009bf4a83d7.png)

**Comment by bmoscon** [comment]
let me see if I can reproduce this

**Comment by sauravskumar** [comment]
> let me see if I can reproduce this

Sure... let me know if you need any help from my side to reproduce this

**Comment by sauravskumar** [comment]
@bmoscon Hi... any updates on the above if possible?

**Comment by bmoscon** [comment]
fixed
