### ISSUE TITLE
feedhandler has stop bug

### ISSUE THREAD

**Issue by xiandong79** [bmoscon/cryptofeed#554]
Background:
My strategy have an event loop, so, I start the crptofeed using 

```
self.feed_handler.add_feed(FTX(symbols=ftx_perp_feed_list, channels=[L2_BOOK], callbacks={L2_BOOK: self.ftx_book_process}))
self.feed_handler.run(start_loop=False)
```

During the running, the FTX book begin to delayed (have not find reason though) , so I want to re-start the feeds.

First, I need to 

```
self.feed_handler.stop()
```

Then, I get error,

```
E [2021-07-09 06:04:39,319] Task exception was never retrieved
future: <Task finished name='Task-2362218' coro=<BinanceMMExecutor.check_market_data_timestamp() done, defined at /home/ubuntu/CC_Trading/binance_mm/binance_mm.py:1299> exception=RuntimeError('This event loop is already running')>
Traceback (most recent call last):
  File "/home/ubuntu/CC_Trading/binance_mm/binance_mm.py", line 1312, in check_market_data_timestamp
    self.feed_handler.stop()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/cryptofeed/feedhandler.py", line 195, in stop
    loop.run_until_complete(asyncio.gather(*shutdown_tasks))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 592, in run_until_complete
    self._check_running()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 552, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
E [2021-07-09 06:04:39,458] Task exception was never retrieved
future: <Task finished name='Task-2362214' coro=<BinanceMMExecutor.get_symbol_info() done, defined at /home/ubuntu/CC_Trading/utils/decorator.py:37> exception=TimeoutError()>
Traceback (most recent call last):
  File "/home/ubuntu/CC_Trading/utils/decorator.py", line 43, in wrapper
    return await asyncio.wait_for(method(*args, **kwargs), timeout)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError
```
After this, I plan to run

```
self.feed_handler.run(start_loop=False)
```

Question2:
is this re-start correct ??

**Comment by bmoscon** [comment]
@xiandong79 it looks like your event loop is still running. calling stop requires the event loop to be stopped. I can add support for an async awaitable stop method that will work when the event loop is still running.

**Comment by bmoscon** [comment]
@xiandong79 this has been fixed on master - let me know if you still have issues. there is now a `stop_async` method that should work for your use case.

**Comment by xiandong79** [comment]
I need the event loop continues running, as there are other task from strategy part would need the event loop.

My main purpose here is to stop the feeds in feedhandler, and then re-start them.

**Comment by xiandong79** [comment]
just like the design of `feedhandler.run(start_loop=False)` ,  it would not start a new loop. For shutdown the feeds, I also do not want it stop the using/existing loop.
