### ISSUE TITLE
OKEx liquidations feed breaks after a few hours

### ISSUE THREAD

**Issue by idclevxx** [bmoscon/cryptofeed#555]
**Describe the bug**
 Similar error message to the ones below have occurred and broken the feed after a few hours. Have tested multiple times:
```
Task exception was never retrieved
future: <Task finished name='Task-148869' coro=<OKEx._liquidations() done, defined at /Users/username/Code/data/.venv/lib/python3.9/site-packages/cryptofeed/exchange/okex.py:59> exception=ClientResponseError(RequestInfo(url=URL('https://www.okex.com/api/futures/v3/instruments/LTC-USDT-211231/liquidation?status=0&limit=100'), method='GET', headers=<CIMultiDictProxy('Host': 'www.okex.com', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Python/3.9 aiohttp/3.7.4.post0', 'Cookie': 'locale=en_US')>, real_url=URL('https://www.okex.com/api/futures/v3/instruments/LTC-USDT-211231/liquidation?status=0&limit=100')), (), status=429, headers=<CIMultiDictProxy('Date': 'Wed, 07 Jul 2021 02:54:36 GMT', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Frame-Options': 'DENY', 'X-BrokerID': '0', 'CF-Cache-Status': 'DYNAMIC', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '66adca078f6b1d1e-CPH')>)>
Traceback (most recent call last):
  File "/Users/username/Code/data/.venv/lib/python3.9/site-packages/cryptofeed/exchange/okex.py", line 71, in _liquidations
    data = await self.http_conn.read(end_point)
  File "/Users/username/Code/data/.venv/lib/python3.9/site-packages/cryptofeed/connection.py", line 129, in read
    response.raise_for_status()
  File "/Users/username/Code/data/.venv/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1000, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 429, message='', url=URL('https://www.okex.com/api/futures/v3/instruments/LTC-USDT-211231/liquidation?status=0&limit=100')

---

Task exception was never retrieved
future: <Task finished name='Task-18' coro=<OKEx._liquidations() done, defined at /Users/username/Code/data/.venv/lib/python3.9/site-packages/cryptofeed/exchange/okex.py:59> exception=ClientResponseError(RequestInfo(url=URL('https://www.okex.com/api/futures/v3/instruments/ETH-USDT-210924/liquidation?status=0&limit=100'), method='GET', headers=<CIMultiDictProxy('Host': 'www.okex.com', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Python/3.9 aiohttp/3.7.4.post0', 'Cookie': 'locale=en_US')>, real_url=URL('https://www.okex.com/api/futures/v3/instruments/ETH-USDT-210924/liquidation?status=0&limit=100')), (), status=429, headers=<CIMultiDictProxy('Date': 'Wed, 07 Jul 2021 07:15:11 GMT', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Frame-Options': 'DENY', 'X-BrokerID': '0', 'CF-Cache-Status': 'DYNAMIC', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '66af47bbda5910b1-CPH')>)>
Traceback (most recent call last):
  File "/Users/username/Code/data/.venv/lib/python3.9/site-packages/cryptofeed/exchange/okex.py", line 71, in _liquidations
    data = await self.http_conn.read(end_point)
  File "/Users/username/Code/data/.venv/lib/python3.9/site-packages/cryptofeed/connection.py", line 129, in read
    response.raise_for_status()
  File "/Users/username/Code/data/.venv/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1000, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 429, message='', url=URL('https://www.okex.com/api/futures/v3/instruments/ETH-USDT-210924/liquidation?status=0&limit=100')

---

Task exception was never retrieved
future: <Task finished name='Task-886613' coro=<OKEx._liquidations() done, defined at /Users/username/Code/data/.venv/lib/python3.9/site-packages/cryptofeed/exchange/okex.py:59> exception=ClientResponseError(RequestInfo(url=URL('https://www.okex.com/api/swap/v3/instruments/BNT-USDT-SWAP/liquidation?status=1&limit=100'), method='GET', headers=<CIMultiDictProxy('Host': 'www.okex.com', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Python/3.9 aiohttp/3.7.4.post0', 'Cookie': 'locale=en_US')>, real_url=URL('https://www.okex.com/api/swap/v3/instruments/BNT-USDT-SWAP/liquidation?status=1&limit=100')), (), status=520, headers=<CIMultiDictProxy('Date': 'Thu, 08 Jul 2021 20:30:57 GMT', 'Content-Type': 'text/html; charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': 'cf_ob_info=520:66bc12840b8110b5:CPH; path=/; expires=Thu, 08-Jul-21 20:31:27 GMT', 'Set-Cookie': 'cf_use_ob=443; path=/; expires=Thu, 08-Jul-21 20:31:27 GMT', 'X-Frame-Options': 'SAMEORIGIN', 'Cache-Control': 'private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0', 'Expires': 'Thu, 01 Jan 1970 00:00:01 GMT', 'CF-RAY': '66bc12840b8110b5-CPH', 'Server': 'cloudflare')>)>
Traceback (most recent call last):
  File "/Users/username/Code/data/.venv/lib/python3.9/site-packages/cryptofeed/exchange/okex.py", line 71, in _liquidations
    data = await self.http_conn.read(end_point)
  File "/Users/username/Code/data/.venv/lib/python3.9/site-packages/cryptofeed/connection.py", line 129, in read
    response.raise_for_status()
  File "/Users/username/Code/data/.venv/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1000, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 520, message='', url=URL('https://www.okex.com/api/swap/v3/instruments/BNT-USDT-SWAP/liquidation?status=1&limit=100')
```

**To Reproduce**
Using this code to load all symbols into liquidations feed:
```
okex_symbols = []
okex_all = OKEx.info()
for k, v in okex_all['instrument_type'].items():
    if v == 'swap' or v == 'futures':
        okex_symbols.append(k)

f = FeedHandler()
f.add_feed(OKEx(channels=[LIQUIDATIONS], symbols=okex_symbols, callbacks={LIQUIDATIONS: LiquidationCallback(liquidations)}), timeout=-1)
```

**Operating System:**
 - macOS.

**Cryptofeed Version**
- pypi 1.9.1.

**Comment by idclevxx** [comment]
Regarding the "avalanche" issue, I can now more or less confirm this; same rows are printed on every start, e.g. this couple of rows showed up on every start of the feed:

```
('2021-07-08 19:45:58.567', 305.0, 'short', 4.455, 'omg-usdt-swap', 'okx')
('2021-07-08 19:45:58.567', 1066.0, 'short', 4.474, 'omg-usdt-swap', 'okx')
```


The odds of that happening 5 times in a row are slim. However, I realize this is probably an issue on OKEx end.

**Comment by bmoscon** [comment]
this should be fixed now, I added some code to handle 429s in the http polling classes

**Comment by idclevxx** [comment]
Thank you!
