### ISSUE TITLE
subscribe 125+ binance spot at once -> rate limit

### ISSUE THREAD

**Issue by xiandong79** [bmoscon/cryptofeed#558]
when subscibe 125 symbols in BINANCE, the rate limit occurs,

the rate limit reason is that `https://www.binance.com/api/v1/depth?symbol=ICPUSDT&limit=5000`, with `limit = 5000`, 
in Binance API weight, it is much high. 

Reference:
https://binance-docs.github.io/apidocs/spot/en/#order-book

I check the source code. when I set max_depth = 1. then, it should ask for `limit=5`
However, it finally sends a url with `limit=5000`

Reason:
in `cryptofeed/exchange/binance.py`

```
    async def _snapshot(self, pair: str) -> None:
        max_depth = self.max_depth if self.max_depth else 1000
        if max_depth not in self.valid_depths:
            for d in self.valid_depths:
                if d > max_depth:
                    max_depth = d
```
this `d` would increase gradually with subscribed_list,  `d` reachs 10, 20, ... finally 5000, then cause the rate-limit.

```
2021-07-12 07:06:24,191 : ERROR : BINANCE.ws.1: encountered an exception, reconnecting in 1.0 seconds
Traceback (most recent call last):
  File "/home/ubuntu/deployment/cryptofeed/cryptofeed/connection_handler.py", line 66, in _create_connection
    await self._handler(connection, self.handler)
  File "/home/ubuntu/deployment/cryptofeed/cryptofeed/connection_handler.py", line 115, in _handler
    await handler(message, connection, self.conn.last_message)
  File "/home/ubuntu/deployment/cryptofeed/cryptofeed/exchange/binance.py", line 356, in message_handler
    await self._book(msg, pair, timestamp)
  File "/home/ubuntu/deployment/cryptofeed/cryptofeed/exchange/binance.py", line 255, in _book
    await self._snapshot(exchange_pair)
  File "/home/ubuntu/deployment/cryptofeed/cryptofeed/exchange/binance.py", line 199, in _snapshot
    resp = await self.http_conn.read(url)
  File "/home/ubuntu/deployment/cryptofeed/cryptofeed/connection.py", line 129, in read
    response.raise_for_status()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1000, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 429, message='Too Many Requests', url=URL('https://www.binance.com/api/v1/depth?symbol=ICPUSDT&limit=5000')
```

**Comment by xiandong79** [comment]
I guess this is due to multi symbols share this `_snapshot()` function, and the `d` and `max_depth` is also shared in many `_snapshot()` function instances?

**Comment by bmoscon** [comment]
fixed - now uses correct limit on the api call - thanks for raising the issue!

**Comment by TnzGit** [comment]
I ran into a similar http 429 rate limit issue when subscribing to all Binance futures symbols l2_book. Not sure if this is the best way but I changed line 282 in binance.py from
`        resp = await self.http_conn.read(self.rest_endpoints[0].route('l2book', self.sandbox).format(pair, max_depth))
`
to
`        resp = await self.http_conn.read(self.rest_endpoints[0].route('l2book', self.sandbox).format(pair, max_depth), retry_count=1)
`
and it's working now because it would now wait and retry.
