### ISSUE TITLE
Perpetual Futures: Predicted funding rate

### ISSUE THREAD

**Issue by ibmua** [bmoscon/cryptofeed#589]
Hi! I tried getting funding rate on ftx, I thought it was going to get "Predicted funding rate", but I was only able to get the previous funding rate. Also, seems like there's currently no way to get FUTURES_INDEX on ftx from which it would be possible to approximate funding by oneself. Code (for v1.9.3):

```
from cryptofeed import FeedHandler
from cryptofeed.callback import FundingCallback
from cryptofeed.defines import FUNDING
from cryptofeed.exchanges import FTX

from cryptofeed.symbols import Symbol
from cryptofeed.defines import CANDLES, BID, ASK, BLOCKCHAIN, COINBASE, FUNDING, GEMINI, L2_BOOK, L3_BOOK, OPEN_INTEREST, PERPETUAL, TICKER, TRADES, FUTURES_INDEX, BOOK_DELTA
from cryptofeed.callback import BookCallback, FundingCallback, TickerCallback, TradeCallback, FuturesIndexCallback, OpenInterestCallback
from cryptofeed import FeedHandler
from cryptofeed.defines import BID, ASK, L2_BOOK, L3_BOOK, TICKER, TRADES, FUNDING, LIQUIDATIONS
from cryptofeed.exchanges import OKEx, Binance, BinanceFutures, BinanceDelivery, Poloniex, Gateio, FTX


symbol  = Symbol('FLOW', 'USD', type=PERPETUAL)

async def funding(**kwargs):
    print(f"Funding Update for {kwargs['feed']}")
    print(kwargs)

async def futures_index(**kwargs):
    print(f"FuturesIndex: {kwargs}")


def main():
    f = FeedHandler()
    f.add_feed(FTX(symbols=[symbol], channels=[FUNDING, FUTURES_INDEX], callbacks={FUNDING: FundingCallback(funding), FUTURES_INDEX: FuturesIndexCallback(futures_index)}))
    f.run()


if __name__ == '__main__':
    main()

```

This will fail with 

```
  File "/usr/local/lib/python3.8/dist-packages/cryptofeed/exchange.py", line 101, in std_channel_to_exchange
    return cls.websocket_channels[channel]
KeyError: 'futures_index'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ftx-funding-demo.py", line 39, in <module>
    main()
  File "ftx-funding-demo.py", line 33, in main
    f.add_feed(FTX(symbols=[symbol], channels=[FUNDING, FUTURES_INDEX], callbacks={FUNDING: FundingCallback(funding), FUTURES_INDEX: FuturesIndexCallback(futures_index)}))
  File "/usr/local/lib/python3.8/dist-packages/cryptofeed/exchanges/ftx.py", line 93, in __init__
    super().__init__('wss://ftexchange.com/ws/', **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/cryptofeed/feed.py", line 123, in __init__
    channels = list(set([self.std_channel_to_exchange(chan) for chan in channels]))
  File "/usr/local/lib/python3.8/dist-packages/cryptofeed/feed.py", line 123, in <listcomp>
    channels = list(set([self.std_channel_to_exchange(chan) for chan in channels]))
  File "/usr/local/lib/python3.8/dist-packages/cryptofeed/exchange.py", line 103, in std_channel_to_exchange
    raise UnsupportedDataFeed(f'{channel} is not supported on {cls.id}')
cryptofeed.exceptions.UnsupportedDataFeed: futures_index is not supported on FTX
```

But will work and show previous funding rate if the FUTURES_INDEX part is removed.

**Comment by bmoscon** [comment]
the funding channel will show the current rate. Is this what you want:


https://docs.ftx.com/#get-future-stats

?

The future-stats endpoints shows the next rate. (It doesn't look like a "predicted" rate, it looks like it will be the next rate? The docs aren't clear on that). Is this what you are looking for? Also, look at the output of FTX.info() - it shows the channels that are supported, and futures_index is not one of them.

**Comment by ibmua** [comment]
Yeah, it seems so. On FTX funding is constantly adjusted throughout the hour and applied when hour ends, similar to Binance, just hourly, not per 8 hours, so that can only be predicted funding rate.

**Comment by bmoscon** [comment]
@ibmua - ok, I'll add this to the futures data sometime this week - thanks for raising the issue

**Comment by bmoscon** [comment]
added
