### ISSUE TITLE
Binance perpetuals

### ISSUE THREAD

**Issue by jshellen** [bmoscon/cryptofeed#590]
Hi,

How do you subscribe to **BTC-USD** _Perpetual_ data at Binance? Supplying "BTC-USD" to the symbols-list produces an error. Code for reproducing the error and the error messages are given below.

I am, however, able to subscribe to BTC-USDT and BTC-BUSD (perpetuals?).  

**Example:**
`

    from cryptofeed import FeedHandler
    from cryptofeed.backends.mongo import BookDeltaMongo, BookMongo, TradeMongo, TickerMongo
    from cryptofeed.defines import BOOK_DELTA, L2_BOOK, TRADES, TICKER
    from cryptofeed.exchanges import BinanceFutures
          
    
    def main():
        """
        Because periods cannot be in keys in documents in mongo, the bids and asks dictionaries
        are converted to BSON. They will need to be decoded after being read
        """
        f = FeedHandler()
    
        f.add_feed(BinanceFutures(channels=[L2_BOOK, TRADES, TICKER],
                            #symbols=['BTC-USDT', 'BTC-BUSD'],    <---------------------------- This works ...
                            symbols=['BTC-USDT', 'BTC-BUSD', 'BTC-USD'],  <-------------------- This doesn't ...
                            callbacks={TRADES: TradeMongo('binance_futures', collection='trades'),
                                       L2_BOOK: BookMongo('binance_futures', collection='l2_book'),
                                       BOOK_DELTA: BookDeltaMongo('binance_futures', collection='l2_book')}))
    
        f.run()
    
    
    if __name__ == '__main__':
        main()
`

**The error**

`

        Traceback (most recent call last):
          File "C:\Users\juhas\PycharmProjects\recorder\main.py", line 30, in <module>
            main()
          File "C:\Users\juhas\PycharmProjects\recorder\main.py", line 20, in main
            f.add_feed(BinanceFutures(channels=[L2_BOOK, TRADES, TICKER],
          File "C:\Users\juhas\AppData\Local\Programs\Python\Python39\lib\site-packages\cryptofeed\exchange\binance_futures.py", line 39, in __init__
            super().__init__(**kwargs)
          File "C:\Users\juhas\AppData\Local\Programs\Python\Python39\lib\site-packages\cryptofeed\exchange\binance.py", line 49, in __init__
            super().__init__({}, **kwargs)
          File "C:\Users\juhas\AppData\Local\Programs\Python\Python39\lib\site-packages\cryptofeed\feed.py", line 132, in __init__
            symbols = [self.std_symbol_to_exchange_symbol(symbol) for symbol in symbols]
          File "C:\Users\juhas\AppData\Local\Programs\Python\Python39\lib\site-packages\cryptofeed\feed.py", line 132, in <listcomp>
            symbols = [self.std_symbol_to_exchange_symbol(symbol) for symbol in symbols]
          File "C:\Users\juhas\AppData\Local\Programs\Python\Python39\lib\site-packages\cryptofeed\feed.py", line 371, in std_symbol_to_exchange_symbol
            raise UnsupportedSymbol(f'{symbol} is not supported on {self.id}')
        cryptofeed.exceptions.UnsupportedSymbol: BTC-USD is not supported on BINANCE_FUTURES

`

**Comment by bmoscon** [comment]
Since I don't know what version you are running, you should check the output of BinanceFutures.symbols(), it will tell you what symbols are supported. In the master branch in github, they are all -PERP (for perpetual futures), so it would be BTC-USDT-PERP. In whatever version you are running, the project wide symbol standardization may or may not have been done yet, so refer to that. Either way, binance futures doesnt support any USD denominated contracts, so that wont work.
