### ISSUE TITLE
TypeError: unhashable type: 'list' when use with Postgres

### ISSUE THREAD

**Issue by boskiv** [bmoscon/cryptofeed#591]
**Describe the bug**
```
def main():
    f = FeedHandler()
    symbols = BinanceFutures.symbols()
    f.add_feed(BinanceFutures(channels=[CANDLES], symbols=[symbols], callbacks={CANDLES: CandlesPostgres(**postgres_cfg)}))
    f.run()
```

```
/Users/iskiridomov/PycharmProjects/corrBtc/venv/bin/python /Users/iskiridomov/PycharmProjects/corrBtc/main.py
Traceback (most recent call last):
  File "/Users/iskiridomov/PycharmProjects/corrBtc/main.py", line 27, in <module>
    main()
  File "/Users/iskiridomov/PycharmProjects/corrBtc/main.py", line 22, in main
    f.add_feed(BinanceFutures(channels=[CANDLES], symbols=[symbols], callbacks={CANDLES: CandlesPostgres(**postgres_cfg)}))
  File "/Users/iskiridomov/PycharmProjects/corrBtc/venv/lib/python3.9/site-packages/cryptofeed/exchange/binance_futures.py", line 39, in __init__
    super().__init__(**kwargs)
  File "/Users/iskiridomov/PycharmProjects/corrBtc/venv/lib/python3.9/site-packages/cryptofeed/exchange/binance.py", line 49, in __init__
    super().__init__({}, **kwargs)
  File "/Users/iskiridomov/PycharmProjects/corrBtc/venv/lib/python3.9/site-packages/cryptofeed/feed.py", line 138, in __init__
    symbols = [self.std_symbol_to_exchange_symbol(symbol) for symbol in symbols]
  File "/Users/iskiridomov/PycharmProjects/corrBtc/venv/lib/python3.9/site-packages/cryptofeed/feed.py", line 138, in <listcomp>
    symbols = [self.std_symbol_to_exchange_symbol(symbol) for symbol in symbols]
  File "/Users/iskiridomov/PycharmProjects/corrBtc/venv/lib/python3.9/site-packages/cryptofeed/feed.py", line 389, in std_symbol_to_exchange_symbol
    return self.normalized_symbol_mapping[symbol]
TypeError: unhashable type: 'list'
```

cryptofeed-1.9.2

**Comment by bmoscon** [comment]
@boskiv symbols = BinanceFutures.symbols() returns a list, and then you are putting it into another list when you do symbols=[symbols]

try this:

```python
def main():
    f = FeedHandler()
    symbols = BinanceFutures.symbols()
    f.add_feed(BinanceFutures(channels=[CANDLES], symbols=symbols, callbacks={CANDLES: CandlesPostgres(**postgres_cfg)}))
    f.run()
```

**Comment by bmoscon** [comment]
I believe this will resolve your problem, but if not please re-open the issue

**Comment by boskiv** [comment]
Yeh, @bmoscon that was totally my mistake. there was 5 am, so I just missed that and guessed about it already when was in bed :)
