### ISSUE TITLE
Hit the limit when subscribe all pairs on trades channel on KuCoin

### ISSUE THREAD

**Issue by kosmodromov** [bmoscon/cryptofeed#621]
**Describe the bug**
Get the error message when trying to subscribe on trades channel with all pairs
{'id': '1', 'type': 'error', 'code': 509, 'data': 'exceed max subscription count limitation of 100 per time'}

**To Reproduce**

`
from cryptofeed.defines import TRADES
from cryptofeed.exchanges import KuCoin
from cryptofeed.feedhandler import FeedHandler
from cryptofeed.callback import TradeCallback

async def trade(*args):
    print(args)

pairs = KuCoin.info()['symbols']
print(len(pairs))

f = FeedHandler()
f.add_feed(
    KuCoin(
        symbols=pairs,
        channels=[TRADES],
        callbacks={TRADES: TradeCallback(trade)}
    )
)

f.run()
`

* Provide any tracebacks, if applicable

```
2021-09-02 12:18:08,375 : ERROR : KUCOIN.ws.1: encountered an exception, reconnecting in 1.0 seconds
Traceback (most recent call last):
  File "/home/dbodunov/crfd/venv/lib/python3.8/site-packages/cryptofeed/connection_handler.py", line 68, in _create_connection
    await self._handler(connection, self.handler)
  File "/home/dbodunov/crfd/venv/lib/python3.8/site-packages/cryptofeed/connection_handler.py", line 117, in _handler
    await handler(message, connection, self.conn.last_message)
  File "/home/dbodunov/crfd/venv/lib/python3.8/site-packages/cryptofeed/exchanges/kucoin.py", line 223, in message_handler
    topic, symbol = msg['topic'].split(":", 1)
KeyError: 'topic'
```

**Expected behavior**
Subscribe to trades channel for all pairs

**Operating System:**
macOS, linux

**Cryptofeed Version**

1.9.3 from pypi

**Comment by bmoscon** [comment]
you can work around this by breaking the subscription into multiple calls to `add_feed`, but yes, this should be handled internally in the kucoin code.

**Comment by bmoscon** [comment]
this has been addressed. Kucoin has a limit of 300 per connection, but will now subscribe to 300 correctly. also emits error when sub'd to more than 300, and no longer crashes on error messages from kucoin
