### ISSUE TITLE
`websockets==10.0` seems breaking some feeds ws connection

### ISSUE THREAD

**Issue by wangzhe3224** [bmoscon/cryptofeed#626]
**Describe the bug**
I updated `websockets` to 10.0 from 9.1, and it breaks feed ws connection at least for Binance and Bybit.

**To Reproduce**
``` Python
from cryptofeed import FeedHandler
from cryptofeed.callback import BookCallback
from cryptofeed.defines import BID, ASK, L2_BOOK
from cryptofeed.exchanges import (Bybit, BinanceFutures)


async def book(book, receipt_timestamp):
    print(f'Book received at {receipt_timestamp} for {book.exchange} - {book.symbol}, with {len(book.book)} entries. Top of book prices: {book.book.asks.index(0)[0]} - {book.book.bids.index(0)[0]}')
    if book.delta:
        print(f"Delta from last book contains {len(book.delta[BID]) + len(book.delta[ASK])} entries.")
    if book.sequence_number:
        assert isinstance(book.sequence_number, int)

config = {'log': {'filename': 'demo.log', 'level': 'INFO'}}
f = FeedHandler(config=config)
f.add_feed(Bybit(symbols=['ADA-USDT-PERP'], channels=[L2_BOOK], callbacks={L2_BOOK: BookCallback(book)}))
f.add_feed(BinanceFutures(symbols=['ADA-USDT-PERP'], channels=[L2_BOOK], callbacks={L2_BOOK: BookCallback(book)}))
f.run()
```

Traceback:

```
2021-09-14 09:06:13,868 : ERROR : BYBIT.ws.2: encountered an exception, reconnecting in 4.0 seconds
Traceback (most recent call last):
  File "/Users/zhewang/Projects/cryptofeed/cryptofeed/connection_handler.py", line 58, in _create_connection
    async with self.conn.connect() as connection:
  File "/Users/zhewang/anaconda3/lib/python3.7/contextlib.py", line 170, in __aenter__
    return await self.gen.__anext__()
  File "/Users/zhewang/Projects/cryptofeed/cryptofeed/connection.py", line 94, in connect
    await self._open()
  File "/Users/zhewang/Projects/cryptofeed/cryptofeed/connection.py", line 304, in _open
    self.conn = await websockets.connect(self.address, **self.ws_kwargs)
  File "/Users/zhewang/Projects/cryptofeed/private/env/lib/python3.7/site-packages/websockets/legacy/client.py", line 649, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "/Users/zhewang/anaconda3/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/Users/zhewang/Projects/cryptofeed/private/env/lib/python3.7/site-packages/websockets/legacy/client.py", line 665, in __await_impl__
    extra_headers=protocol.extra_headers,
  File "/Users/zhewang/Projects/cryptofeed/private/env/lib/python3.7/site-packages/websockets/legacy/client.py", line 332, in handshake
    response_headers, available_extensions
  File "/Users/zhewang/Projects/cryptofeed/private/env/lib/python3.7/site-packages/websockets/legacy/client.py", line 221, in process_extensions
    f"Unsupported extension: "
websockets.exceptions.NegotiationError: Unsupported extension: name = permessage-deflate, params = [('server_no_context_takeover', None), ('client_no_context_takeover', None)]
```

**Expected behavior**
Connect without issue using New WebSocket version

**Screenshots**
None

**Operating System:**
macOS

**Cryptofeed Version**
Latest master build from source.

**Comment by bmoscon** [comment]
seems the issue is caused by non-compliant exchanges that do not correctly implement the websocket RFC. I've put in a workaround for the affected exchanges (bybit, bitmex, gateio, ftx)
