### ISSUE TITLE
BookRedis error on L2_BOOK

### ISSUE THREAD

**Issue by xiandong79** [bmoscon/cryptofeed#634]
**My target is to use BookRedis (sorted set in redis) to save the top (depth=1) of orderbook.**

with latest release:
```
        fh = FeedHandler()
        fh.add_feed(BinanceFutures(max_depth=1, subscription={L2_BOOK: symbols}, callbacks={L2_BOOK: BookRedis()}))
        fh.run()
```

```
  File "/home/ubuntu/.local/lib/python3.8/site-packages/cryptofeed/exchanges/binance_futures.py", line 130, in message_handler
    await self._book(msg, pair, timestamp)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/cryptofeed/exchanges/binance.py", line 330, in _book
    return await self._handle_book_msg(*book_args)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/cryptofeed/exchanges/binance.py", line 279, in _handle_book_msg
    return await self.book_callback(L2_BOOK, self._l2_book[std_pair], timestamp, raw=msg, sequence_number=self.last_update_id[std_pair], timestamp=self.timestamp_normalize(msg['E']))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/cryptofeed/feed.py", line 182, in book_callback
    await self.callback(book_type, book, receipt_timestamp)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/cryptofeed/feed.py", line 193, in callback
    await cb(obj, receipt_timestamp)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/cryptofeed/backends/backend.py", line 58, in __call__
    await self.write(data)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/cryptofeed/backends/redis.py", line 131, in write
    if data['delta'] is None:
KeyError: 'delta
```

**Comment by xiandong79** [comment]
imo, it is due following line does not consider the 'delta'

```
if current_match:
            # Current msg.final_update_id == self.last_update_id[pair] which is the snapshot's update id
            return await self.book_callback(L2_BOOK, self._l2_book[std_pair], timestamp, raw=msg, sequence_number=self.last_update_id[std_pair], timestamp=self.timestamp_normalize(msg['E']))
```

https://github.com/bmoscon/cryptofeed/blob/c17215cad9781ebd263a723676fdd9dc6598f303/cryptofeed/exchanges/binance.py#L279

**Comment by xiandong79** [comment]
```
class BookStream(RedisStreamCallback, BackendBookCallback):
    default_key = 'book'

    async def write(self, data: dict):
        if 'delta' in data:
            data['delta'] = json.dumps(data['delta'])
        elif 'book' in data:
            data['book'] = json.dumps(data['book'])

        if data['timestamp'] is None:
            data['timestamp'] = 'None'
        await super().write(data)
```

with deeper exploration, with current design on

```
class BackendBookCallback:
    async def __call__(self, book, receipt_timestamp: float):
        data = book.to_dict(delta=book.delta is not None, as_type=self.numeric_type)
        if book.delta is None:
            del data['delta']
        data['receipt_timestamp'] = receipt_timestamp
        await self.write(data)
```

BookStream would only send the book_delta into Redis, and ignore the orderbook. not sure this is design on purpose or not. (if design on purpose, the user has no solution to save full orderbook via BookStream)

**Comment by xiandong79** [comment]
fundumentally, it is 

`book.to_dict(delta=book.delta is not None, as_type=self.numeric_type)`

to save the book.delta as the 1st priority, now.

```
            return {'exchange': self.exchange, 'symbol': self.symbol, 'delta': {BID: [(as_type(price), as_type(size)) for price, size in self.delta[BID]], ASK: [(as_type(price), as_type(size)) for price, size in self.delta[ASK]]} if self.delta else None, 'timestamp': self.timestamp}
```
and book is ignored.

**Comment by xiandong79** [comment]
----with your latest updates
I have faced an error. it is due to cpython could not receive keyword arguments

```
2021-09-17 01:42:56,020 : ERROR : BINANCE_FUTURES.ws.1: encountered an exception, reconnecting in 1.0 seconds
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/cryptofeed-2.0.1-py3.8-linux-x86_64.egg/cryptofeed/connection_handler.py", line 68, in _create_connection
    await self._handler(connection, self.handler)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/cryptofeed-2.0.1-py3.8-linux-x86_64.egg/cryptofeed/connection_handler.py", line 117, in _handler
    await handler(message, connection, self.conn.last_message)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/cryptofeed-2.0.1-py3.8-linux-x86_64.egg/cryptofeed/exchanges/binance_futures.py", line 127, in message_handler
    await self._book(msg, pair, timestamp)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/cryptofeed-2.0.1-py3.8-linux-x86_64.egg/cryptofeed/exchanges/binance.py", line 319, in _book
    await self._snapshot(pair)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/cryptofeed-2.0.1-py3.8-linux-x86_64.egg/cryptofeed/exchanges/binance.py", line 264, in _snapshot
    await self.book_callback(L2_BOOK, self._l2_book[std_pair], time.time(), raw=resp, timestamp=ts, sequence_number=resp['lastUpdateId'])
  File "/home/ubuntu/.local/lib/python3.8/site-packages/cryptofeed-2.0.1-py3.8-linux-x86_64.egg/cryptofeed/feed.py", line 181, in book_callback
    await self.callback(book_type, book, receipt_timestamp)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/cryptofeed-2.0.1-py3.8-linux-x86_64.egg/cryptofeed/feed.py", line 192, in callback
    await cb(obj, receipt_timestamp)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/cryptofeed-2.0.1-py3.8-linux-x86_64.egg/cryptofeed/backends/backend.py", line 55, in __call__
    data = book.to_dict(as_type=self.numeric_type)
  File "cryptofeed/types.pyx", line 295, in cryptofeed.types.OrderBook.to_dict
TypeError: to_dict() takes no keyword arguments
```

**Comment by xiandong79** [comment]
Then, I think i should update following, however it does not work

```
# setup.py
...
setup(
    ext_modules=cythonize(
        './param_test.py', 
        compiler_directives={'always_allow_keywords': True}
    )
)
```

**Comment by xiandong79** [comment]
I should update the orderbook lib to 0.4.0.
all good now
