### ISSUE TITLE
With websockets==10.0 cryptofeed can't connect to Bitmex

### ISSUE THREAD

**Issue by xbarra** [bmoscon/cryptofeed#653]
**Describe the bug**
With websockets==10.0 cryptofeed can't connect to Bitmex.

**To Reproduce**
* Small sample
```
config = {
        'log': {
            'filename': 'demo_bitmex.log',
            'level': 'DEBUG'},
        'bitmex': {
            'key_id': 'whatever',
            'key_secret': 'Does not matter if you provide bitmex config or not'},
    }
    f = FeedHandler(config=config)
    f.add_feed(Bitmex(symbols=['BTC-USD-21Z31'], max_depth=1, channels=[L2_BOOK ], callbacks={L2_BOOK: gett2t}))
    f.run()
```

* traceback:
```
2021-09-24 07:42:36,522 : DEBUG : BITMEX.ws.1: connecting to wss://www.bitmex.com/realtime
2021-09-24 07:42:36,725 : ERROR : BITMEX.ws.1: encountered an exception, reconnecting in 8.0 seconds
Traceback (most recent call last):
  File "/home/xdev/cryptofeedtest/venv/lib/python3.9/site-packages/cryptofeed/connection_handler.py", line 58, in _create_connection
    async with self.conn.connect() as connection:
  File "/usr/lib/python3.9/contextlib.py", line 181, in __aenter__
    return await self.gen.__anext__()
  File "/home/xdev/cryptofeedtest/venv/lib/python3.9/site-packages/cryptofeed/connection.py", line 94, in connect
    await self._open()
  File "/home/xdev/cryptofeedtest/venv/lib/python3.9/site-packages/cryptofeed/connection.py", line 304, in _open
    self.conn = await websockets.connect(self.address, **self.ws_kwargs)
  File "/home/xdev/cryptofeedtest/venv/lib/python3.9/site-packages/websockets/legacy/client.py", line 649, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/home/xdev/cryptofeedtest/venv/lib/python3.9/site-packages/websockets/legacy/client.py", line 660, in __await_impl__
    await protocol.handshake(
  File "/home/xdev/cryptofeedtest/venv/lib/python3.9/site-packages/websockets/legacy/client.py", line 331, in handshake
    self.extensions = self.process_extensions(
  File "/home/xdev/cryptofeedtest/venv/lib/python3.9/site-packages/websockets/legacy/client.py", line 220, in process_extensions
    raise NegotiationError(
websockets.exceptions.NegotiationError: Unsupported extension: name = permessage-deflate, params = [('client_no_context_takeover', None)]
```

**Expected behavior**
A connection will be established and the program will get updates. 
With websockets==9.1 and cryptofeed==1.9.3 The program works as expected.

**Operating System:**
 - linux, windows

**Cryptofeed Version**
- Linux: cryptofeed==2.0.1 (fails in 2.0.0 too).
- Windows: cryptofeed==1.9.3

**Comment by bmoscon** [comment]
works for me in 2.0.0. and 2.0.1. If you can provide a reproducible example, I'll investigate. If I remove this line: 
https://github.com/bmoscon/cryptofeed/blob/master/cryptofeed/exchanges/bitmex.py#L64

I get the error you have above, so I'm pretty sure this has been fixed. Try recreating your venv, or removing cryptofeed and re-installing. I did just that to test this - I created a new virtual env, installed websockets 10.0, then cryptofeed 2.0.1 and tested with a bitmex feedhandler. No issues

**Comment by xbarra** [comment]
I just checked and with the old env I had missing that line.

With a fresh venv it's working perfectly.

Thank you for the fast answer. 
I am closing the issue.
