### ISSUE TITLE
Race Condition in Binance L2_BOOK feed/snapshot logic when concurrent_http is True and feed is restarted

### ISSUE THREAD

**Issue by nirvana-msu** [bmoscon/cryptofeed#671]
**Describe the bug**
There is a race condition bug within snapshot handling logic for Binance feed when using ` concurrent_http=True `, and feed is getting restarted for whatever reason. It leads either to `KeyError` exceptions, or possibly even to incorrect order book state in certain cases.

**To Reproduce**
You can run the following script to reproduce. I've tested it against the current release, `2.0.1`. I've reduced timeout settings to make it trigger more often - with these settings I can see exceptions ~ once every minute.

```python
import asyncio
import logging
import sys
import time

from cryptofeed import FeedHandler
from cryptofeed.defines import BINANCE, L2_BOOK
from cryptofeed.types import OrderBook

format_ = '%(asctime)s [%(threadName)-10s|pid:%(process)-5d] [%(name)s] %(levelname)s: %(message)s'
logging.basicConfig(level=logging.INFO, format=format_, handlers=[logging.StreamHandler(sys.stderr)])

logger = logging.getLogger(__name__)

counter = 0


async def l2_book(ob: OrderBook, receipt_timestamp: float):
    global counter
    if counter % 2 == 0:
        logger.info("Sleeping for 5 seconds")
        time.sleep(5)
        await asyncio.sleep(1)
        logger.info("Finished sleeping")
    counter += 1


fh = FeedHandler()
fh.add_feed(
    BINANCE, symbols=['BTC-USDT'], channels=[L2_BOOK], callbacks={L2_BOOK: l2_book},
    max_depth=10, depth_interval='1000ms', concurrent_http=True, timeout=4, timeout_interval=1,
)
fh.run()
```

Sample output:

```
2021-10-02 01:57:53,257 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 01:57:58,263 : WARNING : BINANCE.ws.1: received no messages within timeout, restarting connection
2021-10-02 01:57:59,262 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 01:57:59,264 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 01:58:05,271 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 01:58:05,275 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 01:58:11,283 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 01:58:11,283 [MainThread|pid:1539813] [asyncio] ERROR: Task exception was never retrieved
future: <Task finished name='Task-7' coro=<Binance._book.<locals>._concurrent_snapshot() done, defined at /home/grumpycat/dev/crypto-feed-handler/venv/lib/python3.9/site-packages/cryptofeed/exchanges/binance.py:366> exception=KeyError('BTC-USDT')>
Traceback (most recent call last):
  File "/home/grumpycat/dev/crypto-feed-handler/venv/lib/python3.9/site-packages/cryptofeed/exchanges/binance.py", line 368, in _concurrent_snapshot
    while len(self._book_buffer[std_pair]) > 0:
KeyError: 'BTC-USDT'
2021-10-02 01:58:12,356 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 01:58:17,363 : WARNING : BINANCE.ws.1: received no messages within timeout, restarting connection
2021-10-02 01:58:18,362 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 01:58:18,365 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 01:58:24,371 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 01:58:24,372 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 01:58:30,379 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 01:58:33,273 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 01:58:38,279 : WARNING : BINANCE.ws.1: received no messages within timeout, restarting connection
2021-10-02 01:58:39,280 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 01:58:39,282 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 01:58:45,289 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 01:58:45,291 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 01:58:50,554 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 01:58:55,562 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 01:58:55,563 : WARNING : BINANCE.ws.1: received no messages within timeout, restarting connection
2021-10-02 01:58:55,565 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 01:59:00,571 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 01:59:00,572 [MainThread|pid:1539813] [asyncio] ERROR: Task exception was never retrieved
future: <Task finished name='Task-34' coro=<Binance._book.<locals>._concurrent_snapshot() done, defined at /home/grumpycat/dev/crypto-feed-handler/venv/lib/python3.9/site-packages/cryptofeed/exchanges/binance.py:366> exception=KeyError('BTC-USDT')>
Traceback (most recent call last):
  File "/home/grumpycat/dev/crypto-feed-handler/venv/lib/python3.9/site-packages/cryptofeed/exchanges/binance.py", line 368, in _concurrent_snapshot
    while len(self._book_buffer[std_pair]) > 0:
KeyError: 'BTC-USDT'
2021-10-02 01:59:01,572 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 01:59:01,576 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 01:59:07,584 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 01:59:07,588 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 01:59:13,595 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 01:59:16,345 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 01:59:21,352 : WARNING : BINANCE.ws.1: received no messages within timeout, restarting connection
2021-10-02 01:59:22,352 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 01:59:22,355 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 01:59:28,361 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 01:59:28,364 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 01:59:34,366 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 01:59:37,266 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 01:59:42,271 : WARNING : BINANCE.ws.1: received no messages within timeout, restarting connection
2021-10-02 01:59:43,270 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 01:59:43,273 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 01:59:49,281 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 01:59:49,285 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 01:59:55,291 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 01:59:55,292 [MainThread|pid:1539813] [asyncio] ERROR: Task exception was never retrieved
future: <Task finished name='Task-52' coro=<Binance._book.<locals>._concurrent_snapshot() done, defined at /home/grumpycat/dev/crypto-feed-handler/venv/lib/python3.9/site-packages/cryptofeed/exchanges/binance.py:366> exception=KeyError('BTC-USDT')>
Traceback (most recent call last):
  File "/home/grumpycat/dev/crypto-feed-handler/venv/lib/python3.9/site-packages/cryptofeed/exchanges/binance.py", line 368, in _concurrent_snapshot
    while len(self._book_buffer[std_pair]) > 0:
KeyError: 'BTC-USDT'
2021-10-02 01:59:56,343 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:00:01,350 : WARNING : BINANCE.ws.1: received no messages within timeout, restarting connection
2021-10-02 02:00:02,350 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:00:02,355 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:00:08,358 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:00:08,361 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:00:14,368 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:00:17,272 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:00:22,280 : WARNING : BINANCE.ws.1: received no messages within timeout, restarting connection
2021-10-02 02:00:23,279 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:00:23,282 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:00:29,289 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:00:29,291 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:00:35,298 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:00:35,301 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:00:41,235 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:00:46,242 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:00:46,243 : WARNING : BINANCE.ws.1: received no messages within timeout, restarting connection
2021-10-02 02:00:46,246 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:00:51,252 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:00:51,252 [MainThread|pid:1539813] [asyncio] ERROR: Task exception was never retrieved
future: <Task finished name='Task-79' coro=<Binance._book.<locals>._concurrent_snapshot() done, defined at /home/grumpycat/dev/crypto-feed-handler/venv/lib/python3.9/site-packages/cryptofeed/exchanges/binance.py:366> exception=KeyError('BTC-USDT')>
Traceback (most recent call last):
  File "/home/grumpycat/dev/crypto-feed-handler/venv/lib/python3.9/site-packages/cryptofeed/exchanges/binance.py", line 368, in _concurrent_snapshot
    while len(self._book_buffer[std_pair]) > 0:
KeyError: 'BTC-USDT'
2021-10-02 02:00:52,252 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:00:52,253 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:00:58,261 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:00:58,263 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:01:04,270 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:01:06,282 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:01:11,289 : WARNING : BINANCE.ws.1: received no messages within timeout, restarting connection
2021-10-02 02:01:12,289 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:01:12,291 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:01:18,298 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:01:18,300 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:01:24,305 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:01:24,310 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:01:30,249 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:01:35,255 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:01:35,256 : WARNING : BINANCE.ws.1: received no messages within timeout, restarting connection
2021-10-02 02:01:35,259 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:01:40,265 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:01:40,266 [MainThread|pid:1539813] [asyncio] ERROR: Task exception was never retrieved
future: <Task finished name='Task-97' coro=<Binance._book.<locals>._concurrent_snapshot() done, defined at /home/grumpycat/dev/crypto-feed-handler/venv/lib/python3.9/site-packages/cryptofeed/exchanges/binance.py:366> exception=KeyError('BTC-USDT')>
Traceback (most recent call last):
  File "/home/grumpycat/dev/crypto-feed-handler/venv/lib/python3.9/site-packages/cryptofeed/exchanges/binance.py", line 368, in _concurrent_snapshot
    while len(self._book_buffer[std_pair]) > 0:
KeyError: 'BTC-USDT'
2021-10-02 02:01:41,266 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:01:41,268 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:01:47,274 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:01:47,277 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:01:53,284 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:01:55,280 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:02:00,288 : WARNING : BINANCE.ws.1: received no messages within timeout, restarting connection
2021-10-02 02:02:01,288 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:02:01,290 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:02:07,298 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:02:07,299 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:02:13,306 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:02:13,306 [MainThread|pid:1539813] [asyncio] ERROR: Task exception was never retrieved
future: <Task finished name='Task-106' coro=<Binance._book.<locals>._concurrent_snapshot() done, defined at /home/grumpycat/dev/crypto-feed-handler/venv/lib/python3.9/site-packages/cryptofeed/exchanges/binance.py:366> exception=KeyError('BTC-USDT')>
Traceback (most recent call last):
  File "/home/grumpycat/dev/crypto-feed-handler/venv/lib/python3.9/site-packages/cryptofeed/exchanges/binance.py", line 368, in _concurrent_snapshot
    while len(self._book_buffer[std_pair]) > 0:
KeyError: 'BTC-USDT'
2021-10-02 02:02:14,343 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:02:19,350 : WARNING : BINANCE.ws.1: received no messages within timeout, restarting connection
2021-10-02 02:02:20,350 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:02:20,352 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:02:26,358 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:02:26,361 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:02:32,368 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:02:35,289 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:02:40,297 : WARNING : BINANCE.ws.1: received no messages within timeout, restarting connection
2021-10-02 02:02:41,296 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:02:41,300 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:02:47,307 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:02:47,310 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:02:53,316 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:02:53,317 [MainThread|pid:1539813] [asyncio] ERROR: Task exception was never retrieved
future: <Task finished name='Task-124' coro=<Binance._book.<locals>._concurrent_snapshot() done, defined at /home/grumpycat/dev/crypto-feed-handler/venv/lib/python3.9/site-packages/cryptofeed/exchanges/binance.py:366> exception=KeyError('BTC-USDT')>
Traceback (most recent call last):
  File "/home/grumpycat/dev/crypto-feed-handler/venv/lib/python3.9/site-packages/cryptofeed/exchanges/binance.py", line 368, in _concurrent_snapshot
    while len(self._book_buffer[std_pair]) > 0:
KeyError: 'BTC-USDT'
2021-10-02 02:02:54,356 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:02:59,363 : WARNING : BINANCE.ws.1: received no messages within timeout, restarting connection
2021-10-02 02:03:00,362 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:03:00,366 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:03:06,372 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:03:06,374 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:03:12,379 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:03:14,626 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:03:19,632 : WARNING : BINANCE.ws.1: received no messages within timeout, restarting connection
2021-10-02 02:03:20,633 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:03:20,635 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:03:26,639 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:03:26,643 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:03:32,649 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:03:33,616 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:03:38,623 : WARNING : BINANCE.ws.1: received no messages within timeout, restarting connection
2021-10-02 02:03:39,622 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:03:39,623 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:03:45,627 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:03:45,629 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:03:51,636 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:03:51,637 [MainThread|pid:1539813] [asyncio] ERROR: Task exception was never retrieved
future: <Task finished name='Task-151' coro=<Binance._book.<locals>._concurrent_snapshot() done, defined at /home/grumpycat/dev/crypto-feed-handler/venv/lib/python3.9/site-packages/cryptofeed/exchanges/binance.py:366> exception=KeyError('BTC-USDT')>
Traceback (most recent call last):
  File "/home/grumpycat/dev/crypto-feed-handler/venv/lib/python3.9/site-packages/cryptofeed/exchanges/binance.py", line 368, in _concurrent_snapshot
    while len(self._book_buffer[std_pair]) > 0:
KeyError: 'BTC-USDT'
2021-10-02 02:03:53,356 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:03:58,364 : WARNING : BINANCE.ws.1: received no messages within timeout, restarting connection
2021-10-02 02:03:59,363 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:03:59,367 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:04:05,374 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:04:05,376 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:04:11,382 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:04:14,289 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:04:19,294 : WARNING : BINANCE.ws.1: received no messages within timeout, restarting connection
2021-10-02 02:04:20,294 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:04:20,295 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:04:26,298 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:04:26,299 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:04:31,554 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:04:36,561 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:04:36,562 : WARNING : BINANCE.ws.1: received no messages within timeout, restarting connection
2021-10-02 02:04:36,564 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:04:41,570 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:04:41,571 [MainThread|pid:1539813] [asyncio] ERROR: Task exception was never retrieved
future: <Task finished name='Task-178' coro=<Binance._book.<locals>._concurrent_snapshot() done, defined at /home/grumpycat/dev/crypto-feed-handler/venv/lib/python3.9/site-packages/cryptofeed/exchanges/binance.py:366> exception=KeyError('BTC-USDT')>
Traceback (most recent call last):
  File "/home/grumpycat/dev/crypto-feed-handler/venv/lib/python3.9/site-packages/cryptofeed/exchanges/binance.py", line 368, in _concurrent_snapshot
    while len(self._book_buffer[std_pair]) > 0:
KeyError: 'BTC-USDT'
2021-10-02 02:04:42,571 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:04:42,572 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:04:48,580 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:04:48,582 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:04:54,589 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:04:57,362 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:05:02,368 : WARNING : BINANCE.ws.1: received no messages within timeout, restarting connection
2021-10-02 02:05:03,368 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:05:03,371 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:05:09,378 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:05:09,380 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:05:15,387 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:05:17,601 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:05:22,604 : WARNING : BINANCE.ws.1: received no messages within timeout, restarting connection
2021-10-02 02:05:23,604 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:05:23,606 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:05:29,612 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:05:29,613 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:05:35,619 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
2021-10-02 02:05:35,619 [MainThread|pid:1539813] [asyncio] ERROR: Task exception was never retrieved
future: <Task finished name='Task-196' coro=<Binance._book.<locals>._concurrent_snapshot() done, defined at /home/grumpycat/dev/crypto-feed-handler/venv/lib/python3.9/site-packages/cryptofeed/exchanges/binance.py:366> exception=KeyError('BTC-USDT')>
Traceback (most recent call last):
  File "/home/grumpycat/dev/crypto-feed-handler/venv/lib/python3.9/site-packages/cryptofeed/exchanges/binance.py", line 370, in _concurrent_snapshot
    await self._handle_book_msg(*book_args)
  File "/home/grumpycat/dev/crypto-feed-handler/venv/lib/python3.9/site-packages/cryptofeed/exchanges/binance.py", line 302, in _handle_book_msg
    skip_update = self._check_update_id(std_pair, msg)
  File "/home/grumpycat/dev/crypto-feed-handler/venv/lib/python3.9/site-packages/cryptofeed/exchanges/binance.py", line 266, in _check_update_id
    if self._l2_book[std_pair].delta is None and msg['u'] <= self.last_update_id[std_pair]:
KeyError: 'BTC-USDT'
2021-10-02 02:05:36,373 [MainThread|pid:1539813] [__main__] INFO: Sleeping for 5 seconds
2021-10-02 02:05:41,378 : WARNING : BINANCE.ws.1: received no messages within timeout, restarting connection
2021-10-02 02:05:42,378 [MainThread|pid:1539813] [__main__] INFO: Finished sleeping
```

You can see from this output the race condition can trigger `KeyError` in two different places:
Exceptions are raised either here:
https://github.com/bmoscon/cryptofeed/blob/57061595933c83dd88e5f9145c8ad3c01b98a255/cryptofeed/exchanges/binance.py#L368
or here:
https://github.com/bmoscon/cryptofeed/blob/57061595933c83dd88e5f9145c8ad3c01b98a255/cryptofeed/exchanges/binance.py#L266

**Root Cause:**
The flaw is a result of inadvertent concurrent use of `self._book_buffer` by multiple independent coroutines.

More specifically, the following code schedules a task for execution on event loop at a later time:
https://github.com/bmoscon/cryptofeed/blob/57061595933c83dd88e5f9145c8ad3c01b98a255/cryptofeed/exchanges/binance.py#L366-L373
This code assumes that no one else would interfere with `_book_buffer` - and specifically, that no one would reset it. Meanwhile, new messages will be processed by the feed and for whatever reason, cryptofeed may decide to reset the connection. In my example I've simulated a situation where `time.sleep` causes watcher to trigget timeout error and reset the feed - but there may be many other reasons on why the feed could be reset (e.g. an exception in another user handler, e.g. for trades).

When a connection is reset, it clears `_book_buffer`
https://github.com/bmoscon/cryptofeed/blob/57061595933c83dd88e5f9145c8ad3c01b98a255/cryptofeed/exchanges/binance.py#L151-L157

If this happens while our `_concurrent_snapshot` task (from an earlier connection/message) is still running (in my example, `asyncio.sleep` lets the other coroutines run and reset the connection/book buffer, while we're still processing snapshot), it would then fail when it tries to access  `_book_buffer` next time.

**Operating System:**
Linux

**Cryptofeed Version**
Current release, 2.0.1
P.S. I've not yet tried running it against the changes in https://github.com/bmoscon/cryptofeed/pull/606

cc @tristan-murfitt-elw @villekuosmanen

**Comment by bmoscon** [comment]
@jinusean - do you have any thoughts about this? I believe you were the person who contributed this part of the code?

**Comment by jinusean** [comment]
Hi @bmoscon and @nirvana-msu,

Please verify if https://github.com/bmoscon/cryptofeed/pull/673 is adequate.
