### ISSUE TITLE
Version 2.1.0 With RedisBook Backend, error: ('value is not a valid float'

### ISSUE THREAD

**Issue by xiandong79** [bmoscon/cryptofeed#707]
```
aioredis.exceptions.ResponseError: value is not a valid float
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<RedisZSetCallback.writer() done, defined at /home/ubuntu/.local/lib/python3.8/site-packages/cryptofeed/backends/redis.py:65> exception=ResponseError('Command # 1 (ZADD book-BINANCE_FUTURES-SAND-USDT-PERP NX None {"exchange":"BINANCE_FUTURES","symbol":"SAND-USDT-PERP","book":{"bid":{"2.66552":300},"ask":{"2.66713":669}},"timestamp":"None","receipt_timestamp":1635834684.871002}) of pipeline caused error: (\'value is not a valid float\',)')>
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/cryptofeed/backends/redis.py", line 76, in writer
    await pipe.execute()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/aioredis/client.py", line 4569, in execute
    return await execute(conn, stack, raise_on_error)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/aioredis/client.py", line 4512, in _execute_pipeline
    self.raise_first_error(commands, response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/aioredis/client.py", line 4519, in raise_first_error
    raise r
  File "/home/ubuntu/.local/lib/python3.8/site-packages/aioredis/client.py", line 4506, in _execute_pipeline
    await self.parse_response(connection, args[0], **options)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/aioredis/client.py", line 1080, in parse_response
    response = await connection.read_response()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/aioredis/connection.py", line 868, in read_response
    raise response from None
aioredis.exceptions.ResponseError: Command # 1 (ZADD book-BINANCE_FUTURES-SAND-USDT-PERP NX None {"exchange":"BINANCE_FUTURES","symbol":"SAND-USDT-PERP","book":{"bid":{"2.66552":300},"ask":{"2.66713":669}},"timestamp":"None","receipt_timestamp":1635834684.871002}) of pipeline caused error: ('value is not a valid float',)
```

**Comment by xiandong79** [comment]
```{'exchange': 'BINANCE_FUTURES', 'symbol': 'DOGE-USDT-PERP', 'book': {'bid': {0.27836: 1445.0}, 'ask': {0.27837: 570.0}}, 'timestamp': 'None', 'receipt_timestamp': 1635836548.3144925}
```

however in 
```
class RedisZSetCallback(RedisCallback):
    def __init__(self, host='127.0.0.1', port=6379, socket=None, key=None, numeric_type=float, score_key='timestamp', **kwargs):
```

**score_key='timestamp'** is used, which None, not acceptable in Redis

**Comment by xiandong79** [comment]
in exchanges/binance.py

```
 async def _snapshot(self, pair: str) -> None:
        await self.book_callback(L2_BOOK, self._l2_book[std_pair], time.time(), timestamp=None, raw=resp, sequence_number=self.last_update_id[std_pair])
```

for the _snapshot of Binance, the ` timestamp=None` happens.

**Comment by xiandong79** [comment]
```"redis": ["hiredis", "aioredis>=2.0.0"],```

is satisfied on my server.

**Comment by bmoscon** [comment]
yep, so your options here are to use a different key (like receipt timestamp) or define a wrapper for the callback that either ignores the snapshot, or puts in some default timestamp when the timestamp does not exist. An alternative would be to drop the snapshot and not send it as an update, but send message from the websocket as the snapshot (the first one that is valid post snapshot) and omit the delta there (delta=None means its a snapshot)

**Comment by xiandong79** [comment]
will this error fixed in cryptofeed?

**Comment by bmoscon** [comment]
fixed. now uses receipt timestamp to fill in all missing timestamps
