### ISSUE TITLE
websockets.exceptions.NegotiationError for Coinbase

### ISSUE THREAD

**Issue by JamesKBowler** [bmoscon/cryptofeed#709]
**Describe the bug**

Cryptofeed + Cryptostore has been running fine for the last few weeks, but just noticed the `COINBASE` process had crashed on the 4th October at about 19:05 GMT. Other exchanges are working ok.

Has `COINBASE` changed something?

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/cryptofeed/connection_handler.py", line 56, in _create_connection
    async with self.conn.connect() as connection:
  File "/usr/local/lib/python3.7/contextlib.py", line 170, in __aenter__
    return await self.gen.__anext__()
  File "/usr/local/lib/python3.7/site-packages/cryptofeed/connection.py", line 76, in connect
    await self._open()
  File "/usr/local/lib/python3.7/site-packages/cryptofeed/connection.py", line 204, in _open
    self.conn = await websockets.connect(self.address, **self.ws_kwargs)
  File "/usr/local/lib/python3.7/site-packages/websockets/legacy/client.py", line 649, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/site-packages/websockets/legacy/client.py", line 665, in __await_impl__
    extra_headers=protocol.extra_headers,
  File "/usr/local/lib/python3.7/site-packages/websockets/legacy/client.py", line 332, in handshake
    response_headers, available_extensions
  File "/usr/local/lib/python3.7/site-packages/websockets/legacy/client.py", line 221, in process_extensions
    f"Unsupported extension: "
websockets.exceptions.NegotiationError: Unsupported extension: name = permessage-deflate, params = [('server_no_context_takeover', None), ('client_no_context_takeover', None)]
```

**Operating System:**
 - ubuntu 20.04

**Cryptofeed Version**
- lastest versions pulled from github on `Oct 22 06:44`

**Comment by bmoscon** [comment]
this was fixed last week.
