### ISSUE TITLE
WARNING : PHEMEX.ws.1: received no messages within timeout, restarting connection -- Heartbeat Interval?

### ISSUE THREAD

**Issue by jwest75674** [bmoscon/cryptofeed#715]
**Describe the bug**
```
WARNING : PHEMEX.ws.1: received no messages within timeout, restarting connection
```
Websocket appears to timeout somewhere along the line. I am uncertain, but I beleive this note from the Phemex API Docs may be pertinent:
```
**Session Management**
 * Each client is required to actively send heartbeat (ping) message to Phemex data gateway ('DataGW' in short) with interval less than 30 seconds, otherwise DataGW will drop the connection. If a client sends a ping message, DataGW will reply with a pong message.
 * Clients can use WS built-in ping message or the application level ping message to DataGW as heartbeat. The heartbeat interval is recommended to be set as 5 seconds, and actively reconnect to DataGW if don't receive messages in 3 heartbeat intervals.
```

**To Reproduce**
1 ) start minimum viable datafeed + callback function that match this example:
```
async def candle(t, receipt_timestamp):
    print(t)
    return
```
2) wait ~15 minutes
3)
```
2021-11-21 04:53:24,502 : WARNING : PHEMEX.ws.1: encountered connection issue no close frame received or sent - reconnecting in 1.0 seconds...
Traceback (most recent call last):
  File "/home/josh/.local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 944, in transfer_data
    message = await self.read_message()
  File "/home/josh/.local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 1013, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/josh/.local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 1089, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/josh/.local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 1144, in read_frame
    frame = await Frame.read(
  File "/home/josh/.local/lib/python3.9/site-packages/websockets/legacy/framing.py", line 70, in read
    data = await reader(2)
  File "/usr/lib/python3.9/asyncio/streams.py", line 723, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/lib/python3.9/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/josh/.local/lib/python3.9/site-packages/cryptofeed/connection_handler.py", line 69, in _create_connection
    await self._handler(connection, self.handler)
  File "/home/josh/.local/lib/python3.9/site-packages/cryptofeed/connection_handler.py", line 115, in _handler
    async for message in connection.read():
  File "/home/josh/.local/lib/python3.9/site-packages/cryptofeed/connection.py", line 320, in read
    async for data in self.conn:
  File "/home/josh/.local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 481, in __aiter__
    yield await self.recv()
  File "/home/josh/.local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/home/josh/.local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 920, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent

```

**Expected behavior**
Avoid connection reset, such that apps can run reliably.

**Operating System:**
Ubuntu, Python 3.9

**Cryptofeed Version**
Installed most recent build from source.

**Comment by bmoscon** [comment]
that isnt a reproducible example. Please provide one and I'll see if I can reproduce it

**Comment by jwest75674** [comment]
Here you go!
```
from cryptofeed import FeedHandler
from cryptofeed.exchanges import Phemex
from cryptofeed.defines import TRADES, L2_BOOK, CANDLES, PERPETUAL, BID, ASK, TICKER
from cryptofeed.symbols import Symbol


async def trade(t, receipt_timestamp):
    print(f"{receipt_timestamp}: {t}")

async def candle(t, receipt_timestamp):
    print(f"{receipt_timestamp}: {t}") 

def start_data_feeds(interval="1m"):
    feed_handler = FeedHandler(config="/mnt/lightningdata/python/jwestpython/config.yaml")
    """
    log:
        filename: feedhandler.log
        level: WARNING

    # Enable UVLoop (if not installed, will not cause errors)
    uvloop: True

    # Secrets for exchanges
    phemex:
        key_id: {{redacted}}
        key_secret: {{redacted}}
    """
    phemex_callbacks = {CANDLES: candle, TRADES: trade}
    feed_handler.add_feed(
        Phemex(symbols=[Symbol('CHZ', 'USD', type=PERPETUAL)],
               channels=[CANDLES, TRADES], callbacks=phemex_callbacks, candle_interval=interval))
    feed_handler.run()

    print("CLOSING FEED HANDLER")
    feed_handler.close()

start_data_feeds()
```
--->
```
1637672658.7259376: exchange: PHEMEX symbol: CHZ-USD-PERP start: 1637646420.0 stop: 1637646480.0 interval: 1m trades: None open: 0.440000000000000002220446049250313080847263336181640625 close: 0.440000000000000002220446049250313080847263336181640625 high: 0.440000000000000002220446049250313080847263336181640625 low: 0.440000000000000002220446049250313080847263336181640625 volume: 2552000 closed: False timestamp: None
1637672658.7259376: exchange: PHEMEX symbol: CHZ-USD-PERP start: 1637646360.0 stop: 1637646420.0 interval: 1m trades: None open: 0.44030000000000002469136006766348145902156829833984375 close: 0.44059999999999999165112285481882281601428985595703125 high: 0.44059999999999999165112285481882281601428985595703125 low: 0.44030000000000002469136006766348145902156829833984375 volume: 484360 closed: False timestamp: None
1637672658.7259376: exchange: PHEMEX symbol: CHZ-USD-PERP start: 1637646300.0 stop: 1637646360.0 interval: 1m trades: None open: 0.44040000000000001367794766338192857801914215087890625 close: 0.44040000000000001367794766338192857801914215087890625 high: 0.44040000000000001367794766338192857801914215087890625 low: 0.44040000000000001367794766338192857801914215087890625 volume: 103185720 closed: False timestamp: None
[........]
1637672928.1563802: exchange: PHEMEX symbol: CHZ-USD-PERP start: 1637672820.0 stop: 1637672880.0 interval: 1m trades: None open: 0.42849999999999999200639422269887290894985198974609375 close: 0.428700000000000025490720645393594168126583099365234375 high: 0.428700000000000025490720645393594168126583099365234375 low: 0.42849999999999999200639422269887290894985198974609375 volume: 20398120 closed: False timestamp: None
1637673002.76559: exchange: PHEMEX symbol: CHZ-USD-PERP side: buy amount: 2502 price: 0.42849999999999999200639422269887290894985198974609375 id: None type: None timestamp: 1637673002.5966177
1637673002.76559: exchange: PHEMEX symbol: CHZ-USD-PERP side: buy amount: 1415 price: 0.42849999999999999200639422269887290894985198974609375 id: None type: None timestamp: 1637673002.5942101
1637673002.7673542: exchange: PHEMEX symbol: CHZ-USD-PERP start: 1637673000.0 stop: 1637673060.0 interval: 1m trades: None open: 0.42849999999999999200639422269887290894985198974609375 close: 0.42849999999999999200639422269887290894985198974609375 high: 0.42849999999999999200639422269887290894985198974609375 low: 0.42849999999999999200639422269887290894985198974609375 volume: 167843450 closed: False timestamp: None
1637673002.7673542: exchange: PHEMEX symbol: CHZ-USD-PERP start: 1637672940.0 stop: 1637673000.0 interval: 1m trades: None open: 0.428099999999999980548892608567257411777973175048828125 close: 0.428099999999999980548892608567257411777973175048828125 high: 0.428099999999999980548892608567257411777973175048828125 low: 0.428099999999999980548892608567257411777973175048828125 volume: 0 closed: False timestamp: None
1637673002.7673542: exchange: PHEMEX symbol: CHZ-USD-PERP start: 1637672880.0 stop: 1637672940.0 interval: 1m trades: None open: 0.428099999999999980548892608567257411777973175048828125 close: 0.428099999999999980548892608567257411777973175048828125 high: 0.428099999999999980548892608567257411777973175048828125 low: 0.428099999999999980548892608567257411777973175048828125 volume: 237124590 closed: False timestamp: None
**2021-11-23 06:12:18,745 : WARNING : PHEMEX.ws.1: received no messages within timeout, restarting connection**
```

**Comment by bmoscon** [comment]
@jwest75674 the trading pair you have chosen is very low volume, so the feedhandler considers the data feed to be dead and restarts it. If you are going to be subscribing to low volume feeds like this, increase the timeout (its a kwarg on the exchange/feed object). The default is 2 mins. If you change your example to BTC-USD-PERP it has no timeouts (at least not when I tested it)
