### ISSUE TITLE
FTX.ws error on v1.9.3

### ISSUE THREAD

**Issue by gigitalz** [bmoscon/cryptofeed#716]
**Describe the bug**
I get this trace:

```
2021-11-21 14:47:27,892 : WARNING : FTX.ws.14: encountered connection issue server rejected WebSocket connection: HTTP 404 - reconnecting in 64.0 seconds...
Traceback (most recent call last):
  File "cryptofeed\connection_handler.py", line 58, in _create_connection
  File "contextlib.py", line 175, in __aenter__
  File "cryptofeed\connection.py", line 114, in connect
  File "cryptofeed\connection.py", line 287, in _open
  File "websockets\legacy\client.py", line 629, in __await_impl__
  File "websockets\legacy\client.py", line 388, in handshake
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 404
```

**To Reproduce**
Add open interest feed to btc usd perp pair

```
    f.add_feed(FTX(symbols=['BTC-USD-PERP'],
                channels=[OPEN_INTEREST],
                callbacks={OPEN_INTEREST: OpenInterestSocket(addr, port=port)}))       
```

**Operating System:**
 - Windows 10 Pro

**Cryptofeed Version**
- Intalled from packages v1.9.3

**Comment by bmoscon** [comment]
that version is no longer supported. try with the later versions, that has been fixed
