### ISSUE TITLE
Could not build wheels for cryptofeed - How do I fix this?

### ISSUE THREAD

**Issue by codeconfid** [bmoscon/cryptofeed#735]
What do I need to do to successfully install cryptofeed?

```
C:\Users\Cos\AppData\Local\Programs\Python\Python39\Scripts>python -m pip --version
pip 21.3.1 from C:\Users\Cos\AppData\Local\Programs\Python\Python39\lib\site-packages\pip (python 3.9)
C:\Users\Cos\AppData\Local\Programs\Python\Python39\Scripts>pip install cryptofeed
Collecting cryptofeed
  Using cached cryptofeed-2.1.1.tar.gz (346 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting requests>=2.18.4
  Using cached requests-2.26.0-py2.py3-none-any.whl (62 kB)
Collecting order-book>=0.4.1
  Using cached order_book-0.4.1.tar.gz (13 kB)
  Preparing metadata (setup.py) ... done
Collecting yapic.json>=1.6.3
  Using cached yapic.json-1.7.2-cp39-cp39-win_amd64.whl (66 kB)
Collecting cchardet
  Using cached cchardet-2.1.7-cp39-cp39-win_amd64.whl (115 kB)
Collecting aiohttp==3.8.1
  Using cached aiohttp-3.8.1-cp39-cp39-win_amd64.whl (554 kB)
Collecting aiodns>=1.1
  Using cached aiodns-3.0.0-py3-none-any.whl (5.0 kB)
Collecting websockets>=10.0
  Using cached websockets-10.1-cp39-cp39-win_amd64.whl (97 kB)
Collecting aiofile>=2.0.0
  Using cached aiofile-3.7.2-py3-none-any.whl (19 kB)
Collecting pyyaml
  Using cached PyYAML-6.0-cp39-cp39-win_amd64.whl (151 kB)
Collecting frozenlist>=1.1.1
  Using cached frozenlist-1.2.0-cp39-cp39-win_amd64.whl (83 kB)
Collecting yarl<2.0,>=1.0
  Using cached yarl-1.7.2-cp39-cp39-win_amd64.whl (122 kB)
Collecting multidict<7.0,>=4.5
  Using cached multidict-5.2.0-cp39-cp39-win_amd64.whl (45 kB)
Collecting async-timeout<5.0,>=4.0.0a3
  Using cached async_timeout-4.0.1-py3-none-any.whl (5.7 kB)
Collecting attrs>=17.3.0
  Using cached attrs-21.2.0-py2.py3-none-any.whl (53 kB)
Collecting charset-normalizer<3.0,>=2.0
  Using cached charset_normalizer-2.0.9-py3-none-any.whl (39 kB)
Collecting aiosignal>=1.1.2
  Using cached aiosignal-1.2.0-py3-none-any.whl (8.2 kB)
Collecting pycares>=4.0.0
  Using cached pycares-4.1.2-cp39-cp39-win_amd64.whl (83 kB)
Collecting caio~=0.9.0
  Using cached caio-0.9.3-py3-none-any.whl (18 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.7-py2.py3-none-any.whl (138 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Collecting typing-extensions>=3.6.5
  Using cached typing_extensions-4.0.1-py3-none-any.whl (22 kB)
Collecting cffi>=1.5.0
  Using cached cffi-1.15.0-cp39-cp39-win_amd64.whl (180 kB)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Using legacy 'setup.py install' for order-book, since package 'wheel' is not installed.
Building wheels for collected packages: cryptofeed
  Building wheel for cryptofeed (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Cos\AppData\Local\Programs\Python\Python39\python.exe' 'C:\Users\Cos\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\Cos\AppData\Local\Temp\tmp3cv3n5xn'
       cwd: C:\Users\Cos\AppData\Local\Temp\pip-install-ix2rahqf\cryptofeed_0f4c4c250f654cfdb9f47995aed8038b
  Complete output (112 lines):
  [1/1] Cythonizing cryptofeed/types.pyx
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.9
  creating build\lib.win-amd64-3.9\cryptofeed
  copying cryptofeed\callback.py -> build\lib.win-amd64-3.9\cryptofeed
  copying cryptofeed\config.py -> build\lib.win-amd64-3.9\cryptofeed
  copying cryptofeed\connection.py -> build\lib.win-amd64-3.9\cryptofeed
  copying cryptofeed\connection_handler.py -> build\lib.win-amd64-3.9\cryptofeed
  copying cryptofeed\defines.py -> build\lib.win-amd64-3.9\cryptofeed
  copying cryptofeed\exceptions.py -> build\lib.win-amd64-3.9\cryptofeed
  copying cryptofeed\exchange.py -> build\lib.win-amd64-3.9\cryptofeed
  copying cryptofeed\feed.py -> build\lib.win-amd64-3.9\cryptofeed
  copying cryptofeed\feedhandler.py -> build\lib.win-amd64-3.9\cryptofeed
  copying cryptofeed\log.py -> build\lib.win-amd64-3.9\cryptofeed
  copying cryptofeed\nbbo.py -> build\lib.win-amd64-3.9\cryptofeed
  copying cryptofeed\raw_data_collection.py -> build\lib.win-amd64-3.9\cryptofeed
  copying cryptofeed\symbols.py -> build\lib.win-amd64-3.9\cryptofeed
  copying cryptofeed\__init__.py -> build\lib.win-amd64-3.9\cryptofeed
  creating build\lib.win-amd64-3.9\cryptofeed\auth
  copying cryptofeed\auth\okcoin.py -> build\lib.win-amd64-3.9\cryptofeed\auth
  copying cryptofeed\auth\__init__.py -> build\lib.win-amd64-3.9\cryptofeed\auth
  creating build\lib.win-amd64-3.9\cryptofeed\backends
  copying cryptofeed\backends\aggregate.py -> build\lib.win-amd64-3.9\cryptofeed\backends
  copying cryptofeed\backends\arctic.py -> build\lib.win-amd64-3.9\cryptofeed\backends
  copying cryptofeed\backends\backend.py -> build\lib.win-amd64-3.9\cryptofeed\backends
  copying cryptofeed\backends\elastic.py -> build\lib.win-amd64-3.9\cryptofeed\backends
  copying cryptofeed\backends\gcppubsub.py -> build\lib.win-amd64-3.9\cryptofeed\backends
  copying cryptofeed\backends\http.py -> build\lib.win-amd64-3.9\cryptofeed\backends
  copying cryptofeed\backends\influxdb.py -> build\lib.win-amd64-3.9\cryptofeed\backends
  copying cryptofeed\backends\kafka.py -> build\lib.win-amd64-3.9\cryptofeed\backends
  copying cryptofeed\backends\mongo.py -> build\lib.win-amd64-3.9\cryptofeed\backends
  copying cryptofeed\backends\postgres.py -> build\lib.win-amd64-3.9\cryptofeed\backends
  copying cryptofeed\backends\rabbitmq.py -> build\lib.win-amd64-3.9\cryptofeed\backends
  copying cryptofeed\backends\redis.py -> build\lib.win-amd64-3.9\cryptofeed\backends
  copying cryptofeed\backends\socket.py -> build\lib.win-amd64-3.9\cryptofeed\backends
  copying cryptofeed\backends\victoriametrics.py -> build\lib.win-amd64-3.9\cryptofeed\backends
  copying cryptofeed\backends\zmq.py -> build\lib.win-amd64-3.9\cryptofeed\backends
  copying cryptofeed\backends\_util.py -> build\lib.win-amd64-3.9\cryptofeed\backends
  copying cryptofeed\backends\__init__.py -> build\lib.win-amd64-3.9\cryptofeed\backends
  creating build\lib.win-amd64-3.9\cryptofeed\exchanges
  copying cryptofeed\exchanges\ascendex.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges
  copying cryptofeed\exchanges\bequant.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges
  copying cryptofeed\exchanges\binance.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges
  copying cryptofeed\exchanges\binance_delivery.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges
  copying cryptofeed\exchanges\binance_futures.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges
  copying cryptofeed\exchanges\binance_us.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges
  copying cryptofeed\exchanges\bitfinex.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges
  copying cryptofeed\exchanges\bitflyer.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges
  copying cryptofeed\exchanges\bithumb.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges
  copying cryptofeed\exchanges\bitmex.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges
  copying cryptofeed\exchanges\bitstamp.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges
  copying cryptofeed\exchanges\bittrex.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges
  copying cryptofeed\exchanges\blockchain.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges
  copying cryptofeed\exchanges\bybit.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges
  copying cryptofeed\exchanges\coinbase.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges
  copying cryptofeed\exchanges\cryptodotcom.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges
  copying cryptofeed\exchanges\delta.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges
  copying cryptofeed\exchanges\deribit.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges
  copying cryptofeed\exchanges\dydx.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges
  copying cryptofeed\exchanges\exx.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges
  copying cryptofeed\exchanges\fmfw.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges
  copying cryptofeed\exchanges\ftx.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges
  copying cryptofeed\exchanges\ftx_us.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges
  copying cryptofeed\exchanges\gateio.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges
  copying cryptofeed\exchanges\gemini.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges
  copying cryptofeed\exchanges\hitbtc.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges
  copying cryptofeed\exchanges\huobi.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges
  copying cryptofeed\exchanges\huobi_dm.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges
  copying cryptofeed\exchanges\huobi_swap.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges
  copying cryptofeed\exchanges\kraken.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges
  copying cryptofeed\exchanges\kraken_futures.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges
  copying cryptofeed\exchanges\kucoin.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges
  copying cryptofeed\exchanges\okcoin.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges
  copying cryptofeed\exchanges\okex.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges
  copying cryptofeed\exchanges\phemex.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges
  copying cryptofeed\exchanges\poloniex.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges
  copying cryptofeed\exchanges\probit.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges
  copying cryptofeed\exchanges\upbit.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges
  copying cryptofeed\exchanges\__init__.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges
  creating build\lib.win-amd64-3.9\cryptofeed\util
  copying cryptofeed\util\book.py -> build\lib.win-amd64-3.9\cryptofeed\util
  copying cryptofeed\util\perf.py -> build\lib.win-amd64-3.9\cryptofeed\util
  copying cryptofeed\util\split.py -> build\lib.win-amd64-3.9\cryptofeed\util
  copying cryptofeed\util\time.py -> build\lib.win-amd64-3.9\cryptofeed\util
  copying cryptofeed\util\__init__.py -> build\lib.win-amd64-3.9\cryptofeed\util
  creating build\lib.win-amd64-3.9\cryptofeed\exchanges\mixins
  copying cryptofeed\exchanges\mixins\binance_rest.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges\mixins
  copying cryptofeed\exchanges\mixins\bitfinex_rest.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges\mixins
  copying cryptofeed\exchanges\mixins\bitmex_rest.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges\mixins
  copying cryptofeed\exchanges\mixins\bitstamp_rest.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges\mixins
  copying cryptofeed\exchanges\mixins\coinbase_rest.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges\mixins
  copying cryptofeed\exchanges\mixins\deribit_rest.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges\mixins
  copying cryptofeed\exchanges\mixins\dydx_rest.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges\mixins
  copying cryptofeed\exchanges\mixins\ftx_rest.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges\mixins
  copying cryptofeed\exchanges\mixins\ftx_rest_us.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges\mixins
  copying cryptofeed\exchanges\mixins\gemini_rest.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges\mixins
  copying cryptofeed\exchanges\mixins\kraken_rest.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges\mixins
  copying cryptofeed\exchanges\mixins\poloniex_rest.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges\mixins
  copying cryptofeed\exchanges\mixins\upbit_rest.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges\mixins
  copying cryptofeed\exchanges\mixins\__init__.py -> build\lib.win-amd64-3.9\cryptofeed\exchanges\mixins
  running build_ext
  building 'cryptofeed.types' extension
  creating build\temp.win-amd64-3.9
  creating build\temp.win-amd64-3.9\Release
  creating build\temp.win-amd64-3.9\Release\cryptofeed
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DCYTHON_WITHOUT_ASSERTIONS -IC:\Users\Cos\AppData\Local\Programs\Python\Python39\include -IC:\Users\Cos\AppData\Local\Programs\Python\Python39\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include /Tccryptofeed/types.c /Fobuild\temp.win-amd64-3.9\Release\cryptofeed/types.obj /O2
  types.c
  C:\Users\Cos\AppData\Local\Programs\Python\Python39\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  ----------------------------------------
  ERROR: Failed building wheel for cryptofeed
Failed to build cryptofeed
ERROR: Could not build wheels for cryptofeed, which is required to install pyproject.toml-based projects
C:\Users\Cos\AppData\Local\Programs\Python\Python39\Scripts>python --version
Python 3.9.9
```

**Comment by codeconfid** [comment]
I see that uvloop is a requirement for cryptofeed, but windows does not support uvloop. How do I work around this to use cryptofeed on windows? 

```
I see that uvloop is a requirement for cryptofeed, but windows does not support uvloop. How do I work around this to use cryptofeed on windows? 

```
C:\Users\COS\Dropbox\Projects>pip install uvloop==0.14.0
Collecting uvloop==0.14.0
  Using cached uvloop-0.14.0.tar.gz (2.0 MB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\COS\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\COS\\AppData\\Local\\Temp\\pip-install-ii_uzqhn\\uvloop_49c38bb331bc44e4bac14767f15a7828\\setup.py'"'"'; __file__='"'"'C:\\Users\\COS\\AppData\\Local\\Temp\\pip-install-ii_uzqhn\\uvloop_49c38bb331bc44e4bac14767f15a7828\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Joselyn\AppData\Local\Temp\pip-pip-egg-info-neo6j_kt'
       cwd: C:\Users\COS\AppData\Local\Temp\pip-install-ii_uzqhn\uvloop_49c38bb331bc44e4bac14767f15a7828\
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\COS\AppData\Local\Temp\pip-install-ii_uzqhn\uvloop_49c38bb331bc44e4bac14767f15a7828\setup.py", line 15, in <module>
      raise RuntimeError('uvloop does not support Windows at the moment')
  RuntimeError: uvloop does not support Windows at the moment
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/84/2e/462e7a25b787d2b40cf6c9864a9e702f358349fc9cfb77e83c38acb73048/uvloop-0.14.0.tar.gz#sha256=123ac9c0c7dd71464f58f1b4ee0bbd81285d96cdda8bc3519281b8973e3a461e (from https://pypi.org/simple/uvloop/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement uvloop==0.14.0 (from versions: 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.5, 0.4.6, 0.4.7, 0.4.8, 0.4.9, 0.4.10, 0.4.11, 0.4.12, 0.4.13, 0.4.14, 0.4.15, 0.4.16, 0.4.17, 0.4.18, 0.4.19, 0.4.20, 0.4.21, 0.4.22, 0.4.23, 0.4.24, 0.4.25, 0.4.26, 0.4.27, 0.4.28, 0.4.29, 0.4.30, 0.4.31, 0.4.32, 0.4.33, 0.4.34, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.6.0, 0.6.5, 0.6.6, 0.6.7, 0.6.8, 0.7.0, 0.7.1, 0.7.2, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.11.0, 0.11.1, 0.11.2, 0.11.3, 0.12.0rc1, 0.12.0, 0.12.1, 0.12.2, 0.13.0rc1, 0.13.0, 0.14.0rc1, 0.14.0rc2, 0.14.0, 0.15.0, 0.15.1, 0.15.2, 0.15.3, 0.16.0)
ERROR: No matching distribution found for uvloop==0.14.0
```
```

**Comment by bmoscon** [comment]
windows is not supported, and uvloop is not required. if you can get it to build on windows, I'll take a PR, but only linux and macos are supported. Likely uvloop just needs a flag indicating it only needs to be installed on specific operating systems.
