### ISSUE TITLE
Unable to obtain trades of `BTC-PERP` when using FTX

### ISSUE THREAD

**Issue by AlgoQ** [bmoscon/cryptofeed#765]
**Describe the bug**
Unable to obtain trades of `BTC-PERP` when using FTX. I was able to fetch the spot market `BTC-USD` so I guess there is an issue with the symbol declaration. 

**To Reproduce**
```python
from cryptofeed import FeedHandler
from cryptofeed.exchanges import FTX
from cryptofeed.defines import TRADES
from cryptofeed.symbols import Symbol
from cryptofeed.defines import PERPETUAL

symbol = Symbol('BTC', 'USD', type=PERPETUAL)

async def dataHandler(**kwargs):
    print(kwargs)

def main():
    f = FeedHandler()

    f.add_feed(FTX(symbols=symbol, channels=[TRADES], callbacks={TRADES: dataHandler}))
    f.run()

if __name__ == '__main__':
    main()
```

**Error**
```
Traceback (most recent call last):
  File "mainCryptofeed.py", line 19, in <module>
    main()
  File "mainCryptofeed.py", line 15, in main
    f.add_feed(FTX(symbols=symbol, channels=[TRADES], callbacks={TRADES: dataHandler}))
  File "/home/kobe/anaconda3/lib/python3.8/site-packages/cryptofeed/exchanges/ftx.py", line 92, in __init__
    super().__init__(**kwargs)
  File "/home/kobe/anaconda3/lib/python3.8/site-packages/cryptofeed/feed.py", line 115, in __init__
    [self._feed_config[channel].extend(symbols) for channel in channels]
  File "/home/kobe/anaconda3/lib/python3.8/site-packages/cryptofeed/feed.py", line 115, in <listcomp>
    [self._feed_config[channel].extend(symbols) for channel in channels]
TypeError: 'Symbol' object is not iterable
```

**Operating System:**
Ubuntu

**Cryptofeed Version**
Latest

**Comment by bmoscon** [comment]
@AlgoQ the symbols kwarg takes a list of symbols, you have provided a single symbol

**Comment by AlgoQ** [comment]
Wow stupid mistake, thanks!

**Comment by bmoscon** [comment]
no problem :)
