### ISSUE TITLE
Arctic backend won't write trade data

### ISSUE THREAD

**Issue by KaneM2** [bmoscon/cryptofeed#783]
**Describe the bug**
Binance trade data won't write to Arctic db

**To Reproduce**

```
from decimal import Decimal

from cryptofeed import FeedHandler
from cryptofeed.defines import TRADES
from cryptofeed.exchanges import (Binance)
from cryptofeed.backends.arctic import TradeArctic



async def trade(t, receipt_timestamp):
    assert isinstance(t.timestamp, float)
    assert isinstance(t.side, str)
    assert isinstance(t.amount, Decimal)
    assert isinstance(t.price, Decimal)
    assert isinstance(t.exchange, str)
    print(f"Trade received at {receipt_timestamp}: {t}")


def main():
    config = {'log': {'filename': 'demo.log', 'level': 'DEBUG', 'disabled': False}}
    f = FeedHandler(config=config)
    pairs = Binance.symbols()[:1]
    f.add_feed(Binance(symbols=pairs, channels=[TRADES], callbacks={ TRADES: trade,  TRADES: TradeArctic('cryptofeed-test')}))
    f.run()


if __name__ == '__main__':
    main()
```

* Provide any tracebacks, if applicable
```
(py3) michael@DESKTOP-ROU6JE7:~/crypto$ /home/michael/anaconda3/envs/py3/bin/python /home/michael/crypto/test_feed.py
/home/michael/anaconda3/envs/py3/lib/python3.7/site-packages/arctic/store/_pandas_ndarray_store.py:8: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  from pandas import Panel
2022-02-15 23:25:32,720 : INFO : Config: use dict containing the following main keys: log
2022-02-15 23:25:32,720 : DEBUG : BINANCE: reading symbol information from https://api.binance.com/api/v3/exchangeInfo
2022-02-15 23:25:32,720 : DEBUG : HTTPSync: requesting data from https://api.binance.com/api/v3/exchangeInfo
2022-02-15 23:25:33,207 : DEBUG : BINANCE.ws.1: connecting to wss://stream.binance.com:9443/stream?streams=ethbtc@aggTrade
2022-02-15 23:25:43,920 : INFO : BINANCE.ws.1: closed connection 'WebSocketClientProtocol'
2022-02-15 23:25:43,920 : ERROR : BINANCE.ws.1: encountered an exception, reconnecting in 1.0 seconds
Traceback (most recent call last):
  File "/home/michael/anaconda3/envs/py3/lib/python3.7/site-packages/cryptofeed/connection_handler.py", line 69, in _create_connection
    await self._handler(connection, self.handler)
  File "/home/michael/anaconda3/envs/py3/lib/python3.7/site-packages/cryptofeed/connection_handler.py", line 119, in _handler
    await handler(message, connection, self.conn.last_message)
  File "/home/michael/anaconda3/envs/py3/lib/python3.7/site-packages/cryptofeed/exchanges/binance.py", line 521, in message_handler
    await self._trade(msg, timestamp)
  File "/home/michael/anaconda3/envs/py3/lib/python3.7/site-packages/cryptofeed/exchanges/binance.py", line 198, in _trade
    await self.callback(TRADES, t, timestamp)
  File "/home/michael/anaconda3/envs/py3/lib/python3.7/site-packages/cryptofeed/feed.py", line 251, in callback
    await cb(obj, receipt_timestamp)
  File "/home/michael/anaconda3/envs/py3/lib/python3.7/site-packages/cryptofeed/backends/backend.py", line 51, in __call__
    await self.write(data)
  File "/home/michael/anaconda3/envs/py3/lib/python3.7/site-packages/cryptofeed/backends/arctic.py", line 50, in write
    self.lib.append(self.key, df, upsert=True)
  File "/home/michael/anaconda3/envs/py3/lib/python3.7/site-packages/arctic/decorators.py", line 50, in f_retry
    return f(*args, **kwargs)
  File "/home/michael/anaconda3/envs/py3/lib/python3.7/site-packages/arctic/store/version_store.py", line 592, in append
    previous_version, dirty_append=dirty_append, **kwargs)
  File "/home/michael/anaconda3/envs/py3/lib/python3.7/site-packages/arctic/store/_pandas_ndarray_store.py", line 203, in append
    super(PandasDataFrameStore, self).append(arctic_lib, version, symbol, item, previous_version, dtype=md, **kwargs)
  File "/home/michael/anaconda3/envs/py3/lib/python3.7/site-packages/arctic/store/_ndarray_store.py", line 407, in append
    dtype = self._promote_types(dtype, previous_version['dtype'])
  File "/home/michael/anaconda3/envs/py3/lib/python3.7/site-packages/arctic/store/_ndarray_store.py", line 387, in _promote_types
    rtn = _promote_struct_dtypes(dtype, prev_dtype)
  File "/home/michael/anaconda3/envs/py3/lib/python3.7/site-packages/arctic/store/_ndarray_store.py", line 29, in _promote_struct_dtypes
    raise Exception("Removing columns from dtype not handled")
Exception: Removing columns from dtype not handled
```

**Expected behavior**
Data to write to Arctic

**Operating System:**
 -  Linux

**Cryptofeed Version**
- cryptofeed @ git+https://github.com/bmoscon/cryptofeed.git@5a1b206b2e1f9039d510eefd63b37bde25017fe1

**Comment by bmoscon** [comment]
Works for me using latest cryptofeed + latest arctic. The error makes me think you have old data in arctic and are trying to write new data in it that is formatted differently, but cant say for sure without more info.
