### ISSUE TITLE
Fills and order_info subsriptions on FTX require at least one specified symbol

### ISSUE THREAD

**Issue by aceffer** [bmoscon/cryptofeed#798]
**Describe the bug**
Fills and order_info subsriptions on FTX require at least one specified symbol. This should work without symbol specification.

**To Reproduce**
```
config = {'log': {'filename': 'test.log', 'level': 'DEBUG', 'disabled': False}}
f = FeedHandler(config=config)

f.add_feed(FTX(config=config,
               channels=[FILLS, ORDER_INFO],
               callbacks={FILLS: fill, ORDER_INFO: order}))

f.run()
```
resulted in: 
```
PyDev console: starting.
Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)] on win32
runfile('C:/Users/Attila/Documents/GitHub/arbi/test/web_socket/test_funding_ftx.py', wdir='C:/Users/Attila/Documents/GitHub/arbi/test/web_socket')
2022-02-27 10:26:46,161 : INFO : Config: use dict containing the following main keys: log, ftx
2022-02-27 10:26:46,161 : DEBUG : FTX: reading symbol information from https://ftx.com/api/markets
2022-02-27 10:26:46,161 : DEBUG : HTTPSync: requesting data from https://ftx.com/api/markets
Process finished with exit code 0
```
without even trying to subscribe to order info and fill events.

However, when I specify at least one valid symbol:
```
config = {'log': {'filename': 'test.log', 'level': 'DEBUG', 'disabled': False}}
f = FeedHandler(config=config)

f.add_feed(FTX(config=config, symbols=['BTC-USD-PERPETUAL'],
               channels=[FILLS, ORDER_INFO],
               callbacks={FILLS: fill, ORDER_INFO: order}))

f.run()
```
it will try to subscribe to these events:
```
PyDev console: starting.
Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)] on win32
runfile('C:/Users/Attila/Documents/GitHub/arbi/test/web_socket/test_funding_ftx.py', wdir='C:/Users/Attila/Documents/GitHub/arbi/test/web_socket')
2022-02-27 10:46:54,820 : INFO : Config: use dict containing the following main keys: log, ftxx
2022-02-27 10:46:54,820 : DEBUG : FTX: reading symbol information from https://ftx.com/api/markets
2022-02-27 10:46:54,820 : DEBUG : HTTPSync: requesting data from https://ftx.com/api/markets
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm 2020.2.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2020.2.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/Attila/Documents/GitHub/arbi/test/web_socket/test_funding_ftx.py", line 29, in <module>
    f.add_feed(FTX(config=config, symbols=['BTC-USD-PERPETUAL'],
  File "C:\Users\Attila\Documents\GitHub\venv38\lib\site-packages\cryptofeed\feed.py", line 106, in __init__
    raise ValueError("Authenticated channel subscribed to, but no auth keys provided")
ValueError: Authenticated channel subscribed to, but no auth keys provided
```
**Expected behavior**
This should work without symbol specification.

**Screenshots**

**Operating System:**
 - Windows 10

**Cryptofeed Version**
- 2.2.0

**Comment by bmoscon** [comment]
fixed on master

**Comment by bmoscon** [comment]
note you have to use a subscription dict though, you cannot use channels without symbols, and there is no way to specify an empty set of symbols currently. so do: `subscription={ORDER_INFO: [], FILLS: []}`
