### ISSUE TITLE
issue with latest cryptofeed codebase

### ISSUE THREAD

**Issue by himanshu24x77** [bmoscon/cryptofeed#854]
1. upgraded to latest cryptofeed, getting below error
2. using python3.6 
3. when i try to run example: python3.6 demo_ftx.py

Traceback (most recent call last):
  File "demo_ftx.py", line 12, in <module>
    from cryptofeed import FeedHandler
  File "/home/jaimatadi/Downloads/cryptofeed-master/cryptofeed/__init__.py", line 7, in <module>
    from cryptofeed.feedhandler import FeedHandler
  File "/home/jaimatadi/Downloads/cryptofeed-master/cryptofeed/feedhandler.py", line 26, in <module>
    from cryptofeed.feed import Feed
  File "/home/jaimatadi/Downloads/cryptofeed-master/cryptofeed/feed.py", line 20, in <module>
    from cryptofeed.types import OrderBook
ModuleNotFoundError: No module named 'cryptofeed.types'

after searching, i added below lines in demo_ftx.py:

import pyximport
pyximport.install()

but then got different error:

Traceback (most recent call last):
  File "/home/jaimatadi/.local/lib/python3.6/site-packages/pyximport/pyximport.py", line 216, in load_module
    mod = imp.load_dynamic(name, so_path)
  File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: dynamic module does not define module export function (PyInit_types)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo_ftx.py", line 12, in <module>
    from cryptofeed import FeedHandler
  File "/home/jaimatadi/Downloads/cryptofeed-master/cryptofeed/__init__.py", line 7, in <module>
    from cryptofeed.feedhandler import FeedHandler
  File "/home/jaimatadi/Downloads/cryptofeed-master/cryptofeed/feedhandler.py", line 26, in <module>
    from cryptofeed.feed import Feed
  File "/home/jaimatadi/Downloads/cryptofeed-master/cryptofeed/feed.py", line 20, in <module>
    from cryptofeed.types import OrderBook
  File "/home/jaimatadi/.local/lib/python3.6/site-packages/pyximport/pyximport.py", line 462, in load_module
    language_level=self.language_level)
  File "/home/jaimatadi/.local/lib/python3.6/site-packages/pyximport/pyximport.py", line 231, in load_module
    raise exc.with_traceback(tb)
  File "/home/jaimatadi/.local/lib/python3.6/site-packages/pyximport/pyximport.py", line 216, in load_module
    mod = imp.load_dynamic(name, so_path)
  File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: Building module cryptofeed.types failed: ['ImportError: dynamic module does not define module export function (PyInit_types)\n']

Pls. suggest.

**Comment by bmoscon** [comment]
python 3.6 is not supported. 3.8+ only
