### ISSUE TITLE
deribit L2_BOOK raising ValueError Authenticated channel

### ISSUE THREAD

**Issue by docek** [bmoscon/cryptofeed#866]
**Describe the bug**
I am trying to subscribe to Deribit L2_BOOK channel (public data) and Cryptofeed tels me that the channel is authenticated and needs auth keys.

**To Reproduce**
f = FeedHandler()
f.add_feed(Deribit(symbols=['BTC-USD-PERP'], channels=[L2_BOOK], callbacks={L2_BOOK: book}))
f.run()

**Expected behavior**
As with other exchanges I would expect to receive L2_DATA

**Screenshots**
Traceback (most recent call last):
  File "/home/docek/PycharmProjects/hb-core/noapp/option_price.py", line 28, in <module>
    main()
  File "/home/docek/PycharmProjects/hb-core/noapp/option_price.py", line 22, in main
    f.add_feed(Deribit(symbols=SYMBOLS, channels=[L2_BOOK], callbacks={L2_BOOK: book}))
  File "/home/docek/.cache/pypoetry/virtualenvs/hb-core-koz5fVag-py3.10/lib/python3.10/site-packages/cryptofeed/feed.py", line 109, in __init__
    raise ValueError("Authenticated channel subscribed to, but no auth keys provided")
ValueError: Authenticated channel subscribed to, but no auth keys provided

**Operating System:**
Linux under ChromeOS

**Cryptofeed Version**
2.2.3 using Poetry

**Comment by bmoscon** [comment]
not a bug, see https://github.com/bmoscon/cryptofeed/issues/768
