### ISSUE TITLE
python3.8  run demo example error

### ISSUE THREAD

**Issue by xubinlaile** [bmoscon/cryptofeed#887]
D:\anaconda\envs\python38\python.exe C:/Users/huajia/Desktop/cryptofeed-master/cryptofeed-master/examples/demo_okx_authenticated.py
Traceback (most recent call last):
  File "C:/Users/huajia/Desktop/cryptofeed-master/cryptofeed-master/examples/demo_okx_authenticated.py", line 7, in <module>
    from cryptofeed import FeedHandler
  File "C:\Users\huajia\Desktop\cryptofeed-master\cryptofeed-master\cryptofeed\__init__.py", line 7, in <module>
    from cryptofeed.feedhandler import FeedHandler
  File "C:\Users\huajia\Desktop\cryptofeed-master\cryptofeed-master\cryptofeed\feedhandler.py", line 26, in <module>
    from cryptofeed.feed import Feed
  File "C:\Users\huajia\Desktop\cryptofeed-master\cryptofeed-master\cryptofeed\feed.py", line 20, in <module>
    from cryptofeed.types import OrderBook
ModuleNotFoundError: No module named 'cryptofeed.types'

**Comment by bmoscon** [comment]
windows is not supported. its possible to get it working, but not supported

**Comment by The1iAmNeo** [comment]
@bmoscon how do i get it working on windows ... somehow i was able to get it working in another project but now i can't seem to get it installed on any other project and i can't update the current project

**Comment by bmoscon** [comment]
i dont know how else to say windows is not supported. I dont use it, so dont ask me

**Comment by bmoscon** [comment]
@The1iAmNeo - dont spam closed tickets asking how to get it working on windows. I dont support windows, ask elsewhere (slack, discussions, etc)
