### ISSUE TITLE
demo_liquidations.py throws error because of Deribit

### ISSUE THREAD

**Issue by idclevxx** [bmoscon/cryptofeed#988]
**Describe the bug**
```
DERIBIT: Failed to parse symbol information: 'settlement_period'
Traceback (most recent call last):
  File "/folder/.venv/lib/python3.9/site-packages/cryptofeed/exchange.py", line 105, in symbol_mapping
    syms, info = cls._parse_symbol_data(data if len(data) > 1 else data[0])
  File "/folder/.venv/lib/python3.9/site-packages/cryptofeed/exchanges/deribit.py", line 62, in _parse_symbol_data
    stype = e['kind'] if e['settlement_period'] != 'perpetual' else PERPETUAL
KeyError: 'settlement_period'
```

**To Reproduce**
Run code just as in example.

**Operating System:**
 - MacOS Venture 13.4.1

**Cryptofeed Version**
- Latest, pypi

**Comment by Yn2o** [comment]
Perfect it works thx
